// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.cdn.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.volcengine.volcenginecc.cdn.inputs.DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionSpeedLimitTimeArgs;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs Empty = new DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs();

    /**
     * Indicates the maximum download speed for a single request, measured in B/S. The parameter range is 1–1,073,741,824,000,000, using a base conversion of 1,024.
     * 
     */
    @Import(name="speedLimitRate")
    private @Nullable Output<Integer> speedLimitRate;

    /**
     * @return Indicates the maximum download speed for a single request, measured in B/S. The parameter range is 1–1,073,741,824,000,000, using a base conversion of 1,024.
     * 
     */
    public Optional<Output<Integer>> speedLimitRate() {
        return Optional.ofNullable(this.speedLimitRate);
    }

    /**
     * Represents a data volume. Download throttling is enabled for a request only when the amount of data downloaded in a single request reaches this value. Unit: Byte. The parameter range is 0–1,073,741,824,000,000, using a base of 1,024 for conversion.
     * 
     */
    @Import(name="speedLimitRateAfter")
    private @Nullable Output<Integer> speedLimitRateAfter;

    /**
     * @return Represents a data volume. Download throttling is enabled for a request only when the amount of data downloaded in a single request reaches this value. Unit: Byte. The parameter range is 0–1,073,741,824,000,000, using a base of 1,024 for conversion.
     * 
     */
    public Optional<Output<Integer>> speedLimitRateAfter() {
        return Optional.ofNullable(this.speedLimitRateAfter);
    }

    /**
     * Indicates the date and time period when rate limiting occurs.
     * 
     */
    @Import(name="speedLimitTime")
    private @Nullable Output<DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionSpeedLimitTimeArgs> speedLimitTime;

    /**
     * @return Indicates the date and time period when rate limiting occurs.
     * 
     */
    public Optional<Output<DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionSpeedLimitTimeArgs>> speedLimitTime() {
        return Optional.ofNullable(this.speedLimitTime);
    }

    private DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs() {}

    private DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs(DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs $) {
        this.speedLimitRate = $.speedLimitRate;
        this.speedLimitRateAfter = $.speedLimitRateAfter;
        this.speedLimitTime = $.speedLimitTime;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs $;

        public Builder() {
            $ = new DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs();
        }

        public Builder(DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs defaults) {
            $ = new DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param speedLimitRate Indicates the maximum download speed for a single request, measured in B/S. The parameter range is 1–1,073,741,824,000,000, using a base conversion of 1,024.
         * 
         * @return builder
         * 
         */
        public Builder speedLimitRate(@Nullable Output<Integer> speedLimitRate) {
            $.speedLimitRate = speedLimitRate;
            return this;
        }

        /**
         * @param speedLimitRate Indicates the maximum download speed for a single request, measured in B/S. The parameter range is 1–1,073,741,824,000,000, using a base conversion of 1,024.
         * 
         * @return builder
         * 
         */
        public Builder speedLimitRate(Integer speedLimitRate) {
            return speedLimitRate(Output.of(speedLimitRate));
        }

        /**
         * @param speedLimitRateAfter Represents a data volume. Download throttling is enabled for a request only when the amount of data downloaded in a single request reaches this value. Unit: Byte. The parameter range is 0–1,073,741,824,000,000, using a base of 1,024 for conversion.
         * 
         * @return builder
         * 
         */
        public Builder speedLimitRateAfter(@Nullable Output<Integer> speedLimitRateAfter) {
            $.speedLimitRateAfter = speedLimitRateAfter;
            return this;
        }

        /**
         * @param speedLimitRateAfter Represents a data volume. Download throttling is enabled for a request only when the amount of data downloaded in a single request reaches this value. Unit: Byte. The parameter range is 0–1,073,741,824,000,000, using a base of 1,024 for conversion.
         * 
         * @return builder
         * 
         */
        public Builder speedLimitRateAfter(Integer speedLimitRateAfter) {
            return speedLimitRateAfter(Output.of(speedLimitRateAfter));
        }

        /**
         * @param speedLimitTime Indicates the date and time period when rate limiting occurs.
         * 
         * @return builder
         * 
         */
        public Builder speedLimitTime(@Nullable Output<DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionSpeedLimitTimeArgs> speedLimitTime) {
            $.speedLimitTime = speedLimitTime;
            return this;
        }

        /**
         * @param speedLimitTime Indicates the date and time period when rate limiting occurs.
         * 
         * @return builder
         * 
         */
        public Builder speedLimitTime(DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionSpeedLimitTimeArgs speedLimitTime) {
            return speedLimitTime(Output.of(speedLimitTime));
        }

        public DomainDownloadSpeedLimitDownloadSpeedLimitRuleDownloadSpeedLimitActionArgs build() {
            return $;
        }
    }

}
