// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.apig.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetGatewayNetworkSpecSubnet {
    /**
     * @return 可用区。
     * 
     */
    private String az;
    /**
     * @return 子网ID。
     * 
     */
    private String subnetId;
    /**
     * @return 子网名称。
     * 
     */
    private String subnetName;

    private GetGatewayNetworkSpecSubnet() {}
    /**
     * @return 可用区。
     * 
     */
    public String az() {
        return this.az;
    }
    /**
     * @return 子网ID。
     * 
     */
    public String subnetId() {
        return this.subnetId;
    }
    /**
     * @return 子网名称。
     * 
     */
    public String subnetName() {
        return this.subnetName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGatewayNetworkSpecSubnet defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String az;
        private String subnetId;
        private String subnetName;
        public Builder() {}
        public Builder(GetGatewayNetworkSpecSubnet defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.az = defaults.az;
    	      this.subnetId = defaults.subnetId;
    	      this.subnetName = defaults.subnetName;
        }

        @CustomType.Setter
        public Builder az(String az) {
            if (az == null) {
              throw new MissingRequiredPropertyException("GetGatewayNetworkSpecSubnet", "az");
            }
            this.az = az;
            return this;
        }
        @CustomType.Setter
        public Builder subnetId(String subnetId) {
            if (subnetId == null) {
              throw new MissingRequiredPropertyException("GetGatewayNetworkSpecSubnet", "subnetId");
            }
            this.subnetId = subnetId;
            return this;
        }
        @CustomType.Setter
        public Builder subnetName(String subnetName) {
            if (subnetName == null) {
              throw new MissingRequiredPropertyException("GetGatewayNetworkSpecSubnet", "subnetName");
            }
            this.subnetName = subnetName;
            return this;
        }
        public GetGatewayNetworkSpecSubnet build() {
            final var _resultValue = new GetGatewayNetworkSpecSubnet();
            _resultValue.az = az;
            _resultValue.subnetId = subnetId;
            _resultValue.subnetName = subnetName;
            return _resultValue;
        }
    }
}
