// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.filenas.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetMountPointPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMountPointPlainArgs Empty = new GetMountPointPlainArgs();

    /**
     * Uniquely identifies the resource.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return Uniquely identifies the resource.
     * 
     */
    public String id() {
        return this.id;
    }

    private GetMountPointPlainArgs() {}

    private GetMountPointPlainArgs(GetMountPointPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMountPointPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMountPointPlainArgs $;

        public Builder() {
            $ = new GetMountPointPlainArgs();
        }

        public Builder(GetMountPointPlainArgs defaults) {
            $ = new GetMountPointPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Uniquely identifies the resource.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetMountPointPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetMountPointPlainArgs", "id");
            }
            return $;
        }
    }

}
