# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['VpcFireWallAclRuleArgs', 'VpcFireWallAclRule']

@pulumi.input_type
class VpcFireWallAclRuleArgs:
    def __init__(__self__, *,
                 action: pulumi.Input[builtins.str],
                 destination: pulumi.Input[builtins.str],
                 destination_type: pulumi.Input[builtins.str],
                 proto: pulumi.Input[builtins.str],
                 source: pulumi.Input[builtins.str],
                 source_type: pulumi.Input[builtins.str],
                 vpc_firewall_id: pulumi.Input[builtins.str],
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port_type: Optional[pulumi.Input[builtins.str]] = None,
                 domain_resolution_mode: Optional[pulumi.Input[builtins.str]] = None,
                 end_time: Optional[pulumi.Input[builtins.int]] = None,
                 ip_type: Optional[pulumi.Input[builtins.str]] = None,
                 prio: Optional[pulumi.Input[builtins.int]] = None,
                 repeat_days: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]] = None,
                 repeat_end_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_start_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_type: Optional[pulumi.Input[builtins.str]] = None,
                 start_time: Optional[pulumi.Input[builtins.int]] = None,
                 status: Optional[pulumi.Input[builtins.bool]] = None):
        """
        The set of arguments for constructing a VpcFireWallAclRule resource.
        :param pulumi.Input[builtins.str] action: Policy action: accept (allow); deny (block); monitor (observe).
        :param pulumi.Input[builtins.str] destination: Destination address. The value depends on DestinationType: net for destination CIDR address; group for destination address book UUIDs, separated by commas; domain for destination domain name.
        :param pulumi.Input[builtins.str] destination_type: Destination address type: net for subnet (CIDR format); group for address book (UUID format); domain for domain name.
        :param pulumi.Input[builtins.str] proto: Protocol type: ICMP, TCP, UDP, ANY. Only TCP is supported when the destination address type is domain.
        :param pulumi.Input[builtins.str] source: Source address. The value depends on SourceType: net for source CIDR address; group for source address book UUIDs, separated by commas.
        :param pulumi.Input[builtins.str] source_type: Source address type: net for subnet (CIDR format); group for address book (UUID format).
        :param pulumi.Input[builtins.str] vpc_firewall_id: VPC border firewall instance ID.
        :param pulumi.Input[builtins.str] description: Policy description, used to explain the purpose and function of the policy.
        :param pulumi.Input[builtins.str] dest_port: Destination port, single port or port range (e.g., 22/22, 100/200). If DestPortType is group, it is a list of port address book UUIDs, separated by commas. Leave blank if protocol is ICMP or ANY.
        :param pulumi.Input[builtins.str] dest_port_type: Destination port type: port (single port or port range); group (port address book).
        :param pulumi.Input[builtins.str] domain_resolution_mode: Domain name resolution mode: fqdn for full domain name resolution; dns for dynamic DNS resolution.
        :param pulumi.Input[builtins.int] end_time: Policy activation end time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.str] ip_type: IP version: v4 indicates IPv4; v6 indicates IPv6.
        :param pulumi.Input[builtins.int] prio: Policy priority. Lower values indicate higher priority. 0 is the lowest priority, 1 is the highest. When modifying, the minimum value for this parameter is 1.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.int]]] repeat_days: Specific dates for repeated activation. Valid only when RepeatType is Weekly (0-6 for Sunday to Saturday) or Monthly (1-31 for each day of the month).
        :param pulumi.Input[builtins.str] repeat_end_time: Recurring daily end time, format: hh:mm. Valid only when RepeatType is Weekly or Monthly.
        :param pulumi.Input[builtins.str] repeat_start_time: Recurring daily start time, format: hh:mm. Valid only when RepeatType is Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.str] repeat_type: Activation repeat type: Permanent always effective; Once single activation; Daily repeat daily; Weekly repeat weekly; Monthly repeat monthly.
        :param pulumi.Input[builtins.int] start_time: Policy activation start time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.bool] status: Policy enable status: true enabled; false disabled.
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "destination", destination)
        pulumi.set(__self__, "destination_type", destination_type)
        pulumi.set(__self__, "proto", proto)
        pulumi.set(__self__, "source", source)
        pulumi.set(__self__, "source_type", source_type)
        pulumi.set(__self__, "vpc_firewall_id", vpc_firewall_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if dest_port is not None:
            pulumi.set(__self__, "dest_port", dest_port)
        if dest_port_type is not None:
            pulumi.set(__self__, "dest_port_type", dest_port_type)
        if domain_resolution_mode is not None:
            pulumi.set(__self__, "domain_resolution_mode", domain_resolution_mode)
        if end_time is not None:
            pulumi.set(__self__, "end_time", end_time)
        if ip_type is not None:
            pulumi.set(__self__, "ip_type", ip_type)
        if prio is not None:
            pulumi.set(__self__, "prio", prio)
        if repeat_days is not None:
            pulumi.set(__self__, "repeat_days", repeat_days)
        if repeat_end_time is not None:
            pulumi.set(__self__, "repeat_end_time", repeat_end_time)
        if repeat_start_time is not None:
            pulumi.set(__self__, "repeat_start_time", repeat_start_time)
        if repeat_type is not None:
            pulumi.set(__self__, "repeat_type", repeat_type)
        if start_time is not None:
            pulumi.set(__self__, "start_time", start_time)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter
    def action(self) -> pulumi.Input[builtins.str]:
        """
        Policy action: accept (allow); deny (block); monitor (observe).
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def destination(self) -> pulumi.Input[builtins.str]:
        """
        Destination address. The value depends on DestinationType: net for destination CIDR address; group for destination address book UUIDs, separated by commas; domain for destination domain name.
        """
        return pulumi.get(self, "destination")

    @destination.setter
    def destination(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "destination", value)

    @property
    @pulumi.getter(name="destinationType")
    def destination_type(self) -> pulumi.Input[builtins.str]:
        """
        Destination address type: net for subnet (CIDR format); group for address book (UUID format); domain for domain name.
        """
        return pulumi.get(self, "destination_type")

    @destination_type.setter
    def destination_type(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "destination_type", value)

    @property
    @pulumi.getter
    def proto(self) -> pulumi.Input[builtins.str]:
        """
        Protocol type: ICMP, TCP, UDP, ANY. Only TCP is supported when the destination address type is domain.
        """
        return pulumi.get(self, "proto")

    @proto.setter
    def proto(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "proto", value)

    @property
    @pulumi.getter
    def source(self) -> pulumi.Input[builtins.str]:
        """
        Source address. The value depends on SourceType: net for source CIDR address; group for source address book UUIDs, separated by commas.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "source", value)

    @property
    @pulumi.getter(name="sourceType")
    def source_type(self) -> pulumi.Input[builtins.str]:
        """
        Source address type: net for subnet (CIDR format); group for address book (UUID format).
        """
        return pulumi.get(self, "source_type")

    @source_type.setter
    def source_type(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "source_type", value)

    @property
    @pulumi.getter(name="vpcFirewallId")
    def vpc_firewall_id(self) -> pulumi.Input[builtins.str]:
        """
        VPC border firewall instance ID.
        """
        return pulumi.get(self, "vpc_firewall_id")

    @vpc_firewall_id.setter
    def vpc_firewall_id(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "vpc_firewall_id", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Policy description, used to explain the purpose and function of the policy.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="destPort")
    def dest_port(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination port, single port or port range (e.g., 22/22, 100/200). If DestPortType is group, it is a list of port address book UUIDs, separated by commas. Leave blank if protocol is ICMP or ANY.
        """
        return pulumi.get(self, "dest_port")

    @dest_port.setter
    def dest_port(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "dest_port", value)

    @property
    @pulumi.getter(name="destPortType")
    def dest_port_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination port type: port (single port or port range); group (port address book).
        """
        return pulumi.get(self, "dest_port_type")

    @dest_port_type.setter
    def dest_port_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "dest_port_type", value)

    @property
    @pulumi.getter(name="domainResolutionMode")
    def domain_resolution_mode(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Domain name resolution mode: fqdn for full domain name resolution; dns for dynamic DNS resolution.
        """
        return pulumi.get(self, "domain_resolution_mode")

    @domain_resolution_mode.setter
    def domain_resolution_mode(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "domain_resolution_mode", value)

    @property
    @pulumi.getter(name="endTime")
    def end_time(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Policy activation end time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "end_time")

    @end_time.setter
    def end_time(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "end_time", value)

    @property
    @pulumi.getter(name="ipType")
    def ip_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        IP version: v4 indicates IPv4; v6 indicates IPv6.
        """
        return pulumi.get(self, "ip_type")

    @ip_type.setter
    def ip_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "ip_type", value)

    @property
    @pulumi.getter
    def prio(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Policy priority. Lower values indicate higher priority. 0 is the lowest priority, 1 is the highest. When modifying, the minimum value for this parameter is 1.
        """
        return pulumi.get(self, "prio")

    @prio.setter
    def prio(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "prio", value)

    @property
    @pulumi.getter(name="repeatDays")
    def repeat_days(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]]:
        """
        Specific dates for repeated activation. Valid only when RepeatType is Weekly (0-6 for Sunday to Saturday) or Monthly (1-31 for each day of the month).
        """
        return pulumi.get(self, "repeat_days")

    @repeat_days.setter
    def repeat_days(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]]):
        pulumi.set(self, "repeat_days", value)

    @property
    @pulumi.getter(name="repeatEndTime")
    def repeat_end_time(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Recurring daily end time, format: hh:mm. Valid only when RepeatType is Weekly or Monthly.
        """
        return pulumi.get(self, "repeat_end_time")

    @repeat_end_time.setter
    def repeat_end_time(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "repeat_end_time", value)

    @property
    @pulumi.getter(name="repeatStartTime")
    def repeat_start_time(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Recurring daily start time, format: hh:mm. Valid only when RepeatType is Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "repeat_start_time")

    @repeat_start_time.setter
    def repeat_start_time(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "repeat_start_time", value)

    @property
    @pulumi.getter(name="repeatType")
    def repeat_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Activation repeat type: Permanent always effective; Once single activation; Daily repeat daily; Weekly repeat weekly; Monthly repeat monthly.
        """
        return pulumi.get(self, "repeat_type")

    @repeat_type.setter
    def repeat_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "repeat_type", value)

    @property
    @pulumi.getter(name="startTime")
    def start_time(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Policy activation start time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "start_time")

    @start_time.setter
    def start_time(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "start_time", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Policy enable status: true enabled; false disabled.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "status", value)


@pulumi.input_type
class _VpcFireWallAclRuleState:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[builtins.str]] = None,
                 action: Optional[pulumi.Input[builtins.str]] = None,
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port_group_type: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port_list_v1s: Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleDestPortListV1Args']]]] = None,
                 dest_port_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 dest_port_type: Optional[pulumi.Input[builtins.str]] = None,
                 destination: Optional[pulumi.Input[builtins.str]] = None,
                 destination_cidr_list_v1s: Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleDestinationCidrListV1Args']]]] = None,
                 destination_cidr_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 destination_domain_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 destination_group_type: Optional[pulumi.Input[builtins.str]] = None,
                 destination_type: Optional[pulumi.Input[builtins.str]] = None,
                 domain_resolution_mode: Optional[pulumi.Input[builtins.str]] = None,
                 effect_status: Optional[pulumi.Input[builtins.int]] = None,
                 end_time: Optional[pulumi.Input[builtins.int]] = None,
                 hit_cnt: Optional[pulumi.Input[builtins.int]] = None,
                 ip_type: Optional[pulumi.Input[builtins.str]] = None,
                 is_effected: Optional[pulumi.Input[builtins.bool]] = None,
                 prio: Optional[pulumi.Input[builtins.int]] = None,
                 proto: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_days: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]] = None,
                 repeat_end_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_start_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_type: Optional[pulumi.Input[builtins.str]] = None,
                 rule_id: Optional[pulumi.Input[builtins.str]] = None,
                 source: Optional[pulumi.Input[builtins.str]] = None,
                 source_cidr_list_v1s: Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleSourceCidrListV1Args']]]] = None,
                 source_cidr_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 source_group_type: Optional[pulumi.Input[builtins.str]] = None,
                 source_type: Optional[pulumi.Input[builtins.str]] = None,
                 start_time: Optional[pulumi.Input[builtins.int]] = None,
                 status: Optional[pulumi.Input[builtins.bool]] = None,
                 update_time: Optional[pulumi.Input[builtins.int]] = None,
                 use_count: Optional[pulumi.Input[builtins.int]] = None,
                 vpc_firewall_id: Optional[pulumi.Input[builtins.str]] = None,
                 vpc_firewall_name: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering VpcFireWallAclRule resources.
        :param pulumi.Input[builtins.str] account_id: User unique ID.
        :param pulumi.Input[builtins.str] action: Policy action: accept (allow); deny (block); monitor (observe).
        :param pulumi.Input[builtins.str] description: Policy description, used to explain the purpose and function of the policy.
        :param pulumi.Input[builtins.str] dest_port: Destination port, single port or port range (e.g., 22/22, 100/200). If DestPortType is group, it is a list of port address book UUIDs, separated by commas. Leave blank if protocol is ICMP or ANY.
        :param pulumi.Input[builtins.str] dest_port_group_type: Destination port book type.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] dest_port_lists: Destination port list.
        :param pulumi.Input[builtins.str] dest_port_type: Destination port type: port (single port or port range); group (port address book).
        :param pulumi.Input[builtins.str] destination: Destination address. The value depends on DestinationType: net for destination CIDR address; group for destination address book UUIDs, separated by commas; domain for destination domain name.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] destination_cidr_lists: Destination CIDR list.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] destination_domain_lists: Destination domain name list.
        :param pulumi.Input[builtins.str] destination_group_type: Destination address book type.
        :param pulumi.Input[builtins.str] destination_type: Destination address type: net for subnet (CIDR format); group for address book (UUID format); domain for domain name.
        :param pulumi.Input[builtins.str] domain_resolution_mode: Domain name resolution mode: fqdn for full domain name resolution; dns for dynamic DNS resolution.
        :param pulumi.Input[builtins.int] effect_status: Effectiveness status of the access control policy. 1: not effective; 2: deploying; 3: effective.
        :param pulumi.Input[builtins.int] end_time: Policy activation end time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.int] hit_cnt: Hit count of the access control policy.
        :param pulumi.Input[builtins.str] ip_type: IP version: v4 indicates IPv4; v6 indicates IPv6.
        :param pulumi.Input[builtins.bool] is_effected: Whether the access control policy is effective. true: effective; false: not effective.
        :param pulumi.Input[builtins.int] prio: Policy priority. Lower values indicate higher priority. 0 is the lowest priority, 1 is the highest. When modifying, the minimum value for this parameter is 1.
        :param pulumi.Input[builtins.str] proto: Protocol type: ICMP, TCP, UDP, ANY. Only TCP is supported when the destination address type is domain.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.int]]] repeat_days: Specific dates for repeated activation. Valid only when RepeatType is Weekly (0-6 for Sunday to Saturday) or Monthly (1-31 for each day of the month).
        :param pulumi.Input[builtins.str] repeat_end_time: Recurring daily end time, format: hh:mm. Valid only when RepeatType is Weekly or Monthly.
        :param pulumi.Input[builtins.str] repeat_start_time: Recurring daily start time, format: hh:mm. Valid only when RepeatType is Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.str] repeat_type: Activation repeat type: Permanent always effective; Once single activation; Daily repeat daily; Weekly repeat weekly; Monthly repeat monthly.
        :param pulumi.Input[builtins.str] rule_id: Unique ID of the access control policy.
        :param pulumi.Input[builtins.str] source: Source address. The value depends on SourceType: net for source CIDR address; group for source address book UUIDs, separated by commas.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] source_cidr_lists: Source CIDR list.
        :param pulumi.Input[builtins.str] source_group_type: Source address book type.
        :param pulumi.Input[builtins.str] source_type: Source address type: net for subnet (CIDR format); group for address book (UUID format).
        :param pulumi.Input[builtins.int] start_time: Policy activation start time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.bool] status: Policy enable status: true enabled; false disabled.
        :param pulumi.Input[builtins.int] update_time: Last policy update time, Unix timestamp.
        :param pulumi.Input[builtins.int] use_count: Number of policies used.
        :param pulumi.Input[builtins.str] vpc_firewall_id: VPC border firewall instance ID.
        :param pulumi.Input[builtins.str] vpc_firewall_name: VPC border firewall instance name.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if action is not None:
            pulumi.set(__self__, "action", action)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if dest_port is not None:
            pulumi.set(__self__, "dest_port", dest_port)
        if dest_port_group_type is not None:
            pulumi.set(__self__, "dest_port_group_type", dest_port_group_type)
        if dest_port_list_v1s is not None:
            pulumi.set(__self__, "dest_port_list_v1s", dest_port_list_v1s)
        if dest_port_lists is not None:
            pulumi.set(__self__, "dest_port_lists", dest_port_lists)
        if dest_port_type is not None:
            pulumi.set(__self__, "dest_port_type", dest_port_type)
        if destination is not None:
            pulumi.set(__self__, "destination", destination)
        if destination_cidr_list_v1s is not None:
            pulumi.set(__self__, "destination_cidr_list_v1s", destination_cidr_list_v1s)
        if destination_cidr_lists is not None:
            pulumi.set(__self__, "destination_cidr_lists", destination_cidr_lists)
        if destination_domain_lists is not None:
            pulumi.set(__self__, "destination_domain_lists", destination_domain_lists)
        if destination_group_type is not None:
            pulumi.set(__self__, "destination_group_type", destination_group_type)
        if destination_type is not None:
            pulumi.set(__self__, "destination_type", destination_type)
        if domain_resolution_mode is not None:
            pulumi.set(__self__, "domain_resolution_mode", domain_resolution_mode)
        if effect_status is not None:
            pulumi.set(__self__, "effect_status", effect_status)
        if end_time is not None:
            pulumi.set(__self__, "end_time", end_time)
        if hit_cnt is not None:
            pulumi.set(__self__, "hit_cnt", hit_cnt)
        if ip_type is not None:
            pulumi.set(__self__, "ip_type", ip_type)
        if is_effected is not None:
            pulumi.set(__self__, "is_effected", is_effected)
        if prio is not None:
            pulumi.set(__self__, "prio", prio)
        if proto is not None:
            pulumi.set(__self__, "proto", proto)
        if repeat_days is not None:
            pulumi.set(__self__, "repeat_days", repeat_days)
        if repeat_end_time is not None:
            pulumi.set(__self__, "repeat_end_time", repeat_end_time)
        if repeat_start_time is not None:
            pulumi.set(__self__, "repeat_start_time", repeat_start_time)
        if repeat_type is not None:
            pulumi.set(__self__, "repeat_type", repeat_type)
        if rule_id is not None:
            pulumi.set(__self__, "rule_id", rule_id)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if source_cidr_list_v1s is not None:
            pulumi.set(__self__, "source_cidr_list_v1s", source_cidr_list_v1s)
        if source_cidr_lists is not None:
            pulumi.set(__self__, "source_cidr_lists", source_cidr_lists)
        if source_group_type is not None:
            pulumi.set(__self__, "source_group_type", source_group_type)
        if source_type is not None:
            pulumi.set(__self__, "source_type", source_type)
        if start_time is not None:
            pulumi.set(__self__, "start_time", start_time)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if update_time is not None:
            pulumi.set(__self__, "update_time", update_time)
        if use_count is not None:
            pulumi.set(__self__, "use_count", use_count)
        if vpc_firewall_id is not None:
            pulumi.set(__self__, "vpc_firewall_id", vpc_firewall_id)
        if vpc_firewall_name is not None:
            pulumi.set(__self__, "vpc_firewall_name", vpc_firewall_name)

    @property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        User unique ID.
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "account_id", value)

    @property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Policy action: accept (allow); deny (block); monitor (observe).
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Policy description, used to explain the purpose and function of the policy.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="destPort")
    def dest_port(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination port, single port or port range (e.g., 22/22, 100/200). If DestPortType is group, it is a list of port address book UUIDs, separated by commas. Leave blank if protocol is ICMP or ANY.
        """
        return pulumi.get(self, "dest_port")

    @dest_port.setter
    def dest_port(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "dest_port", value)

    @property
    @pulumi.getter(name="destPortGroupType")
    def dest_port_group_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination port book type.
        """
        return pulumi.get(self, "dest_port_group_type")

    @dest_port_group_type.setter
    def dest_port_group_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "dest_port_group_type", value)

    @property
    @pulumi.getter(name="destPortListV1s")
    def dest_port_list_v1s(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleDestPortListV1Args']]]]:
        return pulumi.get(self, "dest_port_list_v1s")

    @dest_port_list_v1s.setter
    def dest_port_list_v1s(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleDestPortListV1Args']]]]):
        pulumi.set(self, "dest_port_list_v1s", value)

    @property
    @pulumi.getter(name="destPortLists")
    def dest_port_lists(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        Destination port list.
        """
        return pulumi.get(self, "dest_port_lists")

    @dest_port_lists.setter
    def dest_port_lists(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "dest_port_lists", value)

    @property
    @pulumi.getter(name="destPortType")
    def dest_port_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination port type: port (single port or port range); group (port address book).
        """
        return pulumi.get(self, "dest_port_type")

    @dest_port_type.setter
    def dest_port_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "dest_port_type", value)

    @property
    @pulumi.getter
    def destination(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination address. The value depends on DestinationType: net for destination CIDR address; group for destination address book UUIDs, separated by commas; domain for destination domain name.
        """
        return pulumi.get(self, "destination")

    @destination.setter
    def destination(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "destination", value)

    @property
    @pulumi.getter(name="destinationCidrListV1s")
    def destination_cidr_list_v1s(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleDestinationCidrListV1Args']]]]:
        return pulumi.get(self, "destination_cidr_list_v1s")

    @destination_cidr_list_v1s.setter
    def destination_cidr_list_v1s(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleDestinationCidrListV1Args']]]]):
        pulumi.set(self, "destination_cidr_list_v1s", value)

    @property
    @pulumi.getter(name="destinationCidrLists")
    def destination_cidr_lists(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        Destination CIDR list.
        """
        return pulumi.get(self, "destination_cidr_lists")

    @destination_cidr_lists.setter
    def destination_cidr_lists(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "destination_cidr_lists", value)

    @property
    @pulumi.getter(name="destinationDomainLists")
    def destination_domain_lists(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        Destination domain name list.
        """
        return pulumi.get(self, "destination_domain_lists")

    @destination_domain_lists.setter
    def destination_domain_lists(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "destination_domain_lists", value)

    @property
    @pulumi.getter(name="destinationGroupType")
    def destination_group_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination address book type.
        """
        return pulumi.get(self, "destination_group_type")

    @destination_group_type.setter
    def destination_group_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "destination_group_type", value)

    @property
    @pulumi.getter(name="destinationType")
    def destination_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Destination address type: net for subnet (CIDR format); group for address book (UUID format); domain for domain name.
        """
        return pulumi.get(self, "destination_type")

    @destination_type.setter
    def destination_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "destination_type", value)

    @property
    @pulumi.getter(name="domainResolutionMode")
    def domain_resolution_mode(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Domain name resolution mode: fqdn for full domain name resolution; dns for dynamic DNS resolution.
        """
        return pulumi.get(self, "domain_resolution_mode")

    @domain_resolution_mode.setter
    def domain_resolution_mode(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "domain_resolution_mode", value)

    @property
    @pulumi.getter(name="effectStatus")
    def effect_status(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Effectiveness status of the access control policy. 1: not effective; 2: deploying; 3: effective.
        """
        return pulumi.get(self, "effect_status")

    @effect_status.setter
    def effect_status(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "effect_status", value)

    @property
    @pulumi.getter(name="endTime")
    def end_time(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Policy activation end time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "end_time")

    @end_time.setter
    def end_time(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "end_time", value)

    @property
    @pulumi.getter(name="hitCnt")
    def hit_cnt(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Hit count of the access control policy.
        """
        return pulumi.get(self, "hit_cnt")

    @hit_cnt.setter
    def hit_cnt(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "hit_cnt", value)

    @property
    @pulumi.getter(name="ipType")
    def ip_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        IP version: v4 indicates IPv4; v6 indicates IPv6.
        """
        return pulumi.get(self, "ip_type")

    @ip_type.setter
    def ip_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "ip_type", value)

    @property
    @pulumi.getter(name="isEffected")
    def is_effected(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether the access control policy is effective. true: effective; false: not effective.
        """
        return pulumi.get(self, "is_effected")

    @is_effected.setter
    def is_effected(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "is_effected", value)

    @property
    @pulumi.getter
    def prio(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Policy priority. Lower values indicate higher priority. 0 is the lowest priority, 1 is the highest. When modifying, the minimum value for this parameter is 1.
        """
        return pulumi.get(self, "prio")

    @prio.setter
    def prio(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "prio", value)

    @property
    @pulumi.getter
    def proto(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Protocol type: ICMP, TCP, UDP, ANY. Only TCP is supported when the destination address type is domain.
        """
        return pulumi.get(self, "proto")

    @proto.setter
    def proto(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "proto", value)

    @property
    @pulumi.getter(name="repeatDays")
    def repeat_days(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]]:
        """
        Specific dates for repeated activation. Valid only when RepeatType is Weekly (0-6 for Sunday to Saturday) or Monthly (1-31 for each day of the month).
        """
        return pulumi.get(self, "repeat_days")

    @repeat_days.setter
    def repeat_days(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]]):
        pulumi.set(self, "repeat_days", value)

    @property
    @pulumi.getter(name="repeatEndTime")
    def repeat_end_time(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Recurring daily end time, format: hh:mm. Valid only when RepeatType is Weekly or Monthly.
        """
        return pulumi.get(self, "repeat_end_time")

    @repeat_end_time.setter
    def repeat_end_time(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "repeat_end_time", value)

    @property
    @pulumi.getter(name="repeatStartTime")
    def repeat_start_time(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Recurring daily start time, format: hh:mm. Valid only when RepeatType is Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "repeat_start_time")

    @repeat_start_time.setter
    def repeat_start_time(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "repeat_start_time", value)

    @property
    @pulumi.getter(name="repeatType")
    def repeat_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Activation repeat type: Permanent always effective; Once single activation; Daily repeat daily; Weekly repeat weekly; Monthly repeat monthly.
        """
        return pulumi.get(self, "repeat_type")

    @repeat_type.setter
    def repeat_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "repeat_type", value)

    @property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Unique ID of the access control policy.
        """
        return pulumi.get(self, "rule_id")

    @rule_id.setter
    def rule_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "rule_id", value)

    @property
    @pulumi.getter
    def source(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Source address. The value depends on SourceType: net for source CIDR address; group for source address book UUIDs, separated by commas.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "source", value)

    @property
    @pulumi.getter(name="sourceCidrListV1s")
    def source_cidr_list_v1s(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleSourceCidrListV1Args']]]]:
        return pulumi.get(self, "source_cidr_list_v1s")

    @source_cidr_list_v1s.setter
    def source_cidr_list_v1s(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VpcFireWallAclRuleSourceCidrListV1Args']]]]):
        pulumi.set(self, "source_cidr_list_v1s", value)

    @property
    @pulumi.getter(name="sourceCidrLists")
    def source_cidr_lists(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        Source CIDR list.
        """
        return pulumi.get(self, "source_cidr_lists")

    @source_cidr_lists.setter
    def source_cidr_lists(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "source_cidr_lists", value)

    @property
    @pulumi.getter(name="sourceGroupType")
    def source_group_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Source address book type.
        """
        return pulumi.get(self, "source_group_type")

    @source_group_type.setter
    def source_group_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "source_group_type", value)

    @property
    @pulumi.getter(name="sourceType")
    def source_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Source address type: net for subnet (CIDR format); group for address book (UUID format).
        """
        return pulumi.get(self, "source_type")

    @source_type.setter
    def source_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "source_type", value)

    @property
    @pulumi.getter(name="startTime")
    def start_time(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Policy activation start time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "start_time")

    @start_time.setter
    def start_time(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "start_time", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Policy enable status: true enabled; false disabled.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "status", value)

    @property
    @pulumi.getter(name="updateTime")
    def update_time(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Last policy update time, Unix timestamp.
        """
        return pulumi.get(self, "update_time")

    @update_time.setter
    def update_time(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "update_time", value)

    @property
    @pulumi.getter(name="useCount")
    def use_count(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Number of policies used.
        """
        return pulumi.get(self, "use_count")

    @use_count.setter
    def use_count(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "use_count", value)

    @property
    @pulumi.getter(name="vpcFirewallId")
    def vpc_firewall_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        VPC border firewall instance ID.
        """
        return pulumi.get(self, "vpc_firewall_id")

    @vpc_firewall_id.setter
    def vpc_firewall_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "vpc_firewall_id", value)

    @property
    @pulumi.getter(name="vpcFirewallName")
    def vpc_firewall_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        VPC border firewall instance name.
        """
        return pulumi.get(self, "vpc_firewall_name")

    @vpc_firewall_name.setter
    def vpc_firewall_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "vpc_firewall_name", value)


@pulumi.type_token("volcenginecc:fwcenter/vpcFireWallAclRule:VpcFireWallAclRule")
class VpcFireWallAclRule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[builtins.str]] = None,
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port_type: Optional[pulumi.Input[builtins.str]] = None,
                 destination: Optional[pulumi.Input[builtins.str]] = None,
                 destination_type: Optional[pulumi.Input[builtins.str]] = None,
                 domain_resolution_mode: Optional[pulumi.Input[builtins.str]] = None,
                 end_time: Optional[pulumi.Input[builtins.int]] = None,
                 ip_type: Optional[pulumi.Input[builtins.str]] = None,
                 prio: Optional[pulumi.Input[builtins.int]] = None,
                 proto: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_days: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]] = None,
                 repeat_end_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_start_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_type: Optional[pulumi.Input[builtins.str]] = None,
                 source: Optional[pulumi.Input[builtins.str]] = None,
                 source_type: Optional[pulumi.Input[builtins.str]] = None,
                 start_time: Optional[pulumi.Input[builtins.int]] = None,
                 status: Optional[pulumi.Input[builtins.bool]] = None,
                 vpc_firewall_id: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        VPC border firewall access control policy (ACL rule), used to define allow, block, or observe rules for traffic between VPCs.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_volcenginecc as volcenginecc

        example = volcenginecc.fwcenter.VpcFireWallAclRule("Example",
            action="accept",
            description="this is a test",
            dest_port="60000",
            dest_port_type="port",
            destination="0.0.0.0/0",
            destination_type="net",
            domain_resolution_mode="",
            end_time=1782662340,
            ip_type="v4",
            prio=1,
            proto="TCP",
            repeat_days=[
                2,
                3,
            ],
            repeat_end_time="04:00",
            repeat_start_time="02:00",
            repeat_type="Weekly",
            source="0.0.0.0/0",
            source_type="net",
            start_time=1782403200,
            status=True,
            vpc_firewall_id="vfw-yeoxxxxxx4vvsy6xj")
        ```

        ## Import

        ```sh
        $ pulumi import volcenginecc:fwcenter/vpcFireWallAclRule:VpcFireWallAclRule example "vpc_firewall_id|rule_id"
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] action: Policy action: accept (allow); deny (block); monitor (observe).
        :param pulumi.Input[builtins.str] description: Policy description, used to explain the purpose and function of the policy.
        :param pulumi.Input[builtins.str] dest_port: Destination port, single port or port range (e.g., 22/22, 100/200). If DestPortType is group, it is a list of port address book UUIDs, separated by commas. Leave blank if protocol is ICMP or ANY.
        :param pulumi.Input[builtins.str] dest_port_type: Destination port type: port (single port or port range); group (port address book).
        :param pulumi.Input[builtins.str] destination: Destination address. The value depends on DestinationType: net for destination CIDR address; group for destination address book UUIDs, separated by commas; domain for destination domain name.
        :param pulumi.Input[builtins.str] destination_type: Destination address type: net for subnet (CIDR format); group for address book (UUID format); domain for domain name.
        :param pulumi.Input[builtins.str] domain_resolution_mode: Domain name resolution mode: fqdn for full domain name resolution; dns for dynamic DNS resolution.
        :param pulumi.Input[builtins.int] end_time: Policy activation end time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.str] ip_type: IP version: v4 indicates IPv4; v6 indicates IPv6.
        :param pulumi.Input[builtins.int] prio: Policy priority. Lower values indicate higher priority. 0 is the lowest priority, 1 is the highest. When modifying, the minimum value for this parameter is 1.
        :param pulumi.Input[builtins.str] proto: Protocol type: ICMP, TCP, UDP, ANY. Only TCP is supported when the destination address type is domain.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.int]]] repeat_days: Specific dates for repeated activation. Valid only when RepeatType is Weekly (0-6 for Sunday to Saturday) or Monthly (1-31 for each day of the month).
        :param pulumi.Input[builtins.str] repeat_end_time: Recurring daily end time, format: hh:mm. Valid only when RepeatType is Weekly or Monthly.
        :param pulumi.Input[builtins.str] repeat_start_time: Recurring daily start time, format: hh:mm. Valid only when RepeatType is Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.str] repeat_type: Activation repeat type: Permanent always effective; Once single activation; Daily repeat daily; Weekly repeat weekly; Monthly repeat monthly.
        :param pulumi.Input[builtins.str] source: Source address. The value depends on SourceType: net for source CIDR address; group for source address book UUIDs, separated by commas.
        :param pulumi.Input[builtins.str] source_type: Source address type: net for subnet (CIDR format); group for address book (UUID format).
        :param pulumi.Input[builtins.int] start_time: Policy activation start time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.bool] status: Policy enable status: true enabled; false disabled.
        :param pulumi.Input[builtins.str] vpc_firewall_id: VPC border firewall instance ID.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VpcFireWallAclRuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        VPC border firewall access control policy (ACL rule), used to define allow, block, or observe rules for traffic between VPCs.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_volcenginecc as volcenginecc

        example = volcenginecc.fwcenter.VpcFireWallAclRule("Example",
            action="accept",
            description="this is a test",
            dest_port="60000",
            dest_port_type="port",
            destination="0.0.0.0/0",
            destination_type="net",
            domain_resolution_mode="",
            end_time=1782662340,
            ip_type="v4",
            prio=1,
            proto="TCP",
            repeat_days=[
                2,
                3,
            ],
            repeat_end_time="04:00",
            repeat_start_time="02:00",
            repeat_type="Weekly",
            source="0.0.0.0/0",
            source_type="net",
            start_time=1782403200,
            status=True,
            vpc_firewall_id="vfw-yeoxxxxxx4vvsy6xj")
        ```

        ## Import

        ```sh
        $ pulumi import volcenginecc:fwcenter/vpcFireWallAclRule:VpcFireWallAclRule example "vpc_firewall_id|rule_id"
        ```

        :param str resource_name: The name of the resource.
        :param VpcFireWallAclRuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VpcFireWallAclRuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[builtins.str]] = None,
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port: Optional[pulumi.Input[builtins.str]] = None,
                 dest_port_type: Optional[pulumi.Input[builtins.str]] = None,
                 destination: Optional[pulumi.Input[builtins.str]] = None,
                 destination_type: Optional[pulumi.Input[builtins.str]] = None,
                 domain_resolution_mode: Optional[pulumi.Input[builtins.str]] = None,
                 end_time: Optional[pulumi.Input[builtins.int]] = None,
                 ip_type: Optional[pulumi.Input[builtins.str]] = None,
                 prio: Optional[pulumi.Input[builtins.int]] = None,
                 proto: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_days: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]] = None,
                 repeat_end_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_start_time: Optional[pulumi.Input[builtins.str]] = None,
                 repeat_type: Optional[pulumi.Input[builtins.str]] = None,
                 source: Optional[pulumi.Input[builtins.str]] = None,
                 source_type: Optional[pulumi.Input[builtins.str]] = None,
                 start_time: Optional[pulumi.Input[builtins.int]] = None,
                 status: Optional[pulumi.Input[builtins.bool]] = None,
                 vpc_firewall_id: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VpcFireWallAclRuleArgs.__new__(VpcFireWallAclRuleArgs)

            if action is None and not opts.urn:
                raise TypeError("Missing required property 'action'")
            __props__.__dict__["action"] = action
            __props__.__dict__["description"] = description
            __props__.__dict__["dest_port"] = dest_port
            __props__.__dict__["dest_port_type"] = dest_port_type
            if destination is None and not opts.urn:
                raise TypeError("Missing required property 'destination'")
            __props__.__dict__["destination"] = destination
            if destination_type is None and not opts.urn:
                raise TypeError("Missing required property 'destination_type'")
            __props__.__dict__["destination_type"] = destination_type
            __props__.__dict__["domain_resolution_mode"] = domain_resolution_mode
            __props__.__dict__["end_time"] = end_time
            __props__.__dict__["ip_type"] = ip_type
            __props__.__dict__["prio"] = prio
            if proto is None and not opts.urn:
                raise TypeError("Missing required property 'proto'")
            __props__.__dict__["proto"] = proto
            __props__.__dict__["repeat_days"] = repeat_days
            __props__.__dict__["repeat_end_time"] = repeat_end_time
            __props__.__dict__["repeat_start_time"] = repeat_start_time
            __props__.__dict__["repeat_type"] = repeat_type
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            if source_type is None and not opts.urn:
                raise TypeError("Missing required property 'source_type'")
            __props__.__dict__["source_type"] = source_type
            __props__.__dict__["start_time"] = start_time
            __props__.__dict__["status"] = status
            if vpc_firewall_id is None and not opts.urn:
                raise TypeError("Missing required property 'vpc_firewall_id'")
            __props__.__dict__["vpc_firewall_id"] = vpc_firewall_id
            __props__.__dict__["account_id"] = None
            __props__.__dict__["dest_port_group_type"] = None
            __props__.__dict__["dest_port_list_v1s"] = None
            __props__.__dict__["dest_port_lists"] = None
            __props__.__dict__["destination_cidr_list_v1s"] = None
            __props__.__dict__["destination_cidr_lists"] = None
            __props__.__dict__["destination_domain_lists"] = None
            __props__.__dict__["destination_group_type"] = None
            __props__.__dict__["effect_status"] = None
            __props__.__dict__["hit_cnt"] = None
            __props__.__dict__["is_effected"] = None
            __props__.__dict__["rule_id"] = None
            __props__.__dict__["source_cidr_list_v1s"] = None
            __props__.__dict__["source_cidr_lists"] = None
            __props__.__dict__["source_group_type"] = None
            __props__.__dict__["update_time"] = None
            __props__.__dict__["use_count"] = None
            __props__.__dict__["vpc_firewall_name"] = None
        super(VpcFireWallAclRule, __self__).__init__(
            'volcenginecc:fwcenter/vpcFireWallAclRule:VpcFireWallAclRule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: Optional[pulumi.Input[builtins.str]] = None,
            action: Optional[pulumi.Input[builtins.str]] = None,
            description: Optional[pulumi.Input[builtins.str]] = None,
            dest_port: Optional[pulumi.Input[builtins.str]] = None,
            dest_port_group_type: Optional[pulumi.Input[builtins.str]] = None,
            dest_port_list_v1s: Optional[pulumi.Input[Sequence[pulumi.Input[Union['VpcFireWallAclRuleDestPortListV1Args', 'VpcFireWallAclRuleDestPortListV1ArgsDict']]]]] = None,
            dest_port_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
            dest_port_type: Optional[pulumi.Input[builtins.str]] = None,
            destination: Optional[pulumi.Input[builtins.str]] = None,
            destination_cidr_list_v1s: Optional[pulumi.Input[Sequence[pulumi.Input[Union['VpcFireWallAclRuleDestinationCidrListV1Args', 'VpcFireWallAclRuleDestinationCidrListV1ArgsDict']]]]] = None,
            destination_cidr_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
            destination_domain_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
            destination_group_type: Optional[pulumi.Input[builtins.str]] = None,
            destination_type: Optional[pulumi.Input[builtins.str]] = None,
            domain_resolution_mode: Optional[pulumi.Input[builtins.str]] = None,
            effect_status: Optional[pulumi.Input[builtins.int]] = None,
            end_time: Optional[pulumi.Input[builtins.int]] = None,
            hit_cnt: Optional[pulumi.Input[builtins.int]] = None,
            ip_type: Optional[pulumi.Input[builtins.str]] = None,
            is_effected: Optional[pulumi.Input[builtins.bool]] = None,
            prio: Optional[pulumi.Input[builtins.int]] = None,
            proto: Optional[pulumi.Input[builtins.str]] = None,
            repeat_days: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.int]]]] = None,
            repeat_end_time: Optional[pulumi.Input[builtins.str]] = None,
            repeat_start_time: Optional[pulumi.Input[builtins.str]] = None,
            repeat_type: Optional[pulumi.Input[builtins.str]] = None,
            rule_id: Optional[pulumi.Input[builtins.str]] = None,
            source: Optional[pulumi.Input[builtins.str]] = None,
            source_cidr_list_v1s: Optional[pulumi.Input[Sequence[pulumi.Input[Union['VpcFireWallAclRuleSourceCidrListV1Args', 'VpcFireWallAclRuleSourceCidrListV1ArgsDict']]]]] = None,
            source_cidr_lists: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
            source_group_type: Optional[pulumi.Input[builtins.str]] = None,
            source_type: Optional[pulumi.Input[builtins.str]] = None,
            start_time: Optional[pulumi.Input[builtins.int]] = None,
            status: Optional[pulumi.Input[builtins.bool]] = None,
            update_time: Optional[pulumi.Input[builtins.int]] = None,
            use_count: Optional[pulumi.Input[builtins.int]] = None,
            vpc_firewall_id: Optional[pulumi.Input[builtins.str]] = None,
            vpc_firewall_name: Optional[pulumi.Input[builtins.str]] = None) -> 'VpcFireWallAclRule':
        """
        Get an existing VpcFireWallAclRule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] account_id: User unique ID.
        :param pulumi.Input[builtins.str] action: Policy action: accept (allow); deny (block); monitor (observe).
        :param pulumi.Input[builtins.str] description: Policy description, used to explain the purpose and function of the policy.
        :param pulumi.Input[builtins.str] dest_port: Destination port, single port or port range (e.g., 22/22, 100/200). If DestPortType is group, it is a list of port address book UUIDs, separated by commas. Leave blank if protocol is ICMP or ANY.
        :param pulumi.Input[builtins.str] dest_port_group_type: Destination port book type.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] dest_port_lists: Destination port list.
        :param pulumi.Input[builtins.str] dest_port_type: Destination port type: port (single port or port range); group (port address book).
        :param pulumi.Input[builtins.str] destination: Destination address. The value depends on DestinationType: net for destination CIDR address; group for destination address book UUIDs, separated by commas; domain for destination domain name.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] destination_cidr_lists: Destination CIDR list.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] destination_domain_lists: Destination domain name list.
        :param pulumi.Input[builtins.str] destination_group_type: Destination address book type.
        :param pulumi.Input[builtins.str] destination_type: Destination address type: net for subnet (CIDR format); group for address book (UUID format); domain for domain name.
        :param pulumi.Input[builtins.str] domain_resolution_mode: Domain name resolution mode: fqdn for full domain name resolution; dns for dynamic DNS resolution.
        :param pulumi.Input[builtins.int] effect_status: Effectiveness status of the access control policy. 1: not effective; 2: deploying; 3: effective.
        :param pulumi.Input[builtins.int] end_time: Policy activation end time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.int] hit_cnt: Hit count of the access control policy.
        :param pulumi.Input[builtins.str] ip_type: IP version: v4 indicates IPv4; v6 indicates IPv6.
        :param pulumi.Input[builtins.bool] is_effected: Whether the access control policy is effective. true: effective; false: not effective.
        :param pulumi.Input[builtins.int] prio: Policy priority. Lower values indicate higher priority. 0 is the lowest priority, 1 is the highest. When modifying, the minimum value for this parameter is 1.
        :param pulumi.Input[builtins.str] proto: Protocol type: ICMP, TCP, UDP, ANY. Only TCP is supported when the destination address type is domain.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.int]]] repeat_days: Specific dates for repeated activation. Valid only when RepeatType is Weekly (0-6 for Sunday to Saturday) or Monthly (1-31 for each day of the month).
        :param pulumi.Input[builtins.str] repeat_end_time: Recurring daily end time, format: hh:mm. Valid only when RepeatType is Weekly or Monthly.
        :param pulumi.Input[builtins.str] repeat_start_time: Recurring daily start time, format: hh:mm. Valid only when RepeatType is Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.str] repeat_type: Activation repeat type: Permanent always effective; Once single activation; Daily repeat daily; Weekly repeat weekly; Monthly repeat monthly.
        :param pulumi.Input[builtins.str] rule_id: Unique ID of the access control policy.
        :param pulumi.Input[builtins.str] source: Source address. The value depends on SourceType: net for source CIDR address; group for source address book UUIDs, separated by commas.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] source_cidr_lists: Source CIDR list.
        :param pulumi.Input[builtins.str] source_group_type: Source address book type.
        :param pulumi.Input[builtins.str] source_type: Source address type: net for subnet (CIDR format); group for address book (UUID format).
        :param pulumi.Input[builtins.int] start_time: Policy activation start time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        :param pulumi.Input[builtins.bool] status: Policy enable status: true enabled; false disabled.
        :param pulumi.Input[builtins.int] update_time: Last policy update time, Unix timestamp.
        :param pulumi.Input[builtins.int] use_count: Number of policies used.
        :param pulumi.Input[builtins.str] vpc_firewall_id: VPC border firewall instance ID.
        :param pulumi.Input[builtins.str] vpc_firewall_name: VPC border firewall instance name.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _VpcFireWallAclRuleState.__new__(_VpcFireWallAclRuleState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["action"] = action
        __props__.__dict__["description"] = description
        __props__.__dict__["dest_port"] = dest_port
        __props__.__dict__["dest_port_group_type"] = dest_port_group_type
        __props__.__dict__["dest_port_list_v1s"] = dest_port_list_v1s
        __props__.__dict__["dest_port_lists"] = dest_port_lists
        __props__.__dict__["dest_port_type"] = dest_port_type
        __props__.__dict__["destination"] = destination
        __props__.__dict__["destination_cidr_list_v1s"] = destination_cidr_list_v1s
        __props__.__dict__["destination_cidr_lists"] = destination_cidr_lists
        __props__.__dict__["destination_domain_lists"] = destination_domain_lists
        __props__.__dict__["destination_group_type"] = destination_group_type
        __props__.__dict__["destination_type"] = destination_type
        __props__.__dict__["domain_resolution_mode"] = domain_resolution_mode
        __props__.__dict__["effect_status"] = effect_status
        __props__.__dict__["end_time"] = end_time
        __props__.__dict__["hit_cnt"] = hit_cnt
        __props__.__dict__["ip_type"] = ip_type
        __props__.__dict__["is_effected"] = is_effected
        __props__.__dict__["prio"] = prio
        __props__.__dict__["proto"] = proto
        __props__.__dict__["repeat_days"] = repeat_days
        __props__.__dict__["repeat_end_time"] = repeat_end_time
        __props__.__dict__["repeat_start_time"] = repeat_start_time
        __props__.__dict__["repeat_type"] = repeat_type
        __props__.__dict__["rule_id"] = rule_id
        __props__.__dict__["source"] = source
        __props__.__dict__["source_cidr_list_v1s"] = source_cidr_list_v1s
        __props__.__dict__["source_cidr_lists"] = source_cidr_lists
        __props__.__dict__["source_group_type"] = source_group_type
        __props__.__dict__["source_type"] = source_type
        __props__.__dict__["start_time"] = start_time
        __props__.__dict__["status"] = status
        __props__.__dict__["update_time"] = update_time
        __props__.__dict__["use_count"] = use_count
        __props__.__dict__["vpc_firewall_id"] = vpc_firewall_id
        __props__.__dict__["vpc_firewall_name"] = vpc_firewall_name
        return VpcFireWallAclRule(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[builtins.str]:
        """
        User unique ID.
        """
        return pulumi.get(self, "account_id")

    @property
    @pulumi.getter
    def action(self) -> pulumi.Output[builtins.str]:
        """
        Policy action: accept (allow); deny (block); monitor (observe).
        """
        return pulumi.get(self, "action")

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[builtins.str]:
        """
        Policy description, used to explain the purpose and function of the policy.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="destPort")
    def dest_port(self) -> pulumi.Output[builtins.str]:
        """
        Destination port, single port or port range (e.g., 22/22, 100/200). If DestPortType is group, it is a list of port address book UUIDs, separated by commas. Leave blank if protocol is ICMP or ANY.
        """
        return pulumi.get(self, "dest_port")

    @property
    @pulumi.getter(name="destPortGroupType")
    def dest_port_group_type(self) -> pulumi.Output[builtins.str]:
        """
        Destination port book type.
        """
        return pulumi.get(self, "dest_port_group_type")

    @property
    @pulumi.getter(name="destPortListV1s")
    def dest_port_list_v1s(self) -> pulumi.Output[Sequence['outputs.VpcFireWallAclRuleDestPortListV1']]:
        return pulumi.get(self, "dest_port_list_v1s")

    @property
    @pulumi.getter(name="destPortLists")
    def dest_port_lists(self) -> pulumi.Output[Sequence[builtins.str]]:
        """
        Destination port list.
        """
        return pulumi.get(self, "dest_port_lists")

    @property
    @pulumi.getter(name="destPortType")
    def dest_port_type(self) -> pulumi.Output[builtins.str]:
        """
        Destination port type: port (single port or port range); group (port address book).
        """
        return pulumi.get(self, "dest_port_type")

    @property
    @pulumi.getter
    def destination(self) -> pulumi.Output[builtins.str]:
        """
        Destination address. The value depends on DestinationType: net for destination CIDR address; group for destination address book UUIDs, separated by commas; domain for destination domain name.
        """
        return pulumi.get(self, "destination")

    @property
    @pulumi.getter(name="destinationCidrListV1s")
    def destination_cidr_list_v1s(self) -> pulumi.Output[Sequence['outputs.VpcFireWallAclRuleDestinationCidrListV1']]:
        return pulumi.get(self, "destination_cidr_list_v1s")

    @property
    @pulumi.getter(name="destinationCidrLists")
    def destination_cidr_lists(self) -> pulumi.Output[Sequence[builtins.str]]:
        """
        Destination CIDR list.
        """
        return pulumi.get(self, "destination_cidr_lists")

    @property
    @pulumi.getter(name="destinationDomainLists")
    def destination_domain_lists(self) -> pulumi.Output[Sequence[builtins.str]]:
        """
        Destination domain name list.
        """
        return pulumi.get(self, "destination_domain_lists")

    @property
    @pulumi.getter(name="destinationGroupType")
    def destination_group_type(self) -> pulumi.Output[builtins.str]:
        """
        Destination address book type.
        """
        return pulumi.get(self, "destination_group_type")

    @property
    @pulumi.getter(name="destinationType")
    def destination_type(self) -> pulumi.Output[builtins.str]:
        """
        Destination address type: net for subnet (CIDR format); group for address book (UUID format); domain for domain name.
        """
        return pulumi.get(self, "destination_type")

    @property
    @pulumi.getter(name="domainResolutionMode")
    def domain_resolution_mode(self) -> pulumi.Output[builtins.str]:
        """
        Domain name resolution mode: fqdn for full domain name resolution; dns for dynamic DNS resolution.
        """
        return pulumi.get(self, "domain_resolution_mode")

    @property
    @pulumi.getter(name="effectStatus")
    def effect_status(self) -> pulumi.Output[builtins.int]:
        """
        Effectiveness status of the access control policy. 1: not effective; 2: deploying; 3: effective.
        """
        return pulumi.get(self, "effect_status")

    @property
    @pulumi.getter(name="endTime")
    def end_time(self) -> pulumi.Output[builtins.int]:
        """
        Policy activation end time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "end_time")

    @property
    @pulumi.getter(name="hitCnt")
    def hit_cnt(self) -> pulumi.Output[builtins.int]:
        """
        Hit count of the access control policy.
        """
        return pulumi.get(self, "hit_cnt")

    @property
    @pulumi.getter(name="ipType")
    def ip_type(self) -> pulumi.Output[builtins.str]:
        """
        IP version: v4 indicates IPv4; v6 indicates IPv6.
        """
        return pulumi.get(self, "ip_type")

    @property
    @pulumi.getter(name="isEffected")
    def is_effected(self) -> pulumi.Output[builtins.bool]:
        """
        Whether the access control policy is effective. true: effective; false: not effective.
        """
        return pulumi.get(self, "is_effected")

    @property
    @pulumi.getter
    def prio(self) -> pulumi.Output[builtins.int]:
        """
        Policy priority. Lower values indicate higher priority. 0 is the lowest priority, 1 is the highest. When modifying, the minimum value for this parameter is 1.
        """
        return pulumi.get(self, "prio")

    @property
    @pulumi.getter
    def proto(self) -> pulumi.Output[builtins.str]:
        """
        Protocol type: ICMP, TCP, UDP, ANY. Only TCP is supported when the destination address type is domain.
        """
        return pulumi.get(self, "proto")

    @property
    @pulumi.getter(name="repeatDays")
    def repeat_days(self) -> pulumi.Output[Sequence[builtins.int]]:
        """
        Specific dates for repeated activation. Valid only when RepeatType is Weekly (0-6 for Sunday to Saturday) or Monthly (1-31 for each day of the month).
        """
        return pulumi.get(self, "repeat_days")

    @property
    @pulumi.getter(name="repeatEndTime")
    def repeat_end_time(self) -> pulumi.Output[builtins.str]:
        """
        Recurring daily end time, format: hh:mm. Valid only when RepeatType is Weekly or Monthly.
        """
        return pulumi.get(self, "repeat_end_time")

    @property
    @pulumi.getter(name="repeatStartTime")
    def repeat_start_time(self) -> pulumi.Output[builtins.str]:
        """
        Recurring daily start time, format: hh:mm. Valid only when RepeatType is Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "repeat_start_time")

    @property
    @pulumi.getter(name="repeatType")
    def repeat_type(self) -> pulumi.Output[builtins.str]:
        """
        Activation repeat type: Permanent always effective; Once single activation; Daily repeat daily; Weekly repeat weekly; Monthly repeat monthly.
        """
        return pulumi.get(self, "repeat_type")

    @property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> pulumi.Output[builtins.str]:
        """
        Unique ID of the access control policy.
        """
        return pulumi.get(self, "rule_id")

    @property
    @pulumi.getter
    def source(self) -> pulumi.Output[builtins.str]:
        """
        Source address. The value depends on SourceType: net for source CIDR address; group for source address book UUIDs, separated by commas.
        """
        return pulumi.get(self, "source")

    @property
    @pulumi.getter(name="sourceCidrListV1s")
    def source_cidr_list_v1s(self) -> pulumi.Output[Sequence['outputs.VpcFireWallAclRuleSourceCidrListV1']]:
        return pulumi.get(self, "source_cidr_list_v1s")

    @property
    @pulumi.getter(name="sourceCidrLists")
    def source_cidr_lists(self) -> pulumi.Output[Sequence[builtins.str]]:
        """
        Source CIDR list.
        """
        return pulumi.get(self, "source_cidr_lists")

    @property
    @pulumi.getter(name="sourceGroupType")
    def source_group_type(self) -> pulumi.Output[builtins.str]:
        """
        Source address book type.
        """
        return pulumi.get(self, "source_group_type")

    @property
    @pulumi.getter(name="sourceType")
    def source_type(self) -> pulumi.Output[builtins.str]:
        """
        Source address type: net for subnet (CIDR format); group for address book (UUID format).
        """
        return pulumi.get(self, "source_type")

    @property
    @pulumi.getter(name="startTime")
    def start_time(self) -> pulumi.Output[builtins.int]:
        """
        Policy activation start time, Unix timestamp. Fill in only when RepeatType is Once, Daily, Weekly, or Monthly.
        """
        return pulumi.get(self, "start_time")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[builtins.bool]:
        """
        Policy enable status: true enabled; false disabled.
        """
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="updateTime")
    def update_time(self) -> pulumi.Output[builtins.int]:
        """
        Last policy update time, Unix timestamp.
        """
        return pulumi.get(self, "update_time")

    @property
    @pulumi.getter(name="useCount")
    def use_count(self) -> pulumi.Output[builtins.int]:
        """
        Number of policies used.
        """
        return pulumi.get(self, "use_count")

    @property
    @pulumi.getter(name="vpcFirewallId")
    def vpc_firewall_id(self) -> pulumi.Output[builtins.str]:
        """
        VPC border firewall instance ID.
        """
        return pulumi.get(self, "vpc_firewall_id")

    @property
    @pulumi.getter(name="vpcFirewallName")
    def vpc_firewall_name(self) -> pulumi.Output[builtins.str]:
        """
        VPC border firewall instance name.
        """
        return pulumi.get(self, "vpc_firewall_name")

