// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.vefaas.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTimerResult {
    /**
     * @return Timer trigger creation time
     * 
     */
    private String creationTime;
    /**
     * @return Timer trigger time, formatted as a crontab expression
     * 
     */
    private String crontab;
    /**
     * @return Timer trigger remarks
     * 
     */
    private String description;
    /**
     * @return Allow timer trigger concurrency; true means concurrency is allowed
     * 
     */
    private Boolean enableConcurrency;
    /**
     * @return Timer trigger enabled; true means enabled
     * 
     */
    private Boolean enabled;
    /**
     * @return Function ID
     * 
     */
    private String functionId;
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    private String id;
    /**
     * @return Timer trigger update time
     * 
     */
    private String lastUpdateTime;
    /**
     * @return Timer trigger name
     * 
     */
    private String name;
    /**
     * @return Payload sent by timer trigger, that is, the trigger message
     * 
     */
    private String payload;
    /**
     * @return Timer trigger retry count
     * 
     */
    private Integer retries;
    /**
     * @return Timer trigger ID
     * 
     */
    private String timerId;

    private GetTimerResult() {}
    /**
     * @return Timer trigger creation time
     * 
     */
    public String creationTime() {
        return this.creationTime;
    }
    /**
     * @return Timer trigger time, formatted as a crontab expression
     * 
     */
    public String crontab() {
        return this.crontab;
    }
    /**
     * @return Timer trigger remarks
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Allow timer trigger concurrency; true means concurrency is allowed
     * 
     */
    public Boolean enableConcurrency() {
        return this.enableConcurrency;
    }
    /**
     * @return Timer trigger enabled; true means enabled
     * 
     */
    public Boolean enabled() {
        return this.enabled;
    }
    /**
     * @return Function ID
     * 
     */
    public String functionId() {
        return this.functionId;
    }
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Timer trigger update time
     * 
     */
    public String lastUpdateTime() {
        return this.lastUpdateTime;
    }
    /**
     * @return Timer trigger name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Payload sent by timer trigger, that is, the trigger message
     * 
     */
    public String payload() {
        return this.payload;
    }
    /**
     * @return Timer trigger retry count
     * 
     */
    public Integer retries() {
        return this.retries;
    }
    /**
     * @return Timer trigger ID
     * 
     */
    public String timerId() {
        return this.timerId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTimerResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String creationTime;
        private String crontab;
        private String description;
        private Boolean enableConcurrency;
        private Boolean enabled;
        private String functionId;
        private String id;
        private String lastUpdateTime;
        private String name;
        private String payload;
        private Integer retries;
        private String timerId;
        public Builder() {}
        public Builder(GetTimerResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.creationTime = defaults.creationTime;
    	      this.crontab = defaults.crontab;
    	      this.description = defaults.description;
    	      this.enableConcurrency = defaults.enableConcurrency;
    	      this.enabled = defaults.enabled;
    	      this.functionId = defaults.functionId;
    	      this.id = defaults.id;
    	      this.lastUpdateTime = defaults.lastUpdateTime;
    	      this.name = defaults.name;
    	      this.payload = defaults.payload;
    	      this.retries = defaults.retries;
    	      this.timerId = defaults.timerId;
        }

        @CustomType.Setter
        public Builder creationTime(String creationTime) {
            if (creationTime == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "creationTime");
            }
            this.creationTime = creationTime;
            return this;
        }
        @CustomType.Setter
        public Builder crontab(String crontab) {
            if (crontab == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "crontab");
            }
            this.crontab = crontab;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder enableConcurrency(Boolean enableConcurrency) {
            if (enableConcurrency == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "enableConcurrency");
            }
            this.enableConcurrency = enableConcurrency;
            return this;
        }
        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder functionId(String functionId) {
            if (functionId == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "functionId");
            }
            this.functionId = functionId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lastUpdateTime(String lastUpdateTime) {
            if (lastUpdateTime == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "lastUpdateTime");
            }
            this.lastUpdateTime = lastUpdateTime;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder payload(String payload) {
            if (payload == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "payload");
            }
            this.payload = payload;
            return this;
        }
        @CustomType.Setter
        public Builder retries(Integer retries) {
            if (retries == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "retries");
            }
            this.retries = retries;
            return this;
        }
        @CustomType.Setter
        public Builder timerId(String timerId) {
            if (timerId == null) {
              throw new MissingRequiredPropertyException("GetTimerResult", "timerId");
            }
            this.timerId = timerId;
            return this;
        }
        public GetTimerResult build() {
            final var _resultValue = new GetTimerResult();
            _resultValue.creationTime = creationTime;
            _resultValue.crontab = crontab;
            _resultValue.description = description;
            _resultValue.enableConcurrency = enableConcurrency;
            _resultValue.enabled = enabled;
            _resultValue.functionId = functionId;
            _resultValue.id = id;
            _resultValue.lastUpdateTime = lastUpdateTime;
            _resultValue.name = name;
            _resultValue.payload = payload;
            _resultValue.retries = retries;
            _resultValue.timerId = timerId;
            return _resultValue;
        }
    }
}
