// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dns

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcenginecc/sdk/go/volcenginecc/internal"
)

// DNS record resource, used to create, query, update, delete, and list a single DNS record under a specified domain name.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/volcengine/pulumi-volcenginecc/sdk/go/volcenginecc/dns"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := dns.NewRecord(ctx, "DNSRecordDemo", &dns.RecordArgs{
//				Zid:    pulumi.String("xxxxxx"),
//				Host:   pulumi.String("test"),
//				Type:   pulumi.String("CNAME"),
//				Value:  pulumi.String("test1.example1.com"),
//				Line:   pulumi.String("default"),
//				Remark: pulumi.String("test"),
//				Ttl:    pulumi.Int(601),
//				Weight: pulumi.Int(2),
//				Enable: pulumi.Bool(false),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import volcenginecc:dns/record:Record example "zid|record_id"
// ```
type Record struct {
	pulumi.CustomResourceState

	// Creation time of the DNS record.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Whether the DNS record is enabled; if disabled, the record is inactive.
	Enable pulumi.BoolOutput `pulumi:"enable"`
	// Host name included in the DNS record, using FQDN (Fully Qualified Domain Name) format; this field is deprecated.
	Fqdn pulumi.StringOutput `pulumi:"fqdn"`
	// Host record, the prefix of the subdomain; `@` represents the root domain itself.
	Host pulumi.StringOutput `pulumi:"host"`
	// Line code corresponding to the DNS record, such as `default`.
	Line pulumi.StringOutput `pulumi:"line"`
	// List of account IDs that recently operated on this DNS record.
	Operators pulumi.StringArrayOutput `pulumi:"operators"`
	// Host name included in the DNS record, using PQDN (Partially Qualified Domain Name) format.
	Pqdn pulumi.StringOutput `pulumi:"pqdn"`
	// Unique ID of the DNS record.
	RecordId pulumi.StringOutput `pulumi:"recordId"`
	// ID of the record set containing the DNS record; returned only for A, AAAA, and CNAME types.
	RecordSetId pulumi.StringOutput `pulumi:"recordSetId"`
	// Remarks for the DNS record, supports UTF-8 encoding and up to 16 characters.
	Remark pulumi.StringOutput `pulumi:"remark"`
	// Tag information for the DNS record; if it contains `GTMLock`, the record is associated with a GTM instance.
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// Expiration time of the DNS record, in seconds.
	Ttl pulumi.IntOutput `pulumi:"ttl"`
	// Record type, such as `A`, `AAAA`, `CNAME`, `NS`, `MX`, `SRV`, `TXT`.
	Type pulumi.StringOutput `pulumi:"type"`
	// Last updated time of the DNS record.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Record value of the DNS record.
	Value pulumi.StringOutput `pulumi:"value"`
	// Weight of the DNS record, effective only when load balancing is enabled for the record set.
	Weight pulumi.IntOutput `pulumi:"weight"`
	// Domain name ID, can be obtained via interfaces such as `ListZones`.
	Zid pulumi.StringOutput `pulumi:"zid"`
}

// NewRecord registers a new resource with the given unique name, arguments, and options.
func NewRecord(ctx *pulumi.Context,
	name string, args *RecordArgs, opts ...pulumi.ResourceOption) (*Record, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Host == nil {
		return nil, errors.New("invalid value for required argument 'Host'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	if args.Zid == nil {
		return nil, errors.New("invalid value for required argument 'Zid'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Record
	err := ctx.RegisterResource("volcenginecc:dns/record:Record", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRecord gets an existing Record resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRecord(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RecordState, opts ...pulumi.ResourceOption) (*Record, error) {
	var resource Record
	err := ctx.ReadResource("volcenginecc:dns/record:Record", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Record resources.
type recordState struct {
	// Creation time of the DNS record.
	CreatedAt *string `pulumi:"createdAt"`
	// Whether the DNS record is enabled; if disabled, the record is inactive.
	Enable *bool `pulumi:"enable"`
	// Host name included in the DNS record, using FQDN (Fully Qualified Domain Name) format; this field is deprecated.
	Fqdn *string `pulumi:"fqdn"`
	// Host record, the prefix of the subdomain; `@` represents the root domain itself.
	Host *string `pulumi:"host"`
	// Line code corresponding to the DNS record, such as `default`.
	Line *string `pulumi:"line"`
	// List of account IDs that recently operated on this DNS record.
	Operators []string `pulumi:"operators"`
	// Host name included in the DNS record, using PQDN (Partially Qualified Domain Name) format.
	Pqdn *string `pulumi:"pqdn"`
	// Unique ID of the DNS record.
	RecordId *string `pulumi:"recordId"`
	// ID of the record set containing the DNS record; returned only for A, AAAA, and CNAME types.
	RecordSetId *string `pulumi:"recordSetId"`
	// Remarks for the DNS record, supports UTF-8 encoding and up to 16 characters.
	Remark *string `pulumi:"remark"`
	// Tag information for the DNS record; if it contains `GTMLock`, the record is associated with a GTM instance.
	Tags []string `pulumi:"tags"`
	// Expiration time of the DNS record, in seconds.
	Ttl *int `pulumi:"ttl"`
	// Record type, such as `A`, `AAAA`, `CNAME`, `NS`, `MX`, `SRV`, `TXT`.
	Type *string `pulumi:"type"`
	// Last updated time of the DNS record.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Record value of the DNS record.
	Value *string `pulumi:"value"`
	// Weight of the DNS record, effective only when load balancing is enabled for the record set.
	Weight *int `pulumi:"weight"`
	// Domain name ID, can be obtained via interfaces such as `ListZones`.
	Zid *string `pulumi:"zid"`
}

type RecordState struct {
	// Creation time of the DNS record.
	CreatedAt pulumi.StringPtrInput
	// Whether the DNS record is enabled; if disabled, the record is inactive.
	Enable pulumi.BoolPtrInput
	// Host name included in the DNS record, using FQDN (Fully Qualified Domain Name) format; this field is deprecated.
	Fqdn pulumi.StringPtrInput
	// Host record, the prefix of the subdomain; `@` represents the root domain itself.
	Host pulumi.StringPtrInput
	// Line code corresponding to the DNS record, such as `default`.
	Line pulumi.StringPtrInput
	// List of account IDs that recently operated on this DNS record.
	Operators pulumi.StringArrayInput
	// Host name included in the DNS record, using PQDN (Partially Qualified Domain Name) format.
	Pqdn pulumi.StringPtrInput
	// Unique ID of the DNS record.
	RecordId pulumi.StringPtrInput
	// ID of the record set containing the DNS record; returned only for A, AAAA, and CNAME types.
	RecordSetId pulumi.StringPtrInput
	// Remarks for the DNS record, supports UTF-8 encoding and up to 16 characters.
	Remark pulumi.StringPtrInput
	// Tag information for the DNS record; if it contains `GTMLock`, the record is associated with a GTM instance.
	Tags pulumi.StringArrayInput
	// Expiration time of the DNS record, in seconds.
	Ttl pulumi.IntPtrInput
	// Record type, such as `A`, `AAAA`, `CNAME`, `NS`, `MX`, `SRV`, `TXT`.
	Type pulumi.StringPtrInput
	// Last updated time of the DNS record.
	UpdatedAt pulumi.StringPtrInput
	// Record value of the DNS record.
	Value pulumi.StringPtrInput
	// Weight of the DNS record, effective only when load balancing is enabled for the record set.
	Weight pulumi.IntPtrInput
	// Domain name ID, can be obtained via interfaces such as `ListZones`.
	Zid pulumi.StringPtrInput
}

func (RecordState) ElementType() reflect.Type {
	return reflect.TypeOf((*recordState)(nil)).Elem()
}

type recordArgs struct {
	// Whether the DNS record is enabled; if disabled, the record is inactive.
	Enable *bool `pulumi:"enable"`
	// Host record, the prefix of the subdomain; `@` represents the root domain itself.
	Host string `pulumi:"host"`
	// Line code corresponding to the DNS record, such as `default`.
	Line *string `pulumi:"line"`
	// Remarks for the DNS record, supports UTF-8 encoding and up to 16 characters.
	Remark *string `pulumi:"remark"`
	// Expiration time of the DNS record, in seconds.
	Ttl *int `pulumi:"ttl"`
	// Record type, such as `A`, `AAAA`, `CNAME`, `NS`, `MX`, `SRV`, `TXT`.
	Type string `pulumi:"type"`
	// Record value of the DNS record.
	Value string `pulumi:"value"`
	// Weight of the DNS record, effective only when load balancing is enabled for the record set.
	Weight *int `pulumi:"weight"`
	// Domain name ID, can be obtained via interfaces such as `ListZones`.
	Zid string `pulumi:"zid"`
}

// The set of arguments for constructing a Record resource.
type RecordArgs struct {
	// Whether the DNS record is enabled; if disabled, the record is inactive.
	Enable pulumi.BoolPtrInput
	// Host record, the prefix of the subdomain; `@` represents the root domain itself.
	Host pulumi.StringInput
	// Line code corresponding to the DNS record, such as `default`.
	Line pulumi.StringPtrInput
	// Remarks for the DNS record, supports UTF-8 encoding and up to 16 characters.
	Remark pulumi.StringPtrInput
	// Expiration time of the DNS record, in seconds.
	Ttl pulumi.IntPtrInput
	// Record type, such as `A`, `AAAA`, `CNAME`, `NS`, `MX`, `SRV`, `TXT`.
	Type pulumi.StringInput
	// Record value of the DNS record.
	Value pulumi.StringInput
	// Weight of the DNS record, effective only when load balancing is enabled for the record set.
	Weight pulumi.IntPtrInput
	// Domain name ID, can be obtained via interfaces such as `ListZones`.
	Zid pulumi.StringInput
}

func (RecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*recordArgs)(nil)).Elem()
}

type RecordInput interface {
	pulumi.Input

	ToRecordOutput() RecordOutput
	ToRecordOutputWithContext(ctx context.Context) RecordOutput
}

func (*Record) ElementType() reflect.Type {
	return reflect.TypeOf((**Record)(nil)).Elem()
}

func (i *Record) ToRecordOutput() RecordOutput {
	return i.ToRecordOutputWithContext(context.Background())
}

func (i *Record) ToRecordOutputWithContext(ctx context.Context) RecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecordOutput)
}

// RecordArrayInput is an input type that accepts RecordArray and RecordArrayOutput values.
// You can construct a concrete instance of `RecordArrayInput` via:
//
//	RecordArray{ RecordArgs{...} }
type RecordArrayInput interface {
	pulumi.Input

	ToRecordArrayOutput() RecordArrayOutput
	ToRecordArrayOutputWithContext(context.Context) RecordArrayOutput
}

type RecordArray []RecordInput

func (RecordArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Record)(nil)).Elem()
}

func (i RecordArray) ToRecordArrayOutput() RecordArrayOutput {
	return i.ToRecordArrayOutputWithContext(context.Background())
}

func (i RecordArray) ToRecordArrayOutputWithContext(ctx context.Context) RecordArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecordArrayOutput)
}

// RecordMapInput is an input type that accepts RecordMap and RecordMapOutput values.
// You can construct a concrete instance of `RecordMapInput` via:
//
//	RecordMap{ "key": RecordArgs{...} }
type RecordMapInput interface {
	pulumi.Input

	ToRecordMapOutput() RecordMapOutput
	ToRecordMapOutputWithContext(context.Context) RecordMapOutput
}

type RecordMap map[string]RecordInput

func (RecordMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Record)(nil)).Elem()
}

func (i RecordMap) ToRecordMapOutput() RecordMapOutput {
	return i.ToRecordMapOutputWithContext(context.Background())
}

func (i RecordMap) ToRecordMapOutputWithContext(ctx context.Context) RecordMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecordMapOutput)
}

type RecordOutput struct{ *pulumi.OutputState }

func (RecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Record)(nil)).Elem()
}

func (o RecordOutput) ToRecordOutput() RecordOutput {
	return o
}

func (o RecordOutput) ToRecordOutputWithContext(ctx context.Context) RecordOutput {
	return o
}

// Creation time of the DNS record.
func (o RecordOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Whether the DNS record is enabled; if disabled, the record is inactive.
func (o RecordOutput) Enable() pulumi.BoolOutput {
	return o.ApplyT(func(v *Record) pulumi.BoolOutput { return v.Enable }).(pulumi.BoolOutput)
}

// Host name included in the DNS record, using FQDN (Fully Qualified Domain Name) format; this field is deprecated.
func (o RecordOutput) Fqdn() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Fqdn }).(pulumi.StringOutput)
}

// Host record, the prefix of the subdomain; `@` represents the root domain itself.
func (o RecordOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Host }).(pulumi.StringOutput)
}

// Line code corresponding to the DNS record, such as `default`.
func (o RecordOutput) Line() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Line }).(pulumi.StringOutput)
}

// List of account IDs that recently operated on this DNS record.
func (o RecordOutput) Operators() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Record) pulumi.StringArrayOutput { return v.Operators }).(pulumi.StringArrayOutput)
}

// Host name included in the DNS record, using PQDN (Partially Qualified Domain Name) format.
func (o RecordOutput) Pqdn() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Pqdn }).(pulumi.StringOutput)
}

// Unique ID of the DNS record.
func (o RecordOutput) RecordId() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.RecordId }).(pulumi.StringOutput)
}

// ID of the record set containing the DNS record; returned only for A, AAAA, and CNAME types.
func (o RecordOutput) RecordSetId() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.RecordSetId }).(pulumi.StringOutput)
}

// Remarks for the DNS record, supports UTF-8 encoding and up to 16 characters.
func (o RecordOutput) Remark() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Remark }).(pulumi.StringOutput)
}

// Tag information for the DNS record; if it contains `GTMLock`, the record is associated with a GTM instance.
func (o RecordOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Record) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

// Expiration time of the DNS record, in seconds.
func (o RecordOutput) Ttl() pulumi.IntOutput {
	return o.ApplyT(func(v *Record) pulumi.IntOutput { return v.Ttl }).(pulumi.IntOutput)
}

// Record type, such as `A`, `AAAA`, `CNAME`, `NS`, `MX`, `SRV`, `TXT`.
func (o RecordOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Last updated time of the DNS record.
func (o RecordOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Record value of the DNS record.
func (o RecordOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

// Weight of the DNS record, effective only when load balancing is enabled for the record set.
func (o RecordOutput) Weight() pulumi.IntOutput {
	return o.ApplyT(func(v *Record) pulumi.IntOutput { return v.Weight }).(pulumi.IntOutput)
}

// Domain name ID, can be obtained via interfaces such as `ListZones`.
func (o RecordOutput) Zid() pulumi.StringOutput {
	return o.ApplyT(func(v *Record) pulumi.StringOutput { return v.Zid }).(pulumi.StringOutput)
}

type RecordArrayOutput struct{ *pulumi.OutputState }

func (RecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Record)(nil)).Elem()
}

func (o RecordArrayOutput) ToRecordArrayOutput() RecordArrayOutput {
	return o
}

func (o RecordArrayOutput) ToRecordArrayOutputWithContext(ctx context.Context) RecordArrayOutput {
	return o
}

func (o RecordArrayOutput) Index(i pulumi.IntInput) RecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Record {
		return vs[0].([]*Record)[vs[1].(int)]
	}).(RecordOutput)
}

type RecordMapOutput struct{ *pulumi.OutputState }

func (RecordMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Record)(nil)).Elem()
}

func (o RecordMapOutput) ToRecordMapOutput() RecordMapOutput {
	return o
}

func (o RecordMapOutput) ToRecordMapOutputWithContext(ctx context.Context) RecordMapOutput {
	return o
}

func (o RecordMapOutput) MapIndex(k pulumi.StringInput) RecordOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Record {
		return vs[0].(map[string]*Record)[vs[1].(string)]
	}).(RecordOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RecordInput)(nil)).Elem(), &Record{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecordArrayInput)(nil)).Elem(), RecordArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecordMapInput)(nil)).Elem(), RecordMap{})
	pulumi.RegisterOutputType(RecordOutput{})
	pulumi.RegisterOutputType(RecordArrayOutput{})
	pulumi.RegisterOutputType(RecordMapOutput{})
}
