// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.ecs.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LaunchTemplateVersionNetworkInterfaceArgs extends com.pulumi.resources.ResourceArgs {

    public static final LaunchTemplateVersionNetworkInterfaceArgs Empty = new LaunchTemplateVersionNetworkInterfaceArgs();

    /**
     * 网卡关联的安全组ID。
     * 
     */
    @Import(name="securityGroupIds")
    private @Nullable Output<List<String>> securityGroupIds;

    /**
     * @return 网卡关联的安全组ID。
     * 
     */
    public Optional<Output<List<String>>> securityGroupIds() {
        return Optional.ofNullable(this.securityGroupIds);
    }

    /**
     * 实例的私有网络子网ID。
     * 
     */
    @Import(name="subnetId")
    private @Nullable Output<String> subnetId;

    /**
     * @return 实例的私有网络子网ID。
     * 
     */
    public Optional<Output<String>> subnetId() {
        return Optional.ofNullable(this.subnetId);
    }

    private LaunchTemplateVersionNetworkInterfaceArgs() {}

    private LaunchTemplateVersionNetworkInterfaceArgs(LaunchTemplateVersionNetworkInterfaceArgs $) {
        this.securityGroupIds = $.securityGroupIds;
        this.subnetId = $.subnetId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LaunchTemplateVersionNetworkInterfaceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LaunchTemplateVersionNetworkInterfaceArgs $;

        public Builder() {
            $ = new LaunchTemplateVersionNetworkInterfaceArgs();
        }

        public Builder(LaunchTemplateVersionNetworkInterfaceArgs defaults) {
            $ = new LaunchTemplateVersionNetworkInterfaceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param securityGroupIds 网卡关联的安全组ID。
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(@Nullable Output<List<String>> securityGroupIds) {
            $.securityGroupIds = securityGroupIds;
            return this;
        }

        /**
         * @param securityGroupIds 网卡关联的安全组ID。
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(List<String> securityGroupIds) {
            return securityGroupIds(Output.of(securityGroupIds));
        }

        /**
         * @param securityGroupIds 网卡关联的安全组ID。
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(String... securityGroupIds) {
            return securityGroupIds(List.of(securityGroupIds));
        }

        /**
         * @param subnetId 实例的私有网络子网ID。
         * 
         * @return builder
         * 
         */
        public Builder subnetId(@Nullable Output<String> subnetId) {
            $.subnetId = subnetId;
            return this;
        }

        /**
         * @param subnetId 实例的私有网络子网ID。
         * 
         * @return builder
         * 
         */
        public Builder subnetId(String subnetId) {
            return subnetId(Output.of(subnetId));
        }

        public LaunchTemplateVersionNetworkInterfaceArgs build() {
            return $;
        }
    }

}
