// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.veenedge.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VeenCustomDataArgs extends com.pulumi.resources.ResourceArgs {

    public static final VeenCustomDataArgs Empty = new VeenCustomDataArgs();

    /**
     * Original user data content. When IsBase64 is true, the data should be Base64 encoded.
     * 
     */
    @Import(name="data")
    private @Nullable Output<String> data;

    /**
     * @return Original user data content. When IsBase64 is true, the data should be Base64 encoded.
     * 
     */
    public Optional<Output<String>> data() {
        return Optional.ofNullable(this.data);
    }

    /**
     * Whether the data uses Base64 encoding
     * 
     */
    @Import(name="isBase64")
    private @Nullable Output<Boolean> isBase64;

    /**
     * @return Whether the data uses Base64 encoding
     * 
     */
    public Optional<Output<Boolean>> isBase64() {
        return Optional.ofNullable(this.isBase64);
    }

    private VeenCustomDataArgs() {}

    private VeenCustomDataArgs(VeenCustomDataArgs $) {
        this.data = $.data;
        this.isBase64 = $.isBase64;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VeenCustomDataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VeenCustomDataArgs $;

        public Builder() {
            $ = new VeenCustomDataArgs();
        }

        public Builder(VeenCustomDataArgs defaults) {
            $ = new VeenCustomDataArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param data Original user data content. When IsBase64 is true, the data should be Base64 encoded.
         * 
         * @return builder
         * 
         */
        public Builder data(@Nullable Output<String> data) {
            $.data = data;
            return this;
        }

        /**
         * @param data Original user data content. When IsBase64 is true, the data should be Base64 encoded.
         * 
         * @return builder
         * 
         */
        public Builder data(String data) {
            return data(Output.of(data));
        }

        /**
         * @param isBase64 Whether the data uses Base64 encoding
         * 
         * @return builder
         * 
         */
        public Builder isBase64(@Nullable Output<Boolean> isBase64) {
            $.isBase64 = isBase64;
            return this;
        }

        /**
         * @param isBase64 Whether the data uses Base64 encoding
         * 
         * @return builder
         * 
         */
        public Builder isBase64(Boolean isBase64) {
            return isBase64(Output.of(isBase64));
        }

        public VeenCustomDataArgs build() {
            return $;
        }
    }

}
