// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Vke.Outputs
{

    [OutputType]
    public sealed class GetDefaultNodePoolKubernetesConfigKubeletConfigResult
    {
        /// <summary>
        /// Configure kubelet's CpuManagerPolicy. Includes none and static strategies
        /// </summary>
        public readonly string CpuManagerPolicy;
        /// <summary>
        /// Feature gate.
        /// </summary>
        public readonly Outputs.GetDefaultNodePoolKubernetesConfigKubeletConfigFeatureGatesResult FeatureGates;
        /// <summary>
        /// Maximum number of burst requests sent to the API server per second. Does not include events and node heartbeat APIs, whose rate limits are controlled by a different set of flags.
        /// </summary>
        public readonly int KubeApiBurst;
        /// <summary>
        /// Queries per second (QPS) for communication with apiserver. Does not include event and node heartbeat APIs; their rate limits are controlled by a different set of flags
        /// </summary>
        public readonly int KubeApiQps;
        /// <summary>
        /// Resources reserved for Kubernetes system components on the node. By default, half of the default value in the node reserved resource policy is reserved
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDefaultNodePoolKubernetesConfigKubeletConfigKubeReservedResult> KubeReserveds;
        /// <summary>
        /// Configure the maximum number of Pods supported by kubelet
        /// </summary>
        public readonly int MaxPods;
        /// <summary>
        /// Set the maximum number of burst image pulls. Temporarily allow the number of image pulls specified by this parameter, provided it does not exceed the RegistryPullQps setting
        /// </summary>
        public readonly int RegistryBurst;
        /// <summary>
        /// Can be used to limit the QPS cap for the image repository
        /// </summary>
        public readonly int RegistryPullQps;
        /// <summary>
        /// Pull images one by one
        /// </summary>
        public readonly bool SerializeImagePulls;
        /// <summary>
        /// Resources reserved for the operating system on the node. By default, resources are reserved at half the default value specified in the node reserved resource policy.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDefaultNodePoolKubernetesConfigKubeletConfigSystemReservedResult> SystemReserveds;
        /// <summary>
        /// Topology management policy. Values: none: (default) topology management policy disabled. restricted: kubelet only accepts Pods that achieve optimal NUMA (Non-Uniform Memory Access) on requested resources. best-effort: kubelet prioritizes Pods that achieve NUMA on CPU and device resources. single-numa-node: kubelet only allows Pods that achieve NUMA on CPU and device resources within the same node.
        /// </summary>
        public readonly string TopologyManagerPolicy;
        /// <summary>
        /// Resource granularity for topology management strategy. Values: container: resource alignment at container level. pod: resource alignment at Pod level
        /// </summary>
        public readonly string TopologyManagerScope;

        [OutputConstructor]
        private GetDefaultNodePoolKubernetesConfigKubeletConfigResult(
            string cpuManagerPolicy,

            Outputs.GetDefaultNodePoolKubernetesConfigKubeletConfigFeatureGatesResult featureGates,

            int kubeApiBurst,

            int kubeApiQps,

            ImmutableArray<Outputs.GetDefaultNodePoolKubernetesConfigKubeletConfigKubeReservedResult> kubeReserveds,

            int maxPods,

            int registryBurst,

            int registryPullQps,

            bool serializeImagePulls,

            ImmutableArray<Outputs.GetDefaultNodePoolKubernetesConfigKubeletConfigSystemReservedResult> systemReserveds,

            string topologyManagerPolicy,

            string topologyManagerScope)
        {
            CpuManagerPolicy = cpuManagerPolicy;
            FeatureGates = featureGates;
            KubeApiBurst = kubeApiBurst;
            KubeApiQps = kubeApiQps;
            KubeReserveds = kubeReserveds;
            MaxPods = maxPods;
            RegistryBurst = registryBurst;
            RegistryPullQps = registryPullQps;
            SerializeImagePulls = serializeImagePulls;
            SystemReserveds = systemReserveds;
            TopologyManagerPolicy = topologyManagerPolicy;
            TopologyManagerScope = topologyManagerScope;
        }
    }
}
