// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Vke.Outputs
{

    [OutputType]
    public sealed class NodeStatus
    {
        public readonly ImmutableArray<Outputs.NodeStatusCondition> Conditions;
        /// <summary>
        /// 节点的状态，参数值有：Creating，Running，Deleting，Failed，Updating。
        /// </summary>
        public readonly string? Phase;

        [OutputConstructor]
        private NodeStatus(
            ImmutableArray<Outputs.NodeStatusCondition> conditions,

            string? phase)
        {
            Conditions = conditions;
            Phase = phase;
        }
    }
}
