// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.id.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AuthConfigJwtAuthConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final AuthConfigJwtAuthConfigArgs Empty = new AuthConfigJwtAuthConfigArgs();

    /**
     * Allowed Audience List
     * 
     */
    @Import(name="allowedAudiences")
    private @Nullable Output<List<String>> allowedAudiences;

    /**
     * @return Allowed Audience List
     * 
     */
    public Optional<Output<List<String>>> allowedAudiences() {
        return Optional.ofNullable(this.allowedAudiences);
    }

    /**
     * Allowed Client List
     * 
     */
    @Import(name="allowedClients")
    private @Nullable Output<List<String>> allowedClients;

    /**
     * @return Allowed Client List
     * 
     */
    public Optional<Output<List<String>>> allowedClients() {
        return Optional.ofNullable(this.allowedClients);
    }

    /**
     * JWT Discovery URL。
     * 
     */
    @Import(name="discoveryUrl")
    private @Nullable Output<String> discoveryUrl;

    /**
     * @return JWT Discovery URL。
     * 
     */
    public Optional<Output<String>> discoveryUrl() {
        return Optional.ofNullable(this.discoveryUrl);
    }

    private AuthConfigJwtAuthConfigArgs() {}

    private AuthConfigJwtAuthConfigArgs(AuthConfigJwtAuthConfigArgs $) {
        this.allowedAudiences = $.allowedAudiences;
        this.allowedClients = $.allowedClients;
        this.discoveryUrl = $.discoveryUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AuthConfigJwtAuthConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AuthConfigJwtAuthConfigArgs $;

        public Builder() {
            $ = new AuthConfigJwtAuthConfigArgs();
        }

        public Builder(AuthConfigJwtAuthConfigArgs defaults) {
            $ = new AuthConfigJwtAuthConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param allowedAudiences Allowed Audience List
         * 
         * @return builder
         * 
         */
        public Builder allowedAudiences(@Nullable Output<List<String>> allowedAudiences) {
            $.allowedAudiences = allowedAudiences;
            return this;
        }

        /**
         * @param allowedAudiences Allowed Audience List
         * 
         * @return builder
         * 
         */
        public Builder allowedAudiences(List<String> allowedAudiences) {
            return allowedAudiences(Output.of(allowedAudiences));
        }

        /**
         * @param allowedAudiences Allowed Audience List
         * 
         * @return builder
         * 
         */
        public Builder allowedAudiences(String... allowedAudiences) {
            return allowedAudiences(List.of(allowedAudiences));
        }

        /**
         * @param allowedClients Allowed Client List
         * 
         * @return builder
         * 
         */
        public Builder allowedClients(@Nullable Output<List<String>> allowedClients) {
            $.allowedClients = allowedClients;
            return this;
        }

        /**
         * @param allowedClients Allowed Client List
         * 
         * @return builder
         * 
         */
        public Builder allowedClients(List<String> allowedClients) {
            return allowedClients(Output.of(allowedClients));
        }

        /**
         * @param allowedClients Allowed Client List
         * 
         * @return builder
         * 
         */
        public Builder allowedClients(String... allowedClients) {
            return allowedClients(List.of(allowedClients));
        }

        /**
         * @param discoveryUrl JWT Discovery URL。
         * 
         * @return builder
         * 
         */
        public Builder discoveryUrl(@Nullable Output<String> discoveryUrl) {
            $.discoveryUrl = discoveryUrl;
            return this;
        }

        /**
         * @param discoveryUrl JWT Discovery URL。
         * 
         * @return builder
         * 
         */
        public Builder discoveryUrl(String discoveryUrl) {
            return discoveryUrl(Output.of(discoveryUrl));
        }

        public AuthConfigJwtAuthConfigArgs build() {
            return $;
        }
    }

}
