// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Plural Data Source schema for Volcengine::VKE::Addon
 */
export function getAddons(opts?: pulumi.InvokeOptions): Promise<GetAddonsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("volcenginecc:vke/getAddons:getAddons", {
    }, opts);
}

/**
 * A collection of values returned by getAddons.
 */
export interface GetAddonsResult {
    /**
     * Uniquely identifies the data source.
     */
    readonly id: string;
    /**
     * Set of Resource Identifiers.
     */
    readonly ids: string[];
}
/**
 * Plural Data Source schema for Volcengine::VKE::Addon
 */
export function getAddonsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAddonsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("volcenginecc:vke/getAddons:getAddons", {
    }, opts);
}
