// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.cdn.outputs;

import com.pulumi.core.annotations.CustomType;
import com.volcengine.volcenginecc.cdn.outputs.DomainRequestHeaderConditionConditionRule;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainRequestHeaderCondition {
    private @Nullable List<DomainRequestHeaderConditionConditionRule> conditionRules;
    /**
     * @return 表示多条ConditionRule 之间的逻辑关系。该参数有以下取值：AND: 表示逻辑关系是 &#34;AND&#34;。OR：表示逻辑关系是 &#34;OR&#34;。该参数的默认值是 OR。
     * 
     */
    private @Nullable String connective;

    private DomainRequestHeaderCondition() {}
    public List<DomainRequestHeaderConditionConditionRule> conditionRules() {
        return this.conditionRules == null ? List.of() : this.conditionRules;
    }
    /**
     * @return 表示多条ConditionRule 之间的逻辑关系。该参数有以下取值：AND: 表示逻辑关系是 &#34;AND&#34;。OR：表示逻辑关系是 &#34;OR&#34;。该参数的默认值是 OR。
     * 
     */
    public Optional<String> connective() {
        return Optional.ofNullable(this.connective);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainRequestHeaderCondition defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<DomainRequestHeaderConditionConditionRule> conditionRules;
        private @Nullable String connective;
        public Builder() {}
        public Builder(DomainRequestHeaderCondition defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conditionRules = defaults.conditionRules;
    	      this.connective = defaults.connective;
        }

        @CustomType.Setter
        public Builder conditionRules(@Nullable List<DomainRequestHeaderConditionConditionRule> conditionRules) {

            this.conditionRules = conditionRules;
            return this;
        }
        public Builder conditionRules(DomainRequestHeaderConditionConditionRule... conditionRules) {
            return conditionRules(List.of(conditionRules));
        }
        @CustomType.Setter
        public Builder connective(@Nullable String connective) {

            this.connective = connective;
            return this;
        }
        public DomainRequestHeaderCondition build() {
            final var _resultValue = new DomainRequestHeaderCondition();
            _resultValue.conditionRules = conditionRules;
            _resultValue.connective = connective;
            return _resultValue;
        }
    }
}
