// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.cdn.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDomainCustomErrorPageErrorPageRuleErrorPageAction {
    /**
     * @return 表示实际的操作。当前您只能指定该参数值为 redirect。表示对客户端请求进行重定向。
     * 
     */
    private String action;
    /**
     * @return 表示重定向的响应状态码。您可以根据需求选择合适的状态码。该参数的取值有 301、302、303、307、308。需要留意的是：对于 301 和 302，如果原请求使用的方法不是 GET，那么客户端向新的URL发送请求时，新请求使用的方法可能变成 GET。对于 303，新请求使用的方法是 GET。对于 307 和 308，新请求使用的方法与原请求相同，不会被改变。
     * 
     */
    private String redirectCode;
    /**
     * @return 表示跳转的目标地址，长度不能超过 1,024 个字符。地址必须包含协议，域名以及路径，并且符合 URL 的规范。
     * 
     */
    private String redirectUrl;
    /**
     * @return 表示一个状态码，取值范围是 400-599。您可以输入 4xx 或者 5xx。4xx 表示 400-499 之间的所有状态码。5xx 表示 500-599 之间的所有状态码。
     * 
     */
    private String statusCode;

    private GetDomainCustomErrorPageErrorPageRuleErrorPageAction() {}
    /**
     * @return 表示实际的操作。当前您只能指定该参数值为 redirect。表示对客户端请求进行重定向。
     * 
     */
    public String action() {
        return this.action;
    }
    /**
     * @return 表示重定向的响应状态码。您可以根据需求选择合适的状态码。该参数的取值有 301、302、303、307、308。需要留意的是：对于 301 和 302，如果原请求使用的方法不是 GET，那么客户端向新的URL发送请求时，新请求使用的方法可能变成 GET。对于 303，新请求使用的方法是 GET。对于 307 和 308，新请求使用的方法与原请求相同，不会被改变。
     * 
     */
    public String redirectCode() {
        return this.redirectCode;
    }
    /**
     * @return 表示跳转的目标地址，长度不能超过 1,024 个字符。地址必须包含协议，域名以及路径，并且符合 URL 的规范。
     * 
     */
    public String redirectUrl() {
        return this.redirectUrl;
    }
    /**
     * @return 表示一个状态码，取值范围是 400-599。您可以输入 4xx 或者 5xx。4xx 表示 400-499 之间的所有状态码。5xx 表示 500-599 之间的所有状态码。
     * 
     */
    public String statusCode() {
        return this.statusCode;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainCustomErrorPageErrorPageRuleErrorPageAction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String action;
        private String redirectCode;
        private String redirectUrl;
        private String statusCode;
        public Builder() {}
        public Builder(GetDomainCustomErrorPageErrorPageRuleErrorPageAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.action = defaults.action;
    	      this.redirectCode = defaults.redirectCode;
    	      this.redirectUrl = defaults.redirectUrl;
    	      this.statusCode = defaults.statusCode;
        }

        @CustomType.Setter
        public Builder action(String action) {
            if (action == null) {
              throw new MissingRequiredPropertyException("GetDomainCustomErrorPageErrorPageRuleErrorPageAction", "action");
            }
            this.action = action;
            return this;
        }
        @CustomType.Setter
        public Builder redirectCode(String redirectCode) {
            if (redirectCode == null) {
              throw new MissingRequiredPropertyException("GetDomainCustomErrorPageErrorPageRuleErrorPageAction", "redirectCode");
            }
            this.redirectCode = redirectCode;
            return this;
        }
        @CustomType.Setter
        public Builder redirectUrl(String redirectUrl) {
            if (redirectUrl == null) {
              throw new MissingRequiredPropertyException("GetDomainCustomErrorPageErrorPageRuleErrorPageAction", "redirectUrl");
            }
            this.redirectUrl = redirectUrl;
            return this;
        }
        @CustomType.Setter
        public Builder statusCode(String statusCode) {
            if (statusCode == null) {
              throw new MissingRequiredPropertyException("GetDomainCustomErrorPageErrorPageRuleErrorPageAction", "statusCode");
            }
            this.statusCode = statusCode;
            return this;
        }
        public GetDomainCustomErrorPageErrorPageRuleErrorPageAction build() {
            final var _resultValue = new GetDomainCustomErrorPageErrorPageRuleErrorPageAction();
            _resultValue.action = action;
            _resultValue.redirectCode = redirectCode;
            _resultValue.redirectUrl = redirectUrl;
            _resultValue.statusCode = statusCode;
            return _resultValue;
        }
    }
}
