// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Each ALB instance must have at least one listener to function properly. The listener receives client requests and distributes them to backend servers based on your configured forwarding rules and load balancing algorithm. You can create multiple listeners under one ALB instance and configure different protocols for each listener to handle client requests using different protocols.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcenginecc from "@volcengine/pulumi-volcenginecc";
 *
 * const aLBListenerDemo = new volcenginecc.alb.Listener("ALBListenerDemo", {
 *     loadBalancerId: "alb-bdazuxj87hts8dv40noxxxxx",
 *     listenerName: "ALBListenerDemo",
 *     protocol: "HTTPS",
 *     port: 80,
 *     enabled: "on",
 *     serverGroupId: "rsp-1pff7rhpf5e68845wfah2xxxx",
 *     aclStatus: "on",
 *     aclType: "black",
 *     aclIds: ["acl-xp8avgtjnmrk54ov5fyoxxxx"],
 *     customizedCfgId: "ccfg-xoblsk63beo054ov5el5xxxx",
 *     description: "ALBListenerDemo description",
 *     tags: [{
 *         key: "env",
 *         value: "test",
 *     }],
 *     certificateSource: "cert_center",
 *     certCenterCertificateId: "cert-a126f867a19141618ff316a52a50xxxx",
 *     caCertificateSource: "pca_root",
 *     pcaRootCaCertificateId: "pca_root_xxxxxx",
 *     enableHttp2: "on",
 *     enableQuic: "off",
 *     domainExtensions: [{
 *         cert_center_certificate_id: "cert-7718b7e7afa94e4db38ec9092cxxxxxx",
 *         certificate_source: "cert_center",
 *         domain: "",
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import volcenginecc:alb/listener:Listener example "listener_id"
 * ```
 */
export class Listener extends pulumi.CustomResource {
    /**
     * Get an existing Listener resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ListenerState, opts?: pulumi.CustomResourceOptions): Listener {
        return new Listener(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'volcenginecc:alb/listener:Listener';

    /**
     * Returns true if the given object is an instance of Listener.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Listener {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Listener.__pulumiType;
    }

    /**
     * Whether the listener has enabled the 'Log custom header in access logs' feature: on: Feature is enabled. off: Feature is not enabled.
     */
    declare public readonly accessLogRecordCustomizedHeadersEnabled: pulumi.Output<string>;
    /**
     * Access control policy group ID bound to the listener. When the AclStatus parameter is set to on, AclIds is required.
     */
    declare public readonly aclIds: pulumi.Output<string[]>;
    /**
     * Enable access control. Values: on: enabled. off: disabled (default).
     */
    declare public readonly aclStatus: pulumi.Output<string>;
    /**
     * Access control method. Values: white: allowlist mode. The listener only forwards requests from IP addresses or address ranges set in the selected access control policy group. If no IP is added to the selected policy group, the listener does not forward any requests. black: denylist mode. The listener only rejects requests from IP addresses or address ranges set in the selected access control policy group. If no IP is added to the selected policy group, the listener forwards all requests. When the AclStatus parameter is set to on, AclType is required.
     */
    declare public readonly aclType: pulumi.Output<string>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication in HTTPS listeners. If the certificate source is alb, you must specify the CACertificateId parameter.
     */
    declare public readonly caCertificateId: pulumi.Output<string>;
    /**
     * Source of the CA certificate associated with the HTTPS listener, used for mutual authentication. alb (default): Certificate uploaded via ALB. Standard ALB instances do not support certificates from this source. pca*root: Private root CA certificate purchased or uploaded via Volcano Engine Certificate Center. pca*sub: Private subordinate CA certificate purchased or uploaded via Volcano Engine Certificate Center.
     */
    declare public readonly caCertificateSource: pulumi.Output<string>;
    /**
     * Certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener with the certificate source set to cert_center.
     */
    declare public readonly certCenterCertificateId: pulumi.Output<string>;
    /**
     * Certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener and the certificate source is alb.
     */
    declare public readonly certificateId: pulumi.Output<string>;
    /**
     * The source of the default certificate associated with the HTTPS listener. Values: alb: certificate uploaded via ALB. cert*center: SSL certificate purchased or uploaded through Volcano Engine Certificate Center. pca*leaf: private leaf certificate purchased or uploaded through Volcano Engine Certificate Center.
     */
    declare public readonly certificateSource: pulumi.Output<string>;
    /**
     * Listener creation time.
     */
    declare public /*out*/ readonly createdTime: pulumi.Output<string>;
    /**
     * Personalized configuration ID. If not bound, the value is an empty string.
     */
    declare public readonly customizedCfgId: pulumi.Output<string>;
    /**
     * Listener description. Cannot start with http:// or https://. Must start with a letter or Chinese character. May include numbers, English commas (,), periods (.), underscores (_), spaces ( ), equals signs (=), hyphens (-), Chinese commas (，), and Chinese periods (。). Length must be between 1 and 255 characters. If not specified, defaults to an empty string.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * List of additional domain names associated with the HTTPS listener. A single HTTPS listener can be associated with up to 20 additional domain names.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    declare public readonly domainExtensions: pulumi.Output<outputs.alb.ListenerDomainExtension[]>;
    /**
     * HTTP2.0 feature switch. This parameter is only valid for HTTPS listeners. Values: on: enabled. off: disabled (default).
     */
    declare public readonly enableHttp2: pulumi.Output<string>;
    /**
     * QUIC feature switch. This parameter is only valid for HTTPS listeners. Values: on: enabled. off: disabled (default). Only standard ALB instances support QUIC.
     */
    declare public readonly enableQuic: pulumi.Output<string>;
    /**
     * Listener on/off status. Values: on: On (default). off: Off.
     */
    declare public readonly enabled: pulumi.Output<string>;
    /**
     * Listener ID.
     */
    declare public /*out*/ readonly listenerId: pulumi.Output<string>;
    /**
     * Listener name. If not specified, named in the format 'protocol-port'. Cannot start with http:// or https://. Must start with a letter or Chinese character and can include numbers, dot (.), underscore (_), and hyphen (-). Length must be between 1 and 128 characters.
     */
    declare public readonly listenerName: pulumi.Output<string>;
    /**
     * Load balancer instance ID to which the listener belongs.
     */
    declare public readonly loadBalancerId: pulumi.Output<string>;
    /**
     * Private leaf certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener and the certificate source is pca_leaf.
     */
    declare public readonly pcaLeafCertificateId: pulumi.Output<string>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication on HTTPS listeners. When the certificate source is pca_root, you must specify the PcaRootCACertificateId parameter.
     */
    declare public readonly pcaRootCaCertificateId: pulumi.Output<string>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication on HTTPS listeners. When the certificate source is pca_sub, you must specify the PcaSubCACertificateId parameter.
     */
    declare public readonly pcaSubCaCertificateId: pulumi.Output<string>;
    /**
     * The listener port. Values: 1   - 65535.
     */
    declare public readonly port: pulumi.Output<number>;
    /**
     * Name of the project to which the listener belongs.
     */
    declare public /*out*/ readonly projectName: pulumi.Output<string>;
    /**
     * Listener protocol. Supports HTTP and HTTPS protocols.
     */
    declare public readonly protocol: pulumi.Output<string>;
    /**
     * Default server group for the listener.
     */
    declare public readonly serverGroupId: pulumi.Output<string>;
    /**
     * All server groups associated with the listener.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    declare public readonly serverGroups: pulumi.Output<outputs.alb.ListenerServerGroup[]>;
    /**
     * Listener status. Values: Creating: Creating. Active: Running. Pending: Changing configuration. Disabled: Stopped. Deleting: Deleting.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Listener tags.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    declare public readonly tags: pulumi.Output<outputs.alb.ListenerTag[]>;
    /**
     * Time of the listener's most recent operation.
     */
    declare public /*out*/ readonly updatedTime: pulumi.Output<string>;

    /**
     * Create a Listener resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ListenerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ListenerArgs | ListenerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ListenerState | undefined;
            resourceInputs["accessLogRecordCustomizedHeadersEnabled"] = state?.accessLogRecordCustomizedHeadersEnabled;
            resourceInputs["aclIds"] = state?.aclIds;
            resourceInputs["aclStatus"] = state?.aclStatus;
            resourceInputs["aclType"] = state?.aclType;
            resourceInputs["caCertificateId"] = state?.caCertificateId;
            resourceInputs["caCertificateSource"] = state?.caCertificateSource;
            resourceInputs["certCenterCertificateId"] = state?.certCenterCertificateId;
            resourceInputs["certificateId"] = state?.certificateId;
            resourceInputs["certificateSource"] = state?.certificateSource;
            resourceInputs["createdTime"] = state?.createdTime;
            resourceInputs["customizedCfgId"] = state?.customizedCfgId;
            resourceInputs["description"] = state?.description;
            resourceInputs["domainExtensions"] = state?.domainExtensions;
            resourceInputs["enableHttp2"] = state?.enableHttp2;
            resourceInputs["enableQuic"] = state?.enableQuic;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["listenerId"] = state?.listenerId;
            resourceInputs["listenerName"] = state?.listenerName;
            resourceInputs["loadBalancerId"] = state?.loadBalancerId;
            resourceInputs["pcaLeafCertificateId"] = state?.pcaLeafCertificateId;
            resourceInputs["pcaRootCaCertificateId"] = state?.pcaRootCaCertificateId;
            resourceInputs["pcaSubCaCertificateId"] = state?.pcaSubCaCertificateId;
            resourceInputs["port"] = state?.port;
            resourceInputs["projectName"] = state?.projectName;
            resourceInputs["protocol"] = state?.protocol;
            resourceInputs["serverGroupId"] = state?.serverGroupId;
            resourceInputs["serverGroups"] = state?.serverGroups;
            resourceInputs["status"] = state?.status;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["updatedTime"] = state?.updatedTime;
        } else {
            const args = argsOrState as ListenerArgs | undefined;
            if (args?.loadBalancerId === undefined && !opts.urn) {
                throw new Error("Missing required property 'loadBalancerId'");
            }
            if (args?.port === undefined && !opts.urn) {
                throw new Error("Missing required property 'port'");
            }
            if (args?.protocol === undefined && !opts.urn) {
                throw new Error("Missing required property 'protocol'");
            }
            if (args?.serverGroupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverGroupId'");
            }
            resourceInputs["accessLogRecordCustomizedHeadersEnabled"] = args?.accessLogRecordCustomizedHeadersEnabled;
            resourceInputs["aclIds"] = args?.aclIds;
            resourceInputs["aclStatus"] = args?.aclStatus;
            resourceInputs["aclType"] = args?.aclType;
            resourceInputs["caCertificateId"] = args?.caCertificateId;
            resourceInputs["caCertificateSource"] = args?.caCertificateSource;
            resourceInputs["certCenterCertificateId"] = args?.certCenterCertificateId;
            resourceInputs["certificateId"] = args?.certificateId;
            resourceInputs["certificateSource"] = args?.certificateSource;
            resourceInputs["customizedCfgId"] = args?.customizedCfgId;
            resourceInputs["description"] = args?.description;
            resourceInputs["domainExtensions"] = args?.domainExtensions;
            resourceInputs["enableHttp2"] = args?.enableHttp2;
            resourceInputs["enableQuic"] = args?.enableQuic;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["listenerName"] = args?.listenerName;
            resourceInputs["loadBalancerId"] = args?.loadBalancerId;
            resourceInputs["pcaLeafCertificateId"] = args?.pcaLeafCertificateId;
            resourceInputs["pcaRootCaCertificateId"] = args?.pcaRootCaCertificateId;
            resourceInputs["pcaSubCaCertificateId"] = args?.pcaSubCaCertificateId;
            resourceInputs["port"] = args?.port;
            resourceInputs["protocol"] = args?.protocol;
            resourceInputs["serverGroupId"] = args?.serverGroupId;
            resourceInputs["serverGroups"] = args?.serverGroups;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["createdTime"] = undefined /*out*/;
            resourceInputs["listenerId"] = undefined /*out*/;
            resourceInputs["projectName"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedTime"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Listener.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Listener resources.
 */
export interface ListenerState {
    /**
     * Whether the listener has enabled the 'Log custom header in access logs' feature: on: Feature is enabled. off: Feature is not enabled.
     */
    accessLogRecordCustomizedHeadersEnabled?: pulumi.Input<string | undefined>;
    /**
     * Access control policy group ID bound to the listener. When the AclStatus parameter is set to on, AclIds is required.
     */
    aclIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Enable access control. Values: on: enabled. off: disabled (default).
     */
    aclStatus?: pulumi.Input<string | undefined>;
    /**
     * Access control method. Values: white: allowlist mode. The listener only forwards requests from IP addresses or address ranges set in the selected access control policy group. If no IP is added to the selected policy group, the listener does not forward any requests. black: denylist mode. The listener only rejects requests from IP addresses or address ranges set in the selected access control policy group. If no IP is added to the selected policy group, the listener forwards all requests. When the AclStatus parameter is set to on, AclType is required.
     */
    aclType?: pulumi.Input<string | undefined>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication in HTTPS listeners. If the certificate source is alb, you must specify the CACertificateId parameter.
     */
    caCertificateId?: pulumi.Input<string | undefined>;
    /**
     * Source of the CA certificate associated with the HTTPS listener, used for mutual authentication. alb (default): Certificate uploaded via ALB. Standard ALB instances do not support certificates from this source. pca*root: Private root CA certificate purchased or uploaded via Volcano Engine Certificate Center. pca*sub: Private subordinate CA certificate purchased or uploaded via Volcano Engine Certificate Center.
     */
    caCertificateSource?: pulumi.Input<string | undefined>;
    /**
     * Certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener with the certificate source set to cert_center.
     */
    certCenterCertificateId?: pulumi.Input<string | undefined>;
    /**
     * Certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener and the certificate source is alb.
     */
    certificateId?: pulumi.Input<string | undefined>;
    /**
     * The source of the default certificate associated with the HTTPS listener. Values: alb: certificate uploaded via ALB. cert*center: SSL certificate purchased or uploaded through Volcano Engine Certificate Center. pca*leaf: private leaf certificate purchased or uploaded through Volcano Engine Certificate Center.
     */
    certificateSource?: pulumi.Input<string | undefined>;
    /**
     * Listener creation time.
     */
    createdTime?: pulumi.Input<string | undefined>;
    /**
     * Personalized configuration ID. If not bound, the value is an empty string.
     */
    customizedCfgId?: pulumi.Input<string | undefined>;
    /**
     * Listener description. Cannot start with http:// or https://. Must start with a letter or Chinese character. May include numbers, English commas (,), periods (.), underscores (_), spaces ( ), equals signs (=), hyphens (-), Chinese commas (，), and Chinese periods (。). Length must be between 1 and 255 characters. If not specified, defaults to an empty string.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * List of additional domain names associated with the HTTPS listener. A single HTTPS listener can be associated with up to 20 additional domain names.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    domainExtensions?: pulumi.Input<pulumi.Input<inputs.alb.ListenerDomainExtension>[] | undefined>;
    /**
     * HTTP2.0 feature switch. This parameter is only valid for HTTPS listeners. Values: on: enabled. off: disabled (default).
     */
    enableHttp2?: pulumi.Input<string | undefined>;
    /**
     * QUIC feature switch. This parameter is only valid for HTTPS listeners. Values: on: enabled. off: disabled (default). Only standard ALB instances support QUIC.
     */
    enableQuic?: pulumi.Input<string | undefined>;
    /**
     * Listener on/off status. Values: on: On (default). off: Off.
     */
    enabled?: pulumi.Input<string | undefined>;
    /**
     * Listener ID.
     */
    listenerId?: pulumi.Input<string | undefined>;
    /**
     * Listener name. If not specified, named in the format 'protocol-port'. Cannot start with http:// or https://. Must start with a letter or Chinese character and can include numbers, dot (.), underscore (_), and hyphen (-). Length must be between 1 and 128 characters.
     */
    listenerName?: pulumi.Input<string | undefined>;
    /**
     * Load balancer instance ID to which the listener belongs.
     */
    loadBalancerId?: pulumi.Input<string | undefined>;
    /**
     * Private leaf certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener and the certificate source is pca_leaf.
     */
    pcaLeafCertificateId?: pulumi.Input<string | undefined>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication on HTTPS listeners. When the certificate source is pca_root, you must specify the PcaRootCACertificateId parameter.
     */
    pcaRootCaCertificateId?: pulumi.Input<string | undefined>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication on HTTPS listeners. When the certificate source is pca_sub, you must specify the PcaSubCACertificateId parameter.
     */
    pcaSubCaCertificateId?: pulumi.Input<string | undefined>;
    /**
     * The listener port. Values: 1   - 65535.
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * Name of the project to which the listener belongs.
     */
    projectName?: pulumi.Input<string | undefined>;
    /**
     * Listener protocol. Supports HTTP and HTTPS protocols.
     */
    protocol?: pulumi.Input<string | undefined>;
    /**
     * Default server group for the listener.
     */
    serverGroupId?: pulumi.Input<string | undefined>;
    /**
     * All server groups associated with the listener.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    serverGroups?: pulumi.Input<pulumi.Input<inputs.alb.ListenerServerGroup>[] | undefined>;
    /**
     * Listener status. Values: Creating: Creating. Active: Running. Pending: Changing configuration. Disabled: Stopped. Deleting: Deleting.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Listener tags.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.alb.ListenerTag>[] | undefined>;
    /**
     * Time of the listener's most recent operation.
     */
    updatedTime?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Listener resource.
 */
export interface ListenerArgs {
    /**
     * Whether the listener has enabled the 'Log custom header in access logs' feature: on: Feature is enabled. off: Feature is not enabled.
     */
    accessLogRecordCustomizedHeadersEnabled?: pulumi.Input<string | undefined>;
    /**
     * Access control policy group ID bound to the listener. When the AclStatus parameter is set to on, AclIds is required.
     */
    aclIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Enable access control. Values: on: enabled. off: disabled (default).
     */
    aclStatus?: pulumi.Input<string | undefined>;
    /**
     * Access control method. Values: white: allowlist mode. The listener only forwards requests from IP addresses or address ranges set in the selected access control policy group. If no IP is added to the selected policy group, the listener does not forward any requests. black: denylist mode. The listener only rejects requests from IP addresses or address ranges set in the selected access control policy group. If no IP is added to the selected policy group, the listener forwards all requests. When the AclStatus parameter is set to on, AclType is required.
     */
    aclType?: pulumi.Input<string | undefined>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication in HTTPS listeners. If the certificate source is alb, you must specify the CACertificateId parameter.
     */
    caCertificateId?: pulumi.Input<string | undefined>;
    /**
     * Source of the CA certificate associated with the HTTPS listener, used for mutual authentication. alb (default): Certificate uploaded via ALB. Standard ALB instances do not support certificates from this source. pca*root: Private root CA certificate purchased or uploaded via Volcano Engine Certificate Center. pca*sub: Private subordinate CA certificate purchased or uploaded via Volcano Engine Certificate Center.
     */
    caCertificateSource?: pulumi.Input<string | undefined>;
    /**
     * Certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener with the certificate source set to cert_center.
     */
    certCenterCertificateId?: pulumi.Input<string | undefined>;
    /**
     * Certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener and the certificate source is alb.
     */
    certificateId?: pulumi.Input<string | undefined>;
    /**
     * The source of the default certificate associated with the HTTPS listener. Values: alb: certificate uploaded via ALB. cert*center: SSL certificate purchased or uploaded through Volcano Engine Certificate Center. pca*leaf: private leaf certificate purchased or uploaded through Volcano Engine Certificate Center.
     */
    certificateSource?: pulumi.Input<string | undefined>;
    /**
     * Personalized configuration ID. If not bound, the value is an empty string.
     */
    customizedCfgId?: pulumi.Input<string | undefined>;
    /**
     * Listener description. Cannot start with http:// or https://. Must start with a letter or Chinese character. May include numbers, English commas (,), periods (.), underscores (_), spaces ( ), equals signs (=), hyphens (-), Chinese commas (，), and Chinese periods (。). Length must be between 1 and 255 characters. If not specified, defaults to an empty string.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * List of additional domain names associated with the HTTPS listener. A single HTTPS listener can be associated with up to 20 additional domain names.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    domainExtensions?: pulumi.Input<pulumi.Input<inputs.alb.ListenerDomainExtension>[] | undefined>;
    /**
     * HTTP2.0 feature switch. This parameter is only valid for HTTPS listeners. Values: on: enabled. off: disabled (default).
     */
    enableHttp2?: pulumi.Input<string | undefined>;
    /**
     * QUIC feature switch. This parameter is only valid for HTTPS listeners. Values: on: enabled. off: disabled (default). Only standard ALB instances support QUIC.
     */
    enableQuic?: pulumi.Input<string | undefined>;
    /**
     * Listener on/off status. Values: on: On (default). off: Off.
     */
    enabled?: pulumi.Input<string | undefined>;
    /**
     * Listener name. If not specified, named in the format 'protocol-port'. Cannot start with http:// or https://. Must start with a letter or Chinese character and can include numbers, dot (.), underscore (_), and hyphen (-). Length must be between 1 and 128 characters.
     */
    listenerName?: pulumi.Input<string | undefined>;
    /**
     * Load balancer instance ID to which the listener belongs.
     */
    loadBalancerId: pulumi.Input<string>;
    /**
     * Private leaf certificate ID associated with the HTTPS listener. Required when creating an HTTPS listener and the certificate source is pca_leaf.
     */
    pcaLeafCertificateId?: pulumi.Input<string | undefined>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication on HTTPS listeners. When the certificate source is pca_root, you must specify the PcaRootCACertificateId parameter.
     */
    pcaRootCaCertificateId?: pulumi.Input<string | undefined>;
    /**
     * CA certificate ID associated with the HTTPS listener. This parameter is used for mutual authentication on HTTPS listeners. When the certificate source is pca_sub, you must specify the PcaSubCACertificateId parameter.
     */
    pcaSubCaCertificateId?: pulumi.Input<string | undefined>;
    /**
     * The listener port. Values: 1   - 65535.
     */
    port: pulumi.Input<number>;
    /**
     * Listener protocol. Supports HTTP and HTTPS protocols.
     */
    protocol: pulumi.Input<string>;
    /**
     * Default server group for the listener.
     */
    serverGroupId: pulumi.Input<string>;
    /**
     * All server groups associated with the listener.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    serverGroups?: pulumi.Input<pulumi.Input<inputs.alb.ListenerServerGroup>[] | undefined>;
    /**
     * Listener tags.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.alb.ListenerTag>[] | undefined>;
}
