// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Cen.Inputs
{

    public sealed class BandwidthPackageTagArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Tag key for user tags. Parameter   - N: indicates the tag key index, value range: 1–20. Use &amp; to separate multiple tag keys. Cannot start with sys:, in any case. Length range: 1–128 characters. Supports all languages, numbers, spaces ( ), underscores (_), periods (.), colons (:), slashes (/), equals (=), plus (+), hyphens (-), and @ (@). If a tag key starts or ends with a space, the system automatically removes it.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Tag value for user tags. Parameter   - N indicates the tag value index, range: 1–20. Use &amp; to separate multiple tag values. Length range: 0–256 characters. If not specified, defaults to empty. Supports all languages, numbers, spaces ( ), underscores (_), periods (.), colons (:), slashes (/), equals signs (=), plus signs (+), hyphens (-), and @ (@). Case-sensitive. If the tag value starts or ends with a space, the system automatically removes it.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public BandwidthPackageTagArgs()
        {
        }
        public static new BandwidthPackageTagArgs Empty => new BandwidthPackageTagArgs();
    }
}
