// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tls

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcenginecc/sdk/go/volcenginecc/internal"
)

// The log service provides log collection tools such as LogCollector and multi-language SDKs, supports various log collection methods, is compatible with open-source protocol frameworks like Kafka and OpenTelemetry, and supports log data collection from host applications, K8s clusters, mobile clients, Volcano Engine cloud products, and other cloud vendors.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/volcengine/pulumi-volcenginecc/sdk/go/volcenginecc/tls"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := tls.NewRule(ctx, "TLSRuleDemo", &tls.RuleArgs{
//				ContainerRule: &tls.RuleContainerRuleArgs{
//					Container_name_regex: "ccapi-test",
//					Env_tag: []map[string]interface{}{
//						map[string]interface{}{
//							"key": "k1",
//							"val": "v1",
//						},
//					},
//					Exclude_container_env_regex: []map[string]interface{}{
//						map[string]interface{}{
//							"key": "k2",
//							"val": "v2",
//						},
//					},
//					Exclude_container_label_regex: []map[string]interface{}{
//						map[string]interface{}{
//							"key": "k2",
//							"val": "v2",
//						},
//					},
//					Include_container_env_regex: []map[string]interface{}{
//						map[string]interface{}{
//							"key": "k1",
//							"val": "v1",
//						},
//					},
//					Include_container_label_regex: []map[string]interface{}{
//						map[string]interface{}{
//							"key": "k1",
//							"val": "v1",
//						},
//					},
//					Kubernetes_rule: map[string]interface{}{
//						"annotationTag": []map[string]interface{}{
//							map[string]interface{}{
//								"key": "k1",
//								"val": "v1",
//							},
//						},
//						"enableAllLabelTag": true,
//						"excludePodAnnotationRegex": []map[string]interface{}{
//							map[string]interface{}{
//								"key": "k2",
//								"val": "v2",
//							},
//						},
//						"excludePodLabelRegex": []map[string]interface{}{
//							map[string]interface{}{
//								"key": "k2",
//								"val": "v2",
//							},
//						},
//						"includePodAnnotationRegex": []map[string]interface{}{
//							map[string]interface{}{
//								"key": "k1",
//								"val": "v1",
//							},
//						},
//						"includePodLabelRegex": []map[string]interface{}{
//							map[string]interface{}{
//								"key": "k1",
//								"val": "v1",
//							},
//						},
//						"labelTag": []map[string]interface{}{
//							map[string]interface{}{
//								"key": "k1",
//								"val": "v1",
//							},
//						},
//						"namespaceNameRegex": "ccapi",
//						"podNameRegex":       "ccapi",
//						"workloadNameRegex":  "ccapi",
//						"workloadType":       "Deployment",
//					},
//					Stream: pulumi.String(""),
//				},
//				ExcludePaths: tls.RuleExcludePathArray{
//					&tls.RuleExcludePathArgs{
//						Type:  pulumi.String("Path"),
//						Value: pulumi.String("/test"),
//					},
//				},
//				ExtractRule: &tls.RuleExtractRuleArgs{
//					Begin_regex:       "",
//					Delimiter:         pulumi.String(" "),
//					Enable_nanosecond: true,
//					Filter_key_regex: []map[string]interface{}{
//						map[string]interface{}{
//							"key":   "k1",
//							"regex": "v1",
//						},
//					},
//					Keys: pulumi.StringArray{
//						pulumi.String("k1"),
//					},
//					Log_regex: "",
//					Log_template: map[string]interface{}{
//						"format": "",
//						"type":   "",
//					},
//					Quote:                   pulumi.String(""),
//					Time_extract_regex:      "dsfasdf",
//					Time_format:             "%Y-%m-%d %H:%M:%S.%f",
//					Time_key:                "time_key",
//					Time_sample:             "2006-01-02T15:04:05Z07:00",
//					Time_zone:               "Etc/GMT+12",
//					Un_match_log_key:        "LogParseFailed",
//					Un_match_up_load_switch: true,
//				},
//				HostGroupInfos: tls.RuleHostGroupInfoArray{
//					&tls.RuleHostGroupInfoArgs{
//						Host_group_id: "38feb3b9-xxxxx-de52cxxxxx",
//					},
//				},
//				InputType: pulumi.Int(2),
//				LogSample: pulumi.String("asdfasf"),
//				LogType:   pulumi.String("delimiter_log"),
//				Paths: pulumi.StringArray{
//					pulumi.String("/test"),
//				},
//				RuleName: pulumi.String("dx-rule-1"),
//				TopicId:  pulumi.String("b881e3cd-xxxxx-966f-fe98xxxxxxx"),
//				UserDefineRule: &tls.RuleUserDefineRuleArgs{
//					Advanced: &tls.RuleUserDefineRuleAdvancedArgs{
//						CloseEof:                   pulumi.Bool(false),
//						CloseInactive:              pulumi.Int(10),
//						CloseRemoved:               pulumi.Bool(false),
//						CloseRenamed:               pulumi.Bool(false),
//						CloseTimeout:               pulumi.Int(0),
//						NoLineTerminatorEofMaxTime: pulumi.Int(0),
//					},
//					Enable_host_group_label: true,
//					Enable_hostname:         true,
//					Enable_raw_log:          true,
//					Fields: tls.RuleUserDefineRuleFieldArray{
//						&tls.RuleUserDefineRuleFieldArgs{
//							Key: pulumi.String("k1"),
//							Val: pulumi.String("v1"),
//						},
//					},
//					Host_group_label_key: "host_group_label",
//					Hostname_key:         "hostname",
//					Ignore_older:         72,
//					Multi_collects_type:  "RuleID",
//					Parse_path_rule: map[string]interface{}{
//						"keys": []string{
//							"instance-id",
//							"pod-name",
//						},
//						"pathSample": "/var/logs/instanceid_any_podname/test.log",
//						"regex":      "/var/logs/([a-z]*)_any_([a-z]*)/test.log",
//					},
//					Plugin: &tls.RuleUserDefineRulePluginArgs{
//						Processors: pulumi.String("{}"),
//					},
//					Raw_log_key: "raw",
//					Shard_hash_key: map[string]interface{}{
//						"hashKey": "2342134",
//					},
//					Tail_files:   true,
//					Tail_size_kb: 10240,
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import volcenginecc:tls/rule:Rule example "rule_id"
// ```
type Rule struct {
	pulumi.CustomResourceState

	// Container log collection rules.
	ContainerRule RuleContainerRuleOutput `pulumi:"containerRule"`
	// Time when the collection configuration was created.
	CreateTime pulumi.StringOutput `pulumi:"createTime"`
	// Denylist entries for collection. You can create up to 10 denylist entries. When InputType=0 or InputType=2: If Type is Path, Value represents a directory. Supports exact match and wildcard pattern matching. Wildcards supported: *, ?. The ** wildcard is not supported. If Type is File, Value represents a file name. Supports exact match and wildcard pattern matching. Wildcards supported: **, *, ?. Only one ** wildcard can be configured at most. When InputType=1: Configuring a denylist is not allowed.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	ExcludePaths RuleExcludePathArrayOutput `pulumi:"excludePaths"`
	// Log extraction rules. Note: This parameter is required if LogType is set to any type other than minimalist*log or json*log.
	ExtractRule RuleExtractRuleOutput `pulumi:"extractRule"`
	// Machine group information list.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	HostGroupInfos RuleHostGroupInfoArrayOutput `pulumi:"hostGroupInfos"`
	// Collection type. 0: (Default) Host log file. 1: K8s container stdout. 2: K8s container internal log file.
	InputType pulumi.IntOutput `pulumi:"inputType"`
	// Log sample. Maximum length is 3000 characters. Log sample content must match the collection mode. Single-line full-text mode and JSON mode do not require a log sample. Other modes require a log sample, and the content must match the collection mode.
	LogSample pulumi.StringOutput `pulumi:"logSample"`
	// Collection mode. minimalist*log: (Default) Single-line full-text mode. json*log: JSON mode. delimiter*log: Delimiter mode. multiline*log: Multi-line full-text mode. fullregex_log: Full regex mode.
	LogType pulumi.StringOutput `pulumi:"logType"`
	// Collection configuration modification time.
	ModifyTime pulumi.StringOutput `pulumi:"modifyTime"`
	// Collection path list. You can create up to 10 collection paths. Collection paths must be specified as absolute paths; relative paths are not supported. When InputType=0 or InputType=2, collection paths support exact match and wildcard mode. Wildcards only support **, *, and ?, but you can configure at most one ** wildcard. When InputType=1, you do not need to configure the collection path list.
	Paths pulumi.StringArrayOutput `pulumi:"paths"`
	// Collection configuration status. 0: Running. 1: Paused.
	Pause pulumi.IntOutput `pulumi:"pause"`
	// ID of the project to which the collection configuration belongs.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Name of the project to which the collection configuration belongs
	ProjectName pulumi.StringOutput `pulumi:"projectName"`
	// Collection configuration ID.
	RuleId pulumi.StringOutput `pulumi:"ruleId"`
	// Collection configuration name. Please refer to the resource naming rules. Must be unique within a log topic.
	RuleName pulumi.StringOutput `pulumi:"ruleName"`
	// Log topic ID to which the collection configuration belongs.
	TopicId pulumi.StringOutput `pulumi:"topicId"`
	// Name of the log topic to which the collection configuration belongs.
	TopicName pulumi.StringOutput `pulumi:"topicName"`
	// User-defined collection rules.
	UserDefineRule RuleUserDefineRuleOutput `pulumi:"userDefineRule"`
}

// NewRule registers a new resource with the given unique name, arguments, and options.
func NewRule(ctx *pulumi.Context,
	name string, args *RuleArgs, opts ...pulumi.ResourceOption) (*Rule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.RuleName == nil {
		return nil, errors.New("invalid value for required argument 'RuleName'")
	}
	if args.TopicId == nil {
		return nil, errors.New("invalid value for required argument 'TopicId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Rule
	err := ctx.RegisterResource("volcenginecc:tls/rule:Rule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRule gets an existing Rule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RuleState, opts ...pulumi.ResourceOption) (*Rule, error) {
	var resource Rule
	err := ctx.ReadResource("volcenginecc:tls/rule:Rule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Rule resources.
type ruleState struct {
	// Container log collection rules.
	ContainerRule *RuleContainerRule `pulumi:"containerRule"`
	// Time when the collection configuration was created.
	CreateTime *string `pulumi:"createTime"`
	// Denylist entries for collection. You can create up to 10 denylist entries. When InputType=0 or InputType=2: If Type is Path, Value represents a directory. Supports exact match and wildcard pattern matching. Wildcards supported: *, ?. The ** wildcard is not supported. If Type is File, Value represents a file name. Supports exact match and wildcard pattern matching. Wildcards supported: **, *, ?. Only one ** wildcard can be configured at most. When InputType=1: Configuring a denylist is not allowed.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	ExcludePaths []RuleExcludePath `pulumi:"excludePaths"`
	// Log extraction rules. Note: This parameter is required if LogType is set to any type other than minimalist*log or json*log.
	ExtractRule *RuleExtractRule `pulumi:"extractRule"`
	// Machine group information list.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	HostGroupInfos []RuleHostGroupInfo `pulumi:"hostGroupInfos"`
	// Collection type. 0: (Default) Host log file. 1: K8s container stdout. 2: K8s container internal log file.
	InputType *int `pulumi:"inputType"`
	// Log sample. Maximum length is 3000 characters. Log sample content must match the collection mode. Single-line full-text mode and JSON mode do not require a log sample. Other modes require a log sample, and the content must match the collection mode.
	LogSample *string `pulumi:"logSample"`
	// Collection mode. minimalist*log: (Default) Single-line full-text mode. json*log: JSON mode. delimiter*log: Delimiter mode. multiline*log: Multi-line full-text mode. fullregex_log: Full regex mode.
	LogType *string `pulumi:"logType"`
	// Collection configuration modification time.
	ModifyTime *string `pulumi:"modifyTime"`
	// Collection path list. You can create up to 10 collection paths. Collection paths must be specified as absolute paths; relative paths are not supported. When InputType=0 or InputType=2, collection paths support exact match and wildcard mode. Wildcards only support **, *, and ?, but you can configure at most one ** wildcard. When InputType=1, you do not need to configure the collection path list.
	Paths []string `pulumi:"paths"`
	// Collection configuration status. 0: Running. 1: Paused.
	Pause *int `pulumi:"pause"`
	// ID of the project to which the collection configuration belongs.
	ProjectId *string `pulumi:"projectId"`
	// Name of the project to which the collection configuration belongs
	ProjectName *string `pulumi:"projectName"`
	// Collection configuration ID.
	RuleId *string `pulumi:"ruleId"`
	// Collection configuration name. Please refer to the resource naming rules. Must be unique within a log topic.
	RuleName *string `pulumi:"ruleName"`
	// Log topic ID to which the collection configuration belongs.
	TopicId *string `pulumi:"topicId"`
	// Name of the log topic to which the collection configuration belongs.
	TopicName *string `pulumi:"topicName"`
	// User-defined collection rules.
	UserDefineRule *RuleUserDefineRule `pulumi:"userDefineRule"`
}

type RuleState struct {
	// Container log collection rules.
	ContainerRule RuleContainerRulePtrInput
	// Time when the collection configuration was created.
	CreateTime pulumi.StringPtrInput
	// Denylist entries for collection. You can create up to 10 denylist entries. When InputType=0 or InputType=2: If Type is Path, Value represents a directory. Supports exact match and wildcard pattern matching. Wildcards supported: *, ?. The ** wildcard is not supported. If Type is File, Value represents a file name. Supports exact match and wildcard pattern matching. Wildcards supported: **, *, ?. Only one ** wildcard can be configured at most. When InputType=1: Configuring a denylist is not allowed.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	ExcludePaths RuleExcludePathArrayInput
	// Log extraction rules. Note: This parameter is required if LogType is set to any type other than minimalist*log or json*log.
	ExtractRule RuleExtractRulePtrInput
	// Machine group information list.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	HostGroupInfos RuleHostGroupInfoArrayInput
	// Collection type. 0: (Default) Host log file. 1: K8s container stdout. 2: K8s container internal log file.
	InputType pulumi.IntPtrInput
	// Log sample. Maximum length is 3000 characters. Log sample content must match the collection mode. Single-line full-text mode and JSON mode do not require a log sample. Other modes require a log sample, and the content must match the collection mode.
	LogSample pulumi.StringPtrInput
	// Collection mode. minimalist*log: (Default) Single-line full-text mode. json*log: JSON mode. delimiter*log: Delimiter mode. multiline*log: Multi-line full-text mode. fullregex_log: Full regex mode.
	LogType pulumi.StringPtrInput
	// Collection configuration modification time.
	ModifyTime pulumi.StringPtrInput
	// Collection path list. You can create up to 10 collection paths. Collection paths must be specified as absolute paths; relative paths are not supported. When InputType=0 or InputType=2, collection paths support exact match and wildcard mode. Wildcards only support **, *, and ?, but you can configure at most one ** wildcard. When InputType=1, you do not need to configure the collection path list.
	Paths pulumi.StringArrayInput
	// Collection configuration status. 0: Running. 1: Paused.
	Pause pulumi.IntPtrInput
	// ID of the project to which the collection configuration belongs.
	ProjectId pulumi.StringPtrInput
	// Name of the project to which the collection configuration belongs
	ProjectName pulumi.StringPtrInput
	// Collection configuration ID.
	RuleId pulumi.StringPtrInput
	// Collection configuration name. Please refer to the resource naming rules. Must be unique within a log topic.
	RuleName pulumi.StringPtrInput
	// Log topic ID to which the collection configuration belongs.
	TopicId pulumi.StringPtrInput
	// Name of the log topic to which the collection configuration belongs.
	TopicName pulumi.StringPtrInput
	// User-defined collection rules.
	UserDefineRule RuleUserDefineRulePtrInput
}

func (RuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleState)(nil)).Elem()
}

type ruleArgs struct {
	// Container log collection rules.
	ContainerRule *RuleContainerRule `pulumi:"containerRule"`
	// Denylist entries for collection. You can create up to 10 denylist entries. When InputType=0 or InputType=2: If Type is Path, Value represents a directory. Supports exact match and wildcard pattern matching. Wildcards supported: *, ?. The ** wildcard is not supported. If Type is File, Value represents a file name. Supports exact match and wildcard pattern matching. Wildcards supported: **, *, ?. Only one ** wildcard can be configured at most. When InputType=1: Configuring a denylist is not allowed.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	ExcludePaths []RuleExcludePath `pulumi:"excludePaths"`
	// Log extraction rules. Note: This parameter is required if LogType is set to any type other than minimalist*log or json*log.
	ExtractRule *RuleExtractRule `pulumi:"extractRule"`
	// Machine group information list.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	HostGroupInfos []RuleHostGroupInfo `pulumi:"hostGroupInfos"`
	// Collection type. 0: (Default) Host log file. 1: K8s container stdout. 2: K8s container internal log file.
	InputType *int `pulumi:"inputType"`
	// Log sample. Maximum length is 3000 characters. Log sample content must match the collection mode. Single-line full-text mode and JSON mode do not require a log sample. Other modes require a log sample, and the content must match the collection mode.
	LogSample *string `pulumi:"logSample"`
	// Collection mode. minimalist*log: (Default) Single-line full-text mode. json*log: JSON mode. delimiter*log: Delimiter mode. multiline*log: Multi-line full-text mode. fullregex_log: Full regex mode.
	LogType *string `pulumi:"logType"`
	// Collection path list. You can create up to 10 collection paths. Collection paths must be specified as absolute paths; relative paths are not supported. When InputType=0 or InputType=2, collection paths support exact match and wildcard mode. Wildcards only support **, *, and ?, but you can configure at most one ** wildcard. When InputType=1, you do not need to configure the collection path list.
	Paths []string `pulumi:"paths"`
	// Collection configuration status. 0: Running. 1: Paused.
	Pause *int `pulumi:"pause"`
	// Collection configuration name. Please refer to the resource naming rules. Must be unique within a log topic.
	RuleName string `pulumi:"ruleName"`
	// Log topic ID to which the collection configuration belongs.
	TopicId string `pulumi:"topicId"`
	// User-defined collection rules.
	UserDefineRule *RuleUserDefineRule `pulumi:"userDefineRule"`
}

// The set of arguments for constructing a Rule resource.
type RuleArgs struct {
	// Container log collection rules.
	ContainerRule RuleContainerRulePtrInput
	// Denylist entries for collection. You can create up to 10 denylist entries. When InputType=0 or InputType=2: If Type is Path, Value represents a directory. Supports exact match and wildcard pattern matching. Wildcards supported: *, ?. The ** wildcard is not supported. If Type is File, Value represents a file name. Supports exact match and wildcard pattern matching. Wildcards supported: **, *, ?. Only one ** wildcard can be configured at most. When InputType=1: Configuring a denylist is not allowed.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	ExcludePaths RuleExcludePathArrayInput
	// Log extraction rules. Note: This parameter is required if LogType is set to any type other than minimalist*log or json*log.
	ExtractRule RuleExtractRulePtrInput
	// Machine group information list.
	// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
	HostGroupInfos RuleHostGroupInfoArrayInput
	// Collection type. 0: (Default) Host log file. 1: K8s container stdout. 2: K8s container internal log file.
	InputType pulumi.IntPtrInput
	// Log sample. Maximum length is 3000 characters. Log sample content must match the collection mode. Single-line full-text mode and JSON mode do not require a log sample. Other modes require a log sample, and the content must match the collection mode.
	LogSample pulumi.StringPtrInput
	// Collection mode. minimalist*log: (Default) Single-line full-text mode. json*log: JSON mode. delimiter*log: Delimiter mode. multiline*log: Multi-line full-text mode. fullregex_log: Full regex mode.
	LogType pulumi.StringPtrInput
	// Collection path list. You can create up to 10 collection paths. Collection paths must be specified as absolute paths; relative paths are not supported. When InputType=0 or InputType=2, collection paths support exact match and wildcard mode. Wildcards only support **, *, and ?, but you can configure at most one ** wildcard. When InputType=1, you do not need to configure the collection path list.
	Paths pulumi.StringArrayInput
	// Collection configuration status. 0: Running. 1: Paused.
	Pause pulumi.IntPtrInput
	// Collection configuration name. Please refer to the resource naming rules. Must be unique within a log topic.
	RuleName pulumi.StringInput
	// Log topic ID to which the collection configuration belongs.
	TopicId pulumi.StringInput
	// User-defined collection rules.
	UserDefineRule RuleUserDefineRulePtrInput
}

func (RuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleArgs)(nil)).Elem()
}

type RuleInput interface {
	pulumi.Input

	ToRuleOutput() RuleOutput
	ToRuleOutputWithContext(ctx context.Context) RuleOutput
}

func (*Rule) ElementType() reflect.Type {
	return reflect.TypeOf((**Rule)(nil)).Elem()
}

func (i *Rule) ToRuleOutput() RuleOutput {
	return i.ToRuleOutputWithContext(context.Background())
}

func (i *Rule) ToRuleOutputWithContext(ctx context.Context) RuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleOutput)
}

// RuleArrayInput is an input type that accepts RuleArray and RuleArrayOutput values.
// You can construct a concrete instance of `RuleArrayInput` via:
//
//	RuleArray{ RuleArgs{...} }
type RuleArrayInput interface {
	pulumi.Input

	ToRuleArrayOutput() RuleArrayOutput
	ToRuleArrayOutputWithContext(context.Context) RuleArrayOutput
}

type RuleArray []RuleInput

func (RuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Rule)(nil)).Elem()
}

func (i RuleArray) ToRuleArrayOutput() RuleArrayOutput {
	return i.ToRuleArrayOutputWithContext(context.Background())
}

func (i RuleArray) ToRuleArrayOutputWithContext(ctx context.Context) RuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleArrayOutput)
}

// RuleMapInput is an input type that accepts RuleMap and RuleMapOutput values.
// You can construct a concrete instance of `RuleMapInput` via:
//
//	RuleMap{ "key": RuleArgs{...} }
type RuleMapInput interface {
	pulumi.Input

	ToRuleMapOutput() RuleMapOutput
	ToRuleMapOutputWithContext(context.Context) RuleMapOutput
}

type RuleMap map[string]RuleInput

func (RuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Rule)(nil)).Elem()
}

func (i RuleMap) ToRuleMapOutput() RuleMapOutput {
	return i.ToRuleMapOutputWithContext(context.Background())
}

func (i RuleMap) ToRuleMapOutputWithContext(ctx context.Context) RuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleMapOutput)
}

type RuleOutput struct{ *pulumi.OutputState }

func (RuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Rule)(nil)).Elem()
}

func (o RuleOutput) ToRuleOutput() RuleOutput {
	return o
}

func (o RuleOutput) ToRuleOutputWithContext(ctx context.Context) RuleOutput {
	return o
}

// Container log collection rules.
func (o RuleOutput) ContainerRule() RuleContainerRuleOutput {
	return o.ApplyT(func(v *Rule) RuleContainerRuleOutput { return v.ContainerRule }).(RuleContainerRuleOutput)
}

// Time when the collection configuration was created.
func (o RuleOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.CreateTime }).(pulumi.StringOutput)
}

// Denylist entries for collection. You can create up to 10 denylist entries. When InputType=0 or InputType=2: If Type is Path, Value represents a directory. Supports exact match and wildcard pattern matching. Wildcards supported: *, ?. The ** wildcard is not supported. If Type is File, Value represents a file name. Supports exact match and wildcard pattern matching. Wildcards supported: **, *, ?. Only one ** wildcard can be configured at most. When InputType=1: Configuring a denylist is not allowed.
// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
func (o RuleOutput) ExcludePaths() RuleExcludePathArrayOutput {
	return o.ApplyT(func(v *Rule) RuleExcludePathArrayOutput { return v.ExcludePaths }).(RuleExcludePathArrayOutput)
}

// Log extraction rules. Note: This parameter is required if LogType is set to any type other than minimalist*log or json*log.
func (o RuleOutput) ExtractRule() RuleExtractRuleOutput {
	return o.ApplyT(func(v *Rule) RuleExtractRuleOutput { return v.ExtractRule }).(RuleExtractRuleOutput)
}

// Machine group information list.
// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
func (o RuleOutput) HostGroupInfos() RuleHostGroupInfoArrayOutput {
	return o.ApplyT(func(v *Rule) RuleHostGroupInfoArrayOutput { return v.HostGroupInfos }).(RuleHostGroupInfoArrayOutput)
}

// Collection type. 0: (Default) Host log file. 1: K8s container stdout. 2: K8s container internal log file.
func (o RuleOutput) InputType() pulumi.IntOutput {
	return o.ApplyT(func(v *Rule) pulumi.IntOutput { return v.InputType }).(pulumi.IntOutput)
}

// Log sample. Maximum length is 3000 characters. Log sample content must match the collection mode. Single-line full-text mode and JSON mode do not require a log sample. Other modes require a log sample, and the content must match the collection mode.
func (o RuleOutput) LogSample() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.LogSample }).(pulumi.StringOutput)
}

// Collection mode. minimalist*log: (Default) Single-line full-text mode. json*log: JSON mode. delimiter*log: Delimiter mode. multiline*log: Multi-line full-text mode. fullregex_log: Full regex mode.
func (o RuleOutput) LogType() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.LogType }).(pulumi.StringOutput)
}

// Collection configuration modification time.
func (o RuleOutput) ModifyTime() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.ModifyTime }).(pulumi.StringOutput)
}

// Collection path list. You can create up to 10 collection paths. Collection paths must be specified as absolute paths; relative paths are not supported. When InputType=0 or InputType=2, collection paths support exact match and wildcard mode. Wildcards only support **, *, and ?, but you can configure at most one ** wildcard. When InputType=1, you do not need to configure the collection path list.
func (o RuleOutput) Paths() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringArrayOutput { return v.Paths }).(pulumi.StringArrayOutput)
}

// Collection configuration status. 0: Running. 1: Paused.
func (o RuleOutput) Pause() pulumi.IntOutput {
	return o.ApplyT(func(v *Rule) pulumi.IntOutput { return v.Pause }).(pulumi.IntOutput)
}

// ID of the project to which the collection configuration belongs.
func (o RuleOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Name of the project to which the collection configuration belongs
func (o RuleOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

// Collection configuration ID.
func (o RuleOutput) RuleId() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.RuleId }).(pulumi.StringOutput)
}

// Collection configuration name. Please refer to the resource naming rules. Must be unique within a log topic.
func (o RuleOutput) RuleName() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.RuleName }).(pulumi.StringOutput)
}

// Log topic ID to which the collection configuration belongs.
func (o RuleOutput) TopicId() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.TopicId }).(pulumi.StringOutput)
}

// Name of the log topic to which the collection configuration belongs.
func (o RuleOutput) TopicName() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.TopicName }).(pulumi.StringOutput)
}

// User-defined collection rules.
func (o RuleOutput) UserDefineRule() RuleUserDefineRuleOutput {
	return o.ApplyT(func(v *Rule) RuleUserDefineRuleOutput { return v.UserDefineRule }).(RuleUserDefineRuleOutput)
}

type RuleArrayOutput struct{ *pulumi.OutputState }

func (RuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Rule)(nil)).Elem()
}

func (o RuleArrayOutput) ToRuleArrayOutput() RuleArrayOutput {
	return o
}

func (o RuleArrayOutput) ToRuleArrayOutputWithContext(ctx context.Context) RuleArrayOutput {
	return o
}

func (o RuleArrayOutput) Index(i pulumi.IntInput) RuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Rule {
		return vs[0].([]*Rule)[vs[1].(int)]
	}).(RuleOutput)
}

type RuleMapOutput struct{ *pulumi.OutputState }

func (RuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Rule)(nil)).Elem()
}

func (o RuleMapOutput) ToRuleMapOutput() RuleMapOutput {
	return o
}

func (o RuleMapOutput) ToRuleMapOutputWithContext(ctx context.Context) RuleMapOutput {
	return o
}

func (o RuleMapOutput) MapIndex(k pulumi.StringInput) RuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Rule {
		return vs[0].(map[string]*Rule)[vs[1].(string)]
	}).(RuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RuleInput)(nil)).Elem(), &Rule{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleArrayInput)(nil)).Elem(), RuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleMapInput)(nil)).Elem(), RuleMap{})
	pulumi.RegisterOutputType(RuleOutput{})
	pulumi.RegisterOutputType(RuleArrayOutput{})
	pulumi.RegisterOutputType(RuleMapOutput{})
}
