// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.vedbm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.volcengine.volcenginecc.vedbm.outputs.GetEndpointPrivateAddresses;
import com.volcengine.volcenginecc.vedbm.outputs.GetEndpointPublicAddresses;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetEndpointResult {
    /**
     * @return Whether new read-only nodes are automatically added to this terminal
     * 
     */
    private Boolean autoAddNewNodes;
    /**
     * @return Consistency level
     * 
     */
    private String consistLevel;
    /**
     * @return Data synchronization timeout
     * 
     */
    private Integer consistTimeout;
    /**
     * @return Policy after synchronization timeout
     * 
     */
    private String consistTimeoutAction;
    /**
     * @return Description of the connection terminal
     * 
     */
    private String description;
    /**
     * @return Enable transaction splitting
     * 
     */
    private Boolean distributedTransaction;
    /**
     * @return New private network address prefix
     * 
     */
    private String domainPrefix;
    /**
     * @return ID of the created connection terminal
     * 
     */
    private String endpointId;
    /**
     * @return Connection terminal name
     * 
     */
    private String endpointName;
    /**
     * @return Connection terminal type, fixed as Custom
     * 
     */
    private String endpointType;
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    private String id;
    /**
     * @return Instance ID
     * 
     */
    private String instanceId;
    /**
     * @return Whether the primary node accepts read requests
     * 
     */
    private Boolean masterAcceptReadRequests;
    /**
     * @return Node list configured for the connection terminal
     * 
     */
    private List<String> nodeIds;
    /**
     * @return Instance access port
     * 
     */
    private String port;
    /**
     * @return Private address information
     * 
     */
    private GetEndpointPrivateAddresses privateAddresses;
    /**
     * @return Public address information
     * 
     */
    private GetEndpointPublicAddresses publicAddresses;
    /**
     * @return Terminal read/write mode
     * 
     */
    private String readWriteMode;

    private GetEndpointResult() {}
    /**
     * @return Whether new read-only nodes are automatically added to this terminal
     * 
     */
    public Boolean autoAddNewNodes() {
        return this.autoAddNewNodes;
    }
    /**
     * @return Consistency level
     * 
     */
    public String consistLevel() {
        return this.consistLevel;
    }
    /**
     * @return Data synchronization timeout
     * 
     */
    public Integer consistTimeout() {
        return this.consistTimeout;
    }
    /**
     * @return Policy after synchronization timeout
     * 
     */
    public String consistTimeoutAction() {
        return this.consistTimeoutAction;
    }
    /**
     * @return Description of the connection terminal
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Enable transaction splitting
     * 
     */
    public Boolean distributedTransaction() {
        return this.distributedTransaction;
    }
    /**
     * @return New private network address prefix
     * 
     */
    public String domainPrefix() {
        return this.domainPrefix;
    }
    /**
     * @return ID of the created connection terminal
     * 
     */
    public String endpointId() {
        return this.endpointId;
    }
    /**
     * @return Connection terminal name
     * 
     */
    public String endpointName() {
        return this.endpointName;
    }
    /**
     * @return Connection terminal type, fixed as Custom
     * 
     */
    public String endpointType() {
        return this.endpointType;
    }
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Instance ID
     * 
     */
    public String instanceId() {
        return this.instanceId;
    }
    /**
     * @return Whether the primary node accepts read requests
     * 
     */
    public Boolean masterAcceptReadRequests() {
        return this.masterAcceptReadRequests;
    }
    /**
     * @return Node list configured for the connection terminal
     * 
     */
    public List<String> nodeIds() {
        return this.nodeIds;
    }
    /**
     * @return Instance access port
     * 
     */
    public String port() {
        return this.port;
    }
    /**
     * @return Private address information
     * 
     */
    public GetEndpointPrivateAddresses privateAddresses() {
        return this.privateAddresses;
    }
    /**
     * @return Public address information
     * 
     */
    public GetEndpointPublicAddresses publicAddresses() {
        return this.publicAddresses;
    }
    /**
     * @return Terminal read/write mode
     * 
     */
    public String readWriteMode() {
        return this.readWriteMode;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetEndpointResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean autoAddNewNodes;
        private String consistLevel;
        private Integer consistTimeout;
        private String consistTimeoutAction;
        private String description;
        private Boolean distributedTransaction;
        private String domainPrefix;
        private String endpointId;
        private String endpointName;
        private String endpointType;
        private String id;
        private String instanceId;
        private Boolean masterAcceptReadRequests;
        private List<String> nodeIds;
        private String port;
        private GetEndpointPrivateAddresses privateAddresses;
        private GetEndpointPublicAddresses publicAddresses;
        private String readWriteMode;
        public Builder() {}
        public Builder(GetEndpointResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.autoAddNewNodes = defaults.autoAddNewNodes;
    	      this.consistLevel = defaults.consistLevel;
    	      this.consistTimeout = defaults.consistTimeout;
    	      this.consistTimeoutAction = defaults.consistTimeoutAction;
    	      this.description = defaults.description;
    	      this.distributedTransaction = defaults.distributedTransaction;
    	      this.domainPrefix = defaults.domainPrefix;
    	      this.endpointId = defaults.endpointId;
    	      this.endpointName = defaults.endpointName;
    	      this.endpointType = defaults.endpointType;
    	      this.id = defaults.id;
    	      this.instanceId = defaults.instanceId;
    	      this.masterAcceptReadRequests = defaults.masterAcceptReadRequests;
    	      this.nodeIds = defaults.nodeIds;
    	      this.port = defaults.port;
    	      this.privateAddresses = defaults.privateAddresses;
    	      this.publicAddresses = defaults.publicAddresses;
    	      this.readWriteMode = defaults.readWriteMode;
        }

        @CustomType.Setter
        public Builder autoAddNewNodes(Boolean autoAddNewNodes) {
            if (autoAddNewNodes == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "autoAddNewNodes");
            }
            this.autoAddNewNodes = autoAddNewNodes;
            return this;
        }
        @CustomType.Setter
        public Builder consistLevel(String consistLevel) {
            if (consistLevel == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "consistLevel");
            }
            this.consistLevel = consistLevel;
            return this;
        }
        @CustomType.Setter
        public Builder consistTimeout(Integer consistTimeout) {
            if (consistTimeout == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "consistTimeout");
            }
            this.consistTimeout = consistTimeout;
            return this;
        }
        @CustomType.Setter
        public Builder consistTimeoutAction(String consistTimeoutAction) {
            if (consistTimeoutAction == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "consistTimeoutAction");
            }
            this.consistTimeoutAction = consistTimeoutAction;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder distributedTransaction(Boolean distributedTransaction) {
            if (distributedTransaction == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "distributedTransaction");
            }
            this.distributedTransaction = distributedTransaction;
            return this;
        }
        @CustomType.Setter
        public Builder domainPrefix(String domainPrefix) {
            if (domainPrefix == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "domainPrefix");
            }
            this.domainPrefix = domainPrefix;
            return this;
        }
        @CustomType.Setter
        public Builder endpointId(String endpointId) {
            if (endpointId == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "endpointId");
            }
            this.endpointId = endpointId;
            return this;
        }
        @CustomType.Setter
        public Builder endpointName(String endpointName) {
            if (endpointName == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "endpointName");
            }
            this.endpointName = endpointName;
            return this;
        }
        @CustomType.Setter
        public Builder endpointType(String endpointType) {
            if (endpointType == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "endpointType");
            }
            this.endpointType = endpointType;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder instanceId(String instanceId) {
            if (instanceId == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "instanceId");
            }
            this.instanceId = instanceId;
            return this;
        }
        @CustomType.Setter
        public Builder masterAcceptReadRequests(Boolean masterAcceptReadRequests) {
            if (masterAcceptReadRequests == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "masterAcceptReadRequests");
            }
            this.masterAcceptReadRequests = masterAcceptReadRequests;
            return this;
        }
        @CustomType.Setter
        public Builder nodeIds(List<String> nodeIds) {
            if (nodeIds == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "nodeIds");
            }
            this.nodeIds = nodeIds;
            return this;
        }
        public Builder nodeIds(String... nodeIds) {
            return nodeIds(List.of(nodeIds));
        }
        @CustomType.Setter
        public Builder port(String port) {
            if (port == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "port");
            }
            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder privateAddresses(GetEndpointPrivateAddresses privateAddresses) {
            if (privateAddresses == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "privateAddresses");
            }
            this.privateAddresses = privateAddresses;
            return this;
        }
        @CustomType.Setter
        public Builder publicAddresses(GetEndpointPublicAddresses publicAddresses) {
            if (publicAddresses == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "publicAddresses");
            }
            this.publicAddresses = publicAddresses;
            return this;
        }
        @CustomType.Setter
        public Builder readWriteMode(String readWriteMode) {
            if (readWriteMode == null) {
              throw new MissingRequiredPropertyException("GetEndpointResult", "readWriteMode");
            }
            this.readWriteMode = readWriteMode;
            return this;
        }
        public GetEndpointResult build() {
            final var _resultValue = new GetEndpointResult();
            _resultValue.autoAddNewNodes = autoAddNewNodes;
            _resultValue.consistLevel = consistLevel;
            _resultValue.consistTimeout = consistTimeout;
            _resultValue.consistTimeoutAction = consistTimeoutAction;
            _resultValue.description = description;
            _resultValue.distributedTransaction = distributedTransaction;
            _resultValue.domainPrefix = domainPrefix;
            _resultValue.endpointId = endpointId;
            _resultValue.endpointName = endpointName;
            _resultValue.endpointType = endpointType;
            _resultValue.id = id;
            _resultValue.instanceId = instanceId;
            _resultValue.masterAcceptReadRequests = masterAcceptReadRequests;
            _resultValue.nodeIds = nodeIds;
            _resultValue.port = port;
            _resultValue.privateAddresses = privateAddresses;
            _resultValue.publicAddresses = publicAddresses;
            _resultValue.readWriteMode = readWriteMode;
            return _resultValue;
        }
    }
}
