// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.rdspostgresql.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.volcengine.volcenginecc.rdspostgresql.inputs.InstanceRestoreToExistedInstanceDatabaseArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InstanceRestoreToExistedInstanceArgs extends com.pulumi.resources.ResourceArgs {

    public static final InstanceRestoreToExistedInstanceArgs Empty = new InstanceRestoreToExistedInstanceArgs();

    /**
     * Backup set ID
     * 
     */
    @Import(name="backupId")
    private @Nullable Output<String> backupId;

    /**
     * @return Backup set ID
     * 
     */
    public Optional<Output<String>> backupId() {
        return Optional.ofNullable(this.backupId);
    }

    @Import(name="databases")
    private @Nullable Output<List<InstanceRestoreToExistedInstanceDatabaseArgs>> databases;

    public Optional<Output<List<InstanceRestoreToExistedInstanceDatabaseArgs>>> databases() {
        return Optional.ofNullable(this.databases);
    }

    /**
     * Source instance ID
     * 
     */
    @Import(name="sourceDbInstanceId")
    private @Nullable Output<String> sourceDbInstanceId;

    /**
     * @return Source instance ID
     * 
     */
    public Optional<Output<String>> sourceDbInstanceId() {
        return Optional.ofNullable(this.sourceDbInstanceId);
    }

    /**
     * Database account for the target instance
     * 
     */
    @Import(name="targetDbInstanceAccount")
    private @Nullable Output<String> targetDbInstanceAccount;

    /**
     * @return Database account for the target instance
     * 
     */
    public Optional<Output<String>> targetDbInstanceAccount() {
        return Optional.ofNullable(this.targetDbInstanceAccount);
    }

    private InstanceRestoreToExistedInstanceArgs() {}

    private InstanceRestoreToExistedInstanceArgs(InstanceRestoreToExistedInstanceArgs $) {
        this.backupId = $.backupId;
        this.databases = $.databases;
        this.sourceDbInstanceId = $.sourceDbInstanceId;
        this.targetDbInstanceAccount = $.targetDbInstanceAccount;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InstanceRestoreToExistedInstanceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InstanceRestoreToExistedInstanceArgs $;

        public Builder() {
            $ = new InstanceRestoreToExistedInstanceArgs();
        }

        public Builder(InstanceRestoreToExistedInstanceArgs defaults) {
            $ = new InstanceRestoreToExistedInstanceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param backupId Backup set ID
         * 
         * @return builder
         * 
         */
        public Builder backupId(@Nullable Output<String> backupId) {
            $.backupId = backupId;
            return this;
        }

        /**
         * @param backupId Backup set ID
         * 
         * @return builder
         * 
         */
        public Builder backupId(String backupId) {
            return backupId(Output.of(backupId));
        }

        public Builder databases(@Nullable Output<List<InstanceRestoreToExistedInstanceDatabaseArgs>> databases) {
            $.databases = databases;
            return this;
        }

        public Builder databases(List<InstanceRestoreToExistedInstanceDatabaseArgs> databases) {
            return databases(Output.of(databases));
        }

        public Builder databases(InstanceRestoreToExistedInstanceDatabaseArgs... databases) {
            return databases(List.of(databases));
        }

        /**
         * @param sourceDbInstanceId Source instance ID
         * 
         * @return builder
         * 
         */
        public Builder sourceDbInstanceId(@Nullable Output<String> sourceDbInstanceId) {
            $.sourceDbInstanceId = sourceDbInstanceId;
            return this;
        }

        /**
         * @param sourceDbInstanceId Source instance ID
         * 
         * @return builder
         * 
         */
        public Builder sourceDbInstanceId(String sourceDbInstanceId) {
            return sourceDbInstanceId(Output.of(sourceDbInstanceId));
        }

        /**
         * @param targetDbInstanceAccount Database account for the target instance
         * 
         * @return builder
         * 
         */
        public Builder targetDbInstanceAccount(@Nullable Output<String> targetDbInstanceAccount) {
            $.targetDbInstanceAccount = targetDbInstanceAccount;
            return this;
        }

        /**
         * @param targetDbInstanceAccount Database account for the target instance
         * 
         * @return builder
         * 
         */
        public Builder targetDbInstanceAccount(String targetDbInstanceAccount) {
            return targetDbInstanceAccount(Output.of(targetDbInstanceAccount));
        }

        public InstanceRestoreToExistedInstanceArgs build() {
            return $;
        }
    }

}
