// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package autoscaling

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcenginecc/sdk/go/volcenginecc/internal"
)

// Plural Data Source schema for Volcengine::AutoScaling::ScalingGroup
func GetScalingGroups(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetScalingGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetScalingGroupsResult
	err := ctx.Invoke("volcenginecc:autoscaling/getScalingGroups:getScalingGroups", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getScalingGroups.
type GetScalingGroupsResult struct {
	// Uniquely identifies the data source.
	Id string `pulumi:"id"`
	// Set of Resource Identifiers.
	Ids []string `pulumi:"ids"`
}

func GetScalingGroupsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetScalingGroupsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetScalingGroupsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("volcenginecc:autoscaling/getScalingGroups:getScalingGroups", nil, GetScalingGroupsResultOutput{}, options).(GetScalingGroupsResultOutput), nil
	}).(GetScalingGroupsResultOutput)
}

// A collection of values returned by getScalingGroups.
type GetScalingGroupsResultOutput struct{ *pulumi.OutputState }

func (GetScalingGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetScalingGroupsResult)(nil)).Elem()
}

func (o GetScalingGroupsResultOutput) ToGetScalingGroupsResultOutput() GetScalingGroupsResultOutput {
	return o
}

func (o GetScalingGroupsResultOutput) ToGetScalingGroupsResultOutputWithContext(ctx context.Context) GetScalingGroupsResultOutput {
	return o
}

// Uniquely identifies the data source.
func (o GetScalingGroupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Set of Resource Identifiers.
func (o GetScalingGroupsResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetScalingGroupsResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetScalingGroupsResultOutput{})
}
