// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Vefaas.Inputs
{

    public sealed class SandboxInstanceTosMountConfigTosMountPointGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// 沙箱实例挂载的 TOS 远端目录。
        /// </summary>
        [Input("bucketPath")]
        public Input<string>? BucketPath { get; set; }

        /// <summary>
        /// 沙箱实例挂载的 TOS 存储桶本地目录。该目录为沙箱应用已配置的 TOS 存储挂载的本地目录时，系统根据指定的本地目录，修改与之对应的 TOS BucketPath。
        /// </summary>
        [Input("localMountPath")]
        public Input<string>? LocalMountPath { get; set; }

        public SandboxInstanceTosMountConfigTosMountPointGetArgs()
        {
        }
        public static new SandboxInstanceTosMountConfigTosMountPointGetArgs Empty => new SandboxInstanceTosMountConfigTosMountPointGetArgs();
    }
}
