// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.vke.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterPodsConfigFlannelConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterPodsConfigFlannelConfigArgs Empty = new ClusterPodsConfigFlannelConfigArgs();

    /**
     * Flannel 模型容器网络的单节点 Pod 实例数量上限，取值：64（默认值）、16、32、128、256。
     * 
     */
    @Import(name="maxPodsPerNode")
    private @Nullable Output<Integer> maxPodsPerNode;

    /**
     * @return Flannel 模型容器网络的单节点 Pod 实例数量上限，取值：64（默认值）、16、32、128、256。
     * 
     */
    public Optional<Output<Integer>> maxPodsPerNode() {
        return Optional.ofNullable(this.maxPodsPerNode);
    }

    /**
     * Flannel 容器网络的 Pod CIDR。
     * 
     */
    @Import(name="podCidrs")
    private @Nullable Output<List<String>> podCidrs;

    /**
     * @return Flannel 容器网络的 Pod CIDR。
     * 
     */
    public Optional<Output<List<String>>> podCidrs() {
        return Optional.ofNullable(this.podCidrs);
    }

    private ClusterPodsConfigFlannelConfigArgs() {}

    private ClusterPodsConfigFlannelConfigArgs(ClusterPodsConfigFlannelConfigArgs $) {
        this.maxPodsPerNode = $.maxPodsPerNode;
        this.podCidrs = $.podCidrs;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterPodsConfigFlannelConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterPodsConfigFlannelConfigArgs $;

        public Builder() {
            $ = new ClusterPodsConfigFlannelConfigArgs();
        }

        public Builder(ClusterPodsConfigFlannelConfigArgs defaults) {
            $ = new ClusterPodsConfigFlannelConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param maxPodsPerNode Flannel 模型容器网络的单节点 Pod 实例数量上限，取值：64（默认值）、16、32、128、256。
         * 
         * @return builder
         * 
         */
        public Builder maxPodsPerNode(@Nullable Output<Integer> maxPodsPerNode) {
            $.maxPodsPerNode = maxPodsPerNode;
            return this;
        }

        /**
         * @param maxPodsPerNode Flannel 模型容器网络的单节点 Pod 实例数量上限，取值：64（默认值）、16、32、128、256。
         * 
         * @return builder
         * 
         */
        public Builder maxPodsPerNode(Integer maxPodsPerNode) {
            return maxPodsPerNode(Output.of(maxPodsPerNode));
        }

        /**
         * @param podCidrs Flannel 容器网络的 Pod CIDR。
         * 
         * @return builder
         * 
         */
        public Builder podCidrs(@Nullable Output<List<String>> podCidrs) {
            $.podCidrs = podCidrs;
            return this;
        }

        /**
         * @param podCidrs Flannel 容器网络的 Pod CIDR。
         * 
         * @return builder
         * 
         */
        public Builder podCidrs(List<String> podCidrs) {
            return podCidrs(Output.of(podCidrs));
        }

        /**
         * @param podCidrs Flannel 容器网络的 Pod CIDR。
         * 
         * @return builder
         * 
         */
        public Builder podCidrs(String... podCidrs) {
            return podCidrs(List.of(podCidrs));
        }

        public ClusterPodsConfigFlannelConfigArgs build() {
            return $;
        }
    }

}
