// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.cbr.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.volcengine.volcenginecc.cbr.inputs.BackupPlanPolicyArgs;
import com.volcengine.volcenginecc.cbr.inputs.BackupPlanResourceListArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BackupPlanState extends com.pulumi.resources.ResourceArgs {

    public static final BackupPlanState Empty = new BackupPlanState();

    /**
     * Account ID that created this plan
     * 
     */
    @Import(name="accountId")
    private @Nullable Output<String> accountId;

    /**
     * @return Account ID that created this plan
     * 
     */
    public Optional<Output<String>> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    /**
     * Creation Time
     * 
     */
    @Import(name="createdTime")
    private @Nullable Output<String> createdTime;

    /**
     * @return Creation Time
     * 
     */
    public Optional<Output<String>> createdTime() {
        return Optional.ofNullable(this.createdTime);
    }

    /**
     * Backup Plan Name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Backup Plan Name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Backup Plan ID
     * 
     */
    @Import(name="planId")
    private @Nullable Output<String> planId;

    /**
     * @return Backup Plan ID
     * 
     */
    public Optional<Output<String>> planId() {
        return Optional.ofNullable(this.planId);
    }

    /**
     * Backup Policy
     * 
     */
    @Import(name="policy")
    private @Nullable Output<BackupPlanPolicyArgs> policy;

    /**
     * @return Backup Policy
     * 
     */
    public Optional<Output<BackupPlanPolicyArgs>> policy() {
        return Optional.ofNullable(this.policy);
    }

    /**
     * Backup Policy ID
     * 
     */
    @Import(name="policyId")
    private @Nullable Output<String> policyId;

    /**
     * @return Backup Policy ID
     * 
     */
    public Optional<Output<String>> policyId() {
        return Optional.ofNullable(this.policyId);
    }

    @Import(name="resourceLists")
    private @Nullable Output<List<BackupPlanResourceListArgs>> resourceLists;

    public Optional<Output<List<BackupPlanResourceListArgs>>> resourceLists() {
        return Optional.ofNullable(this.resourceLists);
    }

    /**
     * Update Time
     * 
     */
    @Import(name="updatedTime")
    private @Nullable Output<String> updatedTime;

    /**
     * @return Update Time
     * 
     */
    public Optional<Output<String>> updatedTime() {
        return Optional.ofNullable(this.updatedTime);
    }

    private BackupPlanState() {}

    private BackupPlanState(BackupPlanState $) {
        this.accountId = $.accountId;
        this.createdTime = $.createdTime;
        this.name = $.name;
        this.planId = $.planId;
        this.policy = $.policy;
        this.policyId = $.policyId;
        this.resourceLists = $.resourceLists;
        this.updatedTime = $.updatedTime;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BackupPlanState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BackupPlanState $;

        public Builder() {
            $ = new BackupPlanState();
        }

        public Builder(BackupPlanState defaults) {
            $ = new BackupPlanState(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Account ID that created this plan
         * 
         * @return builder
         * 
         */
        public Builder accountId(@Nullable Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Account ID that created this plan
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        /**
         * @param createdTime Creation Time
         * 
         * @return builder
         * 
         */
        public Builder createdTime(@Nullable Output<String> createdTime) {
            $.createdTime = createdTime;
            return this;
        }

        /**
         * @param createdTime Creation Time
         * 
         * @return builder
         * 
         */
        public Builder createdTime(String createdTime) {
            return createdTime(Output.of(createdTime));
        }

        /**
         * @param name Backup Plan Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Backup Plan Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param planId Backup Plan ID
         * 
         * @return builder
         * 
         */
        public Builder planId(@Nullable Output<String> planId) {
            $.planId = planId;
            return this;
        }

        /**
         * @param planId Backup Plan ID
         * 
         * @return builder
         * 
         */
        public Builder planId(String planId) {
            return planId(Output.of(planId));
        }

        /**
         * @param policy Backup Policy
         * 
         * @return builder
         * 
         */
        public Builder policy(@Nullable Output<BackupPlanPolicyArgs> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy Backup Policy
         * 
         * @return builder
         * 
         */
        public Builder policy(BackupPlanPolicyArgs policy) {
            return policy(Output.of(policy));
        }

        /**
         * @param policyId Backup Policy ID
         * 
         * @return builder
         * 
         */
        public Builder policyId(@Nullable Output<String> policyId) {
            $.policyId = policyId;
            return this;
        }

        /**
         * @param policyId Backup Policy ID
         * 
         * @return builder
         * 
         */
        public Builder policyId(String policyId) {
            return policyId(Output.of(policyId));
        }

        public Builder resourceLists(@Nullable Output<List<BackupPlanResourceListArgs>> resourceLists) {
            $.resourceLists = resourceLists;
            return this;
        }

        public Builder resourceLists(List<BackupPlanResourceListArgs> resourceLists) {
            return resourceLists(Output.of(resourceLists));
        }

        public Builder resourceLists(BackupPlanResourceListArgs... resourceLists) {
            return resourceLists(List.of(resourceLists));
        }

        /**
         * @param updatedTime Update Time
         * 
         * @return builder
         * 
         */
        public Builder updatedTime(@Nullable Output<String> updatedTime) {
            $.updatedTime = updatedTime;
            return this;
        }

        /**
         * @param updatedTime Update Time
         * 
         * @return builder
         * 
         */
        public Builder updatedTime(String updatedTime) {
            return updatedTime(Output.of(updatedTime));
        }

        public BackupPlanState build() {
            return $;
        }
    }

}
