// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.apig;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.volcengine.volcenginecc.apig.inputs.UpstreamCircuitBreakingSettingsArgs;
import com.volcengine.volcenginecc.apig.inputs.UpstreamLoadBalancerSettingsArgs;
import com.volcengine.volcenginecc.apig.inputs.UpstreamTlsSettingsArgs;
import com.volcengine.volcenginecc.apig.inputs.UpstreamUpstreamSpecArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UpstreamArgs extends com.pulumi.resources.ResourceArgs {

    public static final UpstreamArgs Empty = new UpstreamArgs();

    /**
     * 服务熔断配置。
     * 
     */
    @Import(name="circuitBreakingSettings")
    private @Nullable Output<UpstreamCircuitBreakingSettingsArgs> circuitBreakingSettings;

    /**
     * @return 服务熔断配置。
     * 
     */
    public Optional<Output<UpstreamCircuitBreakingSettingsArgs>> circuitBreakingSettings() {
        return Optional.ofNullable(this.circuitBreakingSettings);
    }

    /**
     * 备注。
     * 
     */
    @Import(name="comments")
    private @Nullable Output<String> comments;

    /**
     * @return 备注。
     * 
     */
    public Optional<Output<String>> comments() {
        return Optional.ofNullable(this.comments);
    }

    /**
     * 网关实例ID。
     * 
     */
    @Import(name="gatewayId", required=true)
    private Output<String> gatewayId;

    /**
     * @return 网关实例ID。
     * 
     */
    public Output<String> gatewayId() {
        return this.gatewayId;
    }

    /**
     * 负载均衡配置。
     * 
     */
    @Import(name="loadBalancerSettings")
    private @Nullable Output<UpstreamLoadBalancerSettingsArgs> loadBalancerSettings;

    /**
     * @return 负载均衡配置。
     * 
     */
    public Optional<Output<UpstreamLoadBalancerSettingsArgs>> loadBalancerSettings() {
        return Optional.ofNullable(this.loadBalancerSettings);
    }

    /**
     * Upstream名称。
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Upstream名称。
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * 协议，取值：HTTP：HTTP/1.1。HTTP2：HTTP/2。GRPC：GRPC。
     * 
     */
    @Import(name="protocol")
    private @Nullable Output<String> protocol;

    /**
     * @return 协议，取值：HTTP：HTTP/1.1。HTTP2：HTTP/2。GRPC：GRPC。
     * 
     */
    public Optional<Output<String>> protocol() {
        return Optional.ofNullable(this.protocol);
    }

    /**
     * Upstream来源类型，取值：VeFaas：函数服务。ECS：云服务器。K8S：容器服务。Nacos：注册中心。AIProvider：AI模型代理。
     * 
     */
    @Import(name="sourceType", required=true)
    private Output<String> sourceType;

    /**
     * @return Upstream来源类型，取值：VeFaas：函数服务。ECS：云服务器。K8S：容器服务。Nacos：注册中心。AIProvider：AI模型代理。
     * 
     */
    public Output<String> sourceType() {
        return this.sourceType;
    }

    /**
     * TLS配置。
     * 
     */
    @Import(name="tlsSettings")
    private @Nullable Output<UpstreamTlsSettingsArgs> tlsSettings;

    /**
     * @return TLS配置。
     * 
     */
    public Optional<Output<UpstreamTlsSettingsArgs>> tlsSettings() {
        return Optional.ofNullable(this.tlsSettings);
    }

    /**
     * Upstream配置。
     * 
     */
    @Import(name="upstreamSpec", required=true)
    private Output<UpstreamUpstreamSpecArgs> upstreamSpec;

    /**
     * @return Upstream配置。
     * 
     */
    public Output<UpstreamUpstreamSpecArgs> upstreamSpec() {
        return this.upstreamSpec;
    }

    private UpstreamArgs() {}

    private UpstreamArgs(UpstreamArgs $) {
        this.circuitBreakingSettings = $.circuitBreakingSettings;
        this.comments = $.comments;
        this.gatewayId = $.gatewayId;
        this.loadBalancerSettings = $.loadBalancerSettings;
        this.name = $.name;
        this.protocol = $.protocol;
        this.sourceType = $.sourceType;
        this.tlsSettings = $.tlsSettings;
        this.upstreamSpec = $.upstreamSpec;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UpstreamArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UpstreamArgs $;

        public Builder() {
            $ = new UpstreamArgs();
        }

        public Builder(UpstreamArgs defaults) {
            $ = new UpstreamArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param circuitBreakingSettings 服务熔断配置。
         * 
         * @return builder
         * 
         */
        public Builder circuitBreakingSettings(@Nullable Output<UpstreamCircuitBreakingSettingsArgs> circuitBreakingSettings) {
            $.circuitBreakingSettings = circuitBreakingSettings;
            return this;
        }

        /**
         * @param circuitBreakingSettings 服务熔断配置。
         * 
         * @return builder
         * 
         */
        public Builder circuitBreakingSettings(UpstreamCircuitBreakingSettingsArgs circuitBreakingSettings) {
            return circuitBreakingSettings(Output.of(circuitBreakingSettings));
        }

        /**
         * @param comments 备注。
         * 
         * @return builder
         * 
         */
        public Builder comments(@Nullable Output<String> comments) {
            $.comments = comments;
            return this;
        }

        /**
         * @param comments 备注。
         * 
         * @return builder
         * 
         */
        public Builder comments(String comments) {
            return comments(Output.of(comments));
        }

        /**
         * @param gatewayId 网关实例ID。
         * 
         * @return builder
         * 
         */
        public Builder gatewayId(Output<String> gatewayId) {
            $.gatewayId = gatewayId;
            return this;
        }

        /**
         * @param gatewayId 网关实例ID。
         * 
         * @return builder
         * 
         */
        public Builder gatewayId(String gatewayId) {
            return gatewayId(Output.of(gatewayId));
        }

        /**
         * @param loadBalancerSettings 负载均衡配置。
         * 
         * @return builder
         * 
         */
        public Builder loadBalancerSettings(@Nullable Output<UpstreamLoadBalancerSettingsArgs> loadBalancerSettings) {
            $.loadBalancerSettings = loadBalancerSettings;
            return this;
        }

        /**
         * @param loadBalancerSettings 负载均衡配置。
         * 
         * @return builder
         * 
         */
        public Builder loadBalancerSettings(UpstreamLoadBalancerSettingsArgs loadBalancerSettings) {
            return loadBalancerSettings(Output.of(loadBalancerSettings));
        }

        /**
         * @param name Upstream名称。
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Upstream名称。
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param protocol 协议，取值：HTTP：HTTP/1.1。HTTP2：HTTP/2。GRPC：GRPC。
         * 
         * @return builder
         * 
         */
        public Builder protocol(@Nullable Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        /**
         * @param protocol 协议，取值：HTTP：HTTP/1.1。HTTP2：HTTP/2。GRPC：GRPC。
         * 
         * @return builder
         * 
         */
        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        /**
         * @param sourceType Upstream来源类型，取值：VeFaas：函数服务。ECS：云服务器。K8S：容器服务。Nacos：注册中心。AIProvider：AI模型代理。
         * 
         * @return builder
         * 
         */
        public Builder sourceType(Output<String> sourceType) {
            $.sourceType = sourceType;
            return this;
        }

        /**
         * @param sourceType Upstream来源类型，取值：VeFaas：函数服务。ECS：云服务器。K8S：容器服务。Nacos：注册中心。AIProvider：AI模型代理。
         * 
         * @return builder
         * 
         */
        public Builder sourceType(String sourceType) {
            return sourceType(Output.of(sourceType));
        }

        /**
         * @param tlsSettings TLS配置。
         * 
         * @return builder
         * 
         */
        public Builder tlsSettings(@Nullable Output<UpstreamTlsSettingsArgs> tlsSettings) {
            $.tlsSettings = tlsSettings;
            return this;
        }

        /**
         * @param tlsSettings TLS配置。
         * 
         * @return builder
         * 
         */
        public Builder tlsSettings(UpstreamTlsSettingsArgs tlsSettings) {
            return tlsSettings(Output.of(tlsSettings));
        }

        /**
         * @param upstreamSpec Upstream配置。
         * 
         * @return builder
         * 
         */
        public Builder upstreamSpec(Output<UpstreamUpstreamSpecArgs> upstreamSpec) {
            $.upstreamSpec = upstreamSpec;
            return this;
        }

        /**
         * @param upstreamSpec Upstream配置。
         * 
         * @return builder
         * 
         */
        public Builder upstreamSpec(UpstreamUpstreamSpecArgs upstreamSpec) {
            return upstreamSpec(Output.of(upstreamSpec));
        }

        public UpstreamArgs build() {
            if ($.gatewayId == null) {
                throw new MissingRequiredPropertyException("UpstreamArgs", "gatewayId");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("UpstreamArgs", "name");
            }
            if ($.sourceType == null) {
                throw new MissingRequiredPropertyException("UpstreamArgs", "sourceType");
            }
            if ($.upstreamSpec == null) {
                throw new MissingRequiredPropertyException("UpstreamArgs", "upstreamSpec");
            }
            return $;
        }
    }

}
