// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.vpc.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RouteTableCustomRouteEntryArgs extends com.pulumi.resources.ResourceArgs {

    public static final RouteTableCustomRouteEntryArgs Empty = new RouteTableCustomRouteEntryArgs();

    /**
     * Route Entry Description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Route Entry Description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Destination CIDR of the route entry
     * 
     */
    @Import(name="destinationCidrBlock")
    private @Nullable Output<String> destinationCidrBlock;

    /**
     * @return Destination CIDR of the route entry
     * 
     */
    public Optional<Output<String>> destinationCidrBlock() {
        return Optional.ofNullable(this.destinationCidrBlock);
    }

    /**
     * Prefix List ID
     * 
     */
    @Import(name="destinationPrefixListId")
    private @Nullable Output<String> destinationPrefixListId;

    /**
     * @return Prefix List ID
     * 
     */
    public Optional<Output<String>> destinationPrefixListId() {
        return Optional.ofNullable(this.destinationPrefixListId);
    }

    /**
     * Next Hop Resource ID
     * 
     */
    @Import(name="nextHopId")
    private @Nullable Output<String> nextHopId;

    /**
     * @return Next Hop Resource ID
     * 
     */
    public Optional<Output<String>> nextHopId() {
        return Optional.ofNullable(this.nextHopId);
    }

    /**
     * Name of the next hop resource for the route entry
     * 
     */
    @Import(name="nextHopName")
    private @Nullable Output<String> nextHopName;

    /**
     * @return Name of the next hop resource for the route entry
     * 
     */
    public Optional<Output<String>> nextHopName() {
        return Optional.ofNullable(this.nextHopName);
    }

    /**
     * Next hop type for custom route entry. 1. Instance: ECS instance 2. HaVip: High availability virtual IP 3. NetworkInterface: Secondary network interface 4. NatGW: NAT gateway 5. VpnGW: VPN gateway 6. TransitRouter: Transit router 7. IPv6GW: IPv6 gateway 8. CloudConnector: Cloud connector 9. GWLBEndpoint: Gateway load balancer endpoint
     * 
     */
    @Import(name="nextHopType")
    private @Nullable Output<String> nextHopType;

    /**
     * @return Next hop type for custom route entry. 1. Instance: ECS instance 2. HaVip: High availability virtual IP 3. NetworkInterface: Secondary network interface 4. NatGW: NAT gateway 5. VpnGW: VPN gateway 6. TransitRouter: Transit router 7. IPv6GW: IPv6 gateway 8. CloudConnector: Cloud connector 9. GWLBEndpoint: Gateway load balancer endpoint
     * 
     */
    public Optional<Output<String>> nextHopType() {
        return Optional.ofNullable(this.nextHopType);
    }

    /**
     * Route Entry Name
     * 
     */
    @Import(name="routeEntryName")
    private @Nullable Output<String> routeEntryName;

    /**
     * @return Route Entry Name
     * 
     */
    public Optional<Output<String>> routeEntryName() {
        return Optional.ofNullable(this.routeEntryName);
    }

    private RouteTableCustomRouteEntryArgs() {}

    private RouteTableCustomRouteEntryArgs(RouteTableCustomRouteEntryArgs $) {
        this.description = $.description;
        this.destinationCidrBlock = $.destinationCidrBlock;
        this.destinationPrefixListId = $.destinationPrefixListId;
        this.nextHopId = $.nextHopId;
        this.nextHopName = $.nextHopName;
        this.nextHopType = $.nextHopType;
        this.routeEntryName = $.routeEntryName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RouteTableCustomRouteEntryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RouteTableCustomRouteEntryArgs $;

        public Builder() {
            $ = new RouteTableCustomRouteEntryArgs();
        }

        public Builder(RouteTableCustomRouteEntryArgs defaults) {
            $ = new RouteTableCustomRouteEntryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Route Entry Description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Route Entry Description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param destinationCidrBlock Destination CIDR of the route entry
         * 
         * @return builder
         * 
         */
        public Builder destinationCidrBlock(@Nullable Output<String> destinationCidrBlock) {
            $.destinationCidrBlock = destinationCidrBlock;
            return this;
        }

        /**
         * @param destinationCidrBlock Destination CIDR of the route entry
         * 
         * @return builder
         * 
         */
        public Builder destinationCidrBlock(String destinationCidrBlock) {
            return destinationCidrBlock(Output.of(destinationCidrBlock));
        }

        /**
         * @param destinationPrefixListId Prefix List ID
         * 
         * @return builder
         * 
         */
        public Builder destinationPrefixListId(@Nullable Output<String> destinationPrefixListId) {
            $.destinationPrefixListId = destinationPrefixListId;
            return this;
        }

        /**
         * @param destinationPrefixListId Prefix List ID
         * 
         * @return builder
         * 
         */
        public Builder destinationPrefixListId(String destinationPrefixListId) {
            return destinationPrefixListId(Output.of(destinationPrefixListId));
        }

        /**
         * @param nextHopId Next Hop Resource ID
         * 
         * @return builder
         * 
         */
        public Builder nextHopId(@Nullable Output<String> nextHopId) {
            $.nextHopId = nextHopId;
            return this;
        }

        /**
         * @param nextHopId Next Hop Resource ID
         * 
         * @return builder
         * 
         */
        public Builder nextHopId(String nextHopId) {
            return nextHopId(Output.of(nextHopId));
        }

        /**
         * @param nextHopName Name of the next hop resource for the route entry
         * 
         * @return builder
         * 
         */
        public Builder nextHopName(@Nullable Output<String> nextHopName) {
            $.nextHopName = nextHopName;
            return this;
        }

        /**
         * @param nextHopName Name of the next hop resource for the route entry
         * 
         * @return builder
         * 
         */
        public Builder nextHopName(String nextHopName) {
            return nextHopName(Output.of(nextHopName));
        }

        /**
         * @param nextHopType Next hop type for custom route entry. 1. Instance: ECS instance 2. HaVip: High availability virtual IP 3. NetworkInterface: Secondary network interface 4. NatGW: NAT gateway 5. VpnGW: VPN gateway 6. TransitRouter: Transit router 7. IPv6GW: IPv6 gateway 8. CloudConnector: Cloud connector 9. GWLBEndpoint: Gateway load balancer endpoint
         * 
         * @return builder
         * 
         */
        public Builder nextHopType(@Nullable Output<String> nextHopType) {
            $.nextHopType = nextHopType;
            return this;
        }

        /**
         * @param nextHopType Next hop type for custom route entry. 1. Instance: ECS instance 2. HaVip: High availability virtual IP 3. NetworkInterface: Secondary network interface 4. NatGW: NAT gateway 5. VpnGW: VPN gateway 6. TransitRouter: Transit router 7. IPv6GW: IPv6 gateway 8. CloudConnector: Cloud connector 9. GWLBEndpoint: Gateway load balancer endpoint
         * 
         * @return builder
         * 
         */
        public Builder nextHopType(String nextHopType) {
            return nextHopType(Output.of(nextHopType));
        }

        /**
         * @param routeEntryName Route Entry Name
         * 
         * @return builder
         * 
         */
        public Builder routeEntryName(@Nullable Output<String> routeEntryName) {
            $.routeEntryName = routeEntryName;
            return this;
        }

        /**
         * @param routeEntryName Route Entry Name
         * 
         * @return builder
         * 
         */
        public Builder routeEntryName(String routeEntryName) {
            return routeEntryName(Output.of(routeEntryName));
        }

        public RouteTableCustomRouteEntryArgs build() {
            return $;
        }
    }

}
