// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.veenedge.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.util.Objects;

@CustomType
public final class GetVeenAdvancedConfiguration {
    /**
     * @return Whether deletion protection is enabled for the edge instance. true: enabled. false: not enabled.
     * 
     */
    private Boolean deleteProtection;

    private GetVeenAdvancedConfiguration() {}
    /**
     * @return Whether deletion protection is enabled for the edge instance. true: enabled. false: not enabled.
     * 
     */
    public Boolean deleteProtection() {
        return this.deleteProtection;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetVeenAdvancedConfiguration defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean deleteProtection;
        public Builder() {}
        public Builder(GetVeenAdvancedConfiguration defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.deleteProtection = defaults.deleteProtection;
        }

        @CustomType.Setter
        public Builder deleteProtection(Boolean deleteProtection) {
            if (deleteProtection == null) {
              throw new MissingRequiredPropertyException("GetVeenAdvancedConfiguration", "deleteProtection");
            }
            this.deleteProtection = deleteProtection;
            return this;
        }
        public GetVeenAdvancedConfiguration build() {
            final var _resultValue = new GetVeenAdvancedConfiguration();
            _resultValue.deleteProtection = deleteProtection;
            return _resultValue;
        }
    }
}
