// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Tls.Outputs
{

    [OutputType]
    public sealed class GetAlarmNotifyGroupReceiverGeneralWebhookHeaderResult
    {
        /// <summary>
        /// Custom request header key.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Custom request header value.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetAlarmNotifyGroupReceiverGeneralWebhookHeaderResult(
            string key,

            string value)
        {
            Key = key;
            Value = value;
        }
    }
}
