// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Apig
{
    public static class GetGateway
    {
        /// <summary>
        /// Data Source schema for Volcengine::APIG::Gateway
        /// </summary>
        public static Task<GetGatewayResult> InvokeAsync(GetGatewayArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGatewayResult>("volcenginecc:apig/getGateway:getGateway", args ?? new GetGatewayArgs(), options.WithDefaults());

        /// <summary>
        /// Data Source schema for Volcengine::APIG::Gateway
        /// </summary>
        public static Output<GetGatewayResult> Invoke(GetGatewayInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGatewayResult>("volcenginecc:apig/getGateway:getGateway", args ?? new GetGatewayInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Data Source schema for Volcengine::APIG::Gateway
        /// </summary>
        public static Output<GetGatewayResult> Invoke(GetGatewayInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetGatewayResult>("volcenginecc:apig/getGateway:getGateway", args ?? new GetGatewayInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGatewayArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Uniquely identifies the resource.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetGatewayArgs()
        {
        }
        public static new GetGatewayArgs Empty => new GetGatewayArgs();
    }

    public sealed class GetGatewayInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Uniquely identifies the resource.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetGatewayInvokeArgs()
        {
        }
        public static new GetGatewayInvokeArgs Empty => new GetGatewayInvokeArgs();
    }


    [OutputType]
    public sealed class GetGatewayResult
    {
        /// <summary>
        /// Backend service configuration information
        /// </summary>
        public readonly Outputs.GetGatewayBackendSpecResult BackendSpec;
        /// <summary>
        /// Gateway remarks. Length limit: 0–253 characters.
        /// </summary>
        public readonly string Comments;
        /// <summary>
        /// Gateway creation time
        /// </summary>
        public readonly string CreatedTime;
        /// <summary>
        /// Custom log configuration
        /// </summary>
        public readonly Outputs.GetGatewayCustomLogResult CustomLog;
        /// <summary>
        /// Event
        /// </summary>
        public readonly ImmutableArray<Outputs.GetGatewayEventResult> Events;
        /// <summary>
        /// Gateway instance ID
        /// </summary>
        public readonly string GatewayId;
        /// <summary>
        /// Uniquely identifies the resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Log configuration
        /// </summary>
        public readonly Outputs.GetGatewayLogSpecResult LogSpec;
        /// <summary>
        /// Error message for gateway creation failure, deletion failure, or abnormal status
        /// </summary>
        public readonly string Message;
        /// <summary>
        /// Monitoring configuration information
        /// </summary>
        public readonly Outputs.GetGatewayMonitorSpecResult MonitorSpec;
        /// <summary>
        /// Gateway name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Network configuration information
        /// </summary>
        public readonly Outputs.GetGatewayNetworkSpecResult NetworkSpec;
        /// <summary>
        /// Project name
        /// </summary>
        public readonly string ProjectName;
        /// <summary>
        /// Resource specification configuration information
        /// </summary>
        public readonly Outputs.GetGatewayResourceSpecResult ResourceSpec;
        /// <summary>
        /// Gateway status. Options: Creating: Creating; CreatedFailed: Creation failed; Updating: Updating; Running: Running; Deleting: Deleting; DeletedFailed: Deletion failed; Abnormal: Abnormal
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Subnet ID list. Length limit: 1–2
        /// </summary>
        public readonly ImmutableArray<string> SubnetIds;
        /// <summary>
        /// Link tracing configuration information.
        /// </summary>
        public readonly Outputs.GetGatewayTraceSpecResult TraceSpec;
        /// <summary>
        /// Gateway type. Options: standard: Standard gateway; serverless: Serverless gateway (not supported yet)
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Gateway version.
        /// </summary>
        public readonly string Version;
        /// <summary>
        /// VPC ID。
        /// </summary>
        public readonly string VpcId;

        [OutputConstructor]
        private GetGatewayResult(
            Outputs.GetGatewayBackendSpecResult backendSpec,

            string comments,

            string createdTime,

            Outputs.GetGatewayCustomLogResult customLog,

            ImmutableArray<Outputs.GetGatewayEventResult> events,

            string gatewayId,

            string id,

            Outputs.GetGatewayLogSpecResult logSpec,

            string message,

            Outputs.GetGatewayMonitorSpecResult monitorSpec,

            string name,

            Outputs.GetGatewayNetworkSpecResult networkSpec,

            string projectName,

            Outputs.GetGatewayResourceSpecResult resourceSpec,

            string status,

            ImmutableArray<string> subnetIds,

            Outputs.GetGatewayTraceSpecResult traceSpec,

            string type,

            string version,

            string vpcId)
        {
            BackendSpec = backendSpec;
            Comments = comments;
            CreatedTime = createdTime;
            CustomLog = customLog;
            Events = events;
            GatewayId = gatewayId;
            Id = id;
            LogSpec = logSpec;
            Message = message;
            MonitorSpec = monitorSpec;
            Name = name;
            NetworkSpec = networkSpec;
            ProjectName = projectName;
            ResourceSpec = resourceSpec;
            Status = status;
            SubnetIds = subnetIds;
            TraceSpec = traceSpec;
            Type = type;
            Version = version;
            VpcId = vpcId;
        }
    }
}
