// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.tos.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.volcengine.volcenginecc.tos.inputs.BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointFollowerArgs;
import com.volcengine.volcenginecc.tos.inputs.BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointPrimaryArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs extends com.pulumi.resources.ResourceArgs {

    public static final BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs Empty = new BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs();

    @Import(name="followers")
    private @Nullable Output<List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointFollowerArgs>> followers;

    public Optional<Output<List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointFollowerArgs>>> followers() {
        return Optional.ofNullable(this.followers);
    }

    @Import(name="primaries")
    private @Nullable Output<List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointPrimaryArgs>> primaries;

    public Optional<Output<List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointPrimaryArgs>>> primaries() {
        return Optional.ofNullable(this.primaries);
    }

    private BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs() {}

    private BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs(BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs $) {
        this.followers = $.followers;
        this.primaries = $.primaries;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs $;

        public Builder() {
            $ = new BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs();
        }

        public Builder(BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs defaults) {
            $ = new BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs(Objects.requireNonNull(defaults));
        }

        public Builder followers(@Nullable Output<List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointFollowerArgs>> followers) {
            $.followers = followers;
            return this;
        }

        public Builder followers(List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointFollowerArgs> followers) {
            return followers(Output.of(followers));
        }

        public Builder followers(BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointFollowerArgs... followers) {
            return followers(List.of(followers));
        }

        public Builder primaries(@Nullable Output<List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointPrimaryArgs>> primaries) {
            $.primaries = primaries;
            return this;
        }

        public Builder primaries(List<BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointPrimaryArgs> primaries) {
            return primaries(Output.of(primaries));
        }

        public Builder primaries(BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointPrimaryArgs... primaries) {
            return primaries(List.of(primaries));
        }

        public BucketMirrorBackRuleRedirectPrivateSourceSourceEndpointArgs build() {
            return $;
        }
    }

}
