// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.ark;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.resources.InvokeArgs;
import com.volcengine.volcenginecc.Utilities;
import com.volcengine.volcenginecc.ark.inputs.GetEndpointArgs;
import com.volcengine.volcenginecc.ark.inputs.GetEndpointPlainArgs;
import com.volcengine.volcenginecc.ark.outputs.GetEndpointResult;
import com.volcengine.volcenginecc.ark.outputs.GetEndpointsResult;
import java.util.concurrent.CompletableFuture;

public final class ArkFunctions {
    /**
     * Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static Output<GetEndpointResult> getEndpoint(GetEndpointArgs args) {
        return getEndpoint(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static CompletableFuture<GetEndpointResult> getEndpointPlain(GetEndpointPlainArgs args) {
        return getEndpointPlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static Output<GetEndpointResult> getEndpoint(GetEndpointArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("volcenginecc:ark/getEndpoint:getEndpoint", TypeShape.of(GetEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static Output<GetEndpointResult> getEndpoint(GetEndpointArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("volcenginecc:ark/getEndpoint:getEndpoint", TypeShape.of(GetEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static CompletableFuture<GetEndpointResult> getEndpointPlain(GetEndpointPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("volcenginecc:ark/getEndpoint:getEndpoint", TypeShape.of(GetEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static Output<GetEndpointsResult> getEndpoints() {
        return getEndpoints(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static CompletableFuture<GetEndpointsResult> getEndpointsPlain() {
        return getEndpointsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static Output<GetEndpointsResult> getEndpoints(InvokeArgs args) {
        return getEndpoints(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static CompletableFuture<GetEndpointsResult> getEndpointsPlain(InvokeArgs args) {
        return getEndpointsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static Output<GetEndpointsResult> getEndpoints(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("volcenginecc:ark/getEndpoints:getEndpoints", TypeShape.of(GetEndpointsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static Output<GetEndpointsResult> getEndpoints(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("volcenginecc:ark/getEndpoints:getEndpoints", TypeShape.of(GetEndpointsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Volcengine::ARK::Endpoint
     * 
     */
    public static CompletableFuture<GetEndpointsResult> getEndpointsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("volcenginecc:ark/getEndpoints:getEndpoints", TypeShape.of(GetEndpointsResult.class), args, Utilities.withVersion(options));
    }
}
