# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SnapshotArgs', 'Snapshot']

@pulumi.input_type
class SnapshotArgs:
    def __init__(__self__, *,
                 snapshot_name: pulumi.Input[_builtins.str],
                 volume_id: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input['SnapshotTagArgs']]]] = None):
        """
        The set of arguments for constructing a Snapshot resource.

        :param pulumi.Input[_builtins.str] snapshot_name: Name of the created snapshot. Naming rules: length must be between 1 and 128 characters. Only Chinese characters, letters, numbers, underscores (_), hyphens (-), and periods (.) are allowed. To avoid conflicts with automatic snapshot names, the name cannot start with 'auto'.
        :param pulumi.Input[_builtins.str] volume_id: Cloud disk ID associated with the snapshot.
        :param pulumi.Input[_builtins.str] description: Snapshot description. Default is empty. Length must be between 0 and 255 characters.
        :param pulumi.Input[_builtins.str] project_name: Name of the Project to which the snapshot will be added. Note: snapshots do not inherit the project of the cloud disk, so snapshots and cloud disks can belong to different projects. If you do not set ProjectName when creating the snapshot, it will be added to the default project.
        :param pulumi.Input[_builtins.int] retention_days: Snapshot retention period, in days. Value options: empty: retain snapshot permanently. 1~65536: specify retention days. Default is empty, which means retain snapshot permanently. Snapshot retention period is calculated from the snapshot creation time.
        :param pulumi.Input[Sequence[pulumi.Input['SnapshotTagArgs']]] tags: Snapshot tag information.
               Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        """
        pulumi.set(__self__, "snapshot_name", snapshot_name)
        pulumi.set(__self__, "volume_id", volume_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if project_name is not None:
            pulumi.set(__self__, "project_name", project_name)
        if retention_days is not None:
            pulumi.set(__self__, "retention_days", retention_days)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="snapshotName")
    def snapshot_name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the created snapshot. Naming rules: length must be between 1 and 128 characters. Only Chinese characters, letters, numbers, underscores (_), hyphens (-), and periods (.) are allowed. To avoid conflicts with automatic snapshot names, the name cannot start with 'auto'.
        """
        return pulumi.get(self, "snapshot_name")

    @snapshot_name.setter
    def snapshot_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "snapshot_name", value)

    @_builtins.property
    @pulumi.getter(name="volumeId")
    def volume_id(self) -> pulumi.Input[_builtins.str]:
        """
        Cloud disk ID associated with the snapshot.
        """
        return pulumi.get(self, "volume_id")

    @volume_id.setter
    def volume_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "volume_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Snapshot description. Default is empty. Length must be between 0 and 255 characters.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the Project to which the snapshot will be added. Note: snapshots do not inherit the project of the cloud disk, so snapshots and cloud disks can belong to different projects. If you do not set ProjectName when creating the snapshot, it will be added to the default project.
        """
        return pulumi.get(self, "project_name")

    @project_name.setter
    def project_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_name", value)

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Snapshot retention period, in days. Value options: empty: retain snapshot permanently. 1~65536: specify retention days. Default is empty, which means retain snapshot permanently. Snapshot retention period is calculated from the snapshot creation time.
        """
        return pulumi.get(self, "retention_days")

    @retention_days.setter
    def retention_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "retention_days", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SnapshotTagArgs']]]]:
        """
        Snapshot tag information.
        Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SnapshotTagArgs']]]]):
        pulumi.set(self, "tags", value)


@pulumi.input_type
class _SnapshotState:
    def __init__(__self__, *,
                 creation_time: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 image_id: pulumi.Input[Optional[_builtins.str]] = None,
                 instant_access: pulumi.Input[Optional[_builtins.bool]] = None,
                 progress: pulumi.Input[Optional[_builtins.int]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 shared: pulumi.Input[Optional[_builtins.bool]] = None,
                 snapshot_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 snapshot_id: pulumi.Input[Optional[_builtins.str]] = None,
                 snapshot_name: pulumi.Input[Optional[_builtins.str]] = None,
                 snapshot_type: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input['SnapshotTagArgs']]]] = None,
                 volume_id: pulumi.Input[Optional[_builtins.str]] = None,
                 volume_kind: pulumi.Input[Optional[_builtins.str]] = None,
                 volume_name: pulumi.Input[Optional[_builtins.str]] = None,
                 volume_size: pulumi.Input[Optional[_builtins.int]] = None,
                 volume_status: pulumi.Input[Optional[_builtins.str]] = None,
                 volume_type: pulumi.Input[Optional[_builtins.str]] = None,
                 zone_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Snapshot resources.

        :param pulumi.Input[_builtins.str] creation_time: Snapshot creation time.
        :param pulumi.Input[_builtins.str] description: Snapshot description. Default is empty. Length must be between 0 and 255 characters.
        :param pulumi.Input[_builtins.str] image_id: Image ID
        :param pulumi.Input[_builtins.bool] instant_access: Whether the snapshot has enabled ultra-fast availability. Value options: true: ultra-fast availability enabled. false: ultra-fast availability not enabled.
        :param pulumi.Input[_builtins.int] progress: Snapshot dump progress.
        :param pulumi.Input[_builtins.str] project_name: Name of the Project to which the snapshot will be added. Note: snapshots do not inherit the project of the cloud disk, so snapshots and cloud disks can belong to different projects. If you do not set ProjectName when creating the snapshot, it will be added to the default project.
        :param pulumi.Input[_builtins.int] retention_days: Snapshot retention period, in days. Value options: empty: retain snapshot permanently. 1~65536: specify retention days. Default is empty, which means retain snapshot permanently. Snapshot retention period is calculated from the snapshot creation time.
        :param pulumi.Input[_builtins.bool] shared: Whether the snapshot is shared.
        :param pulumi.Input[_builtins.str] snapshot_group_id: Snapshot consistency group ID.
        :param pulumi.Input[_builtins.str] snapshot_id: Snapshot ID.
        :param pulumi.Input[_builtins.str] snapshot_name: Name of the created snapshot. Naming rules: length must be between 1 and 128 characters. Only Chinese characters, letters, numbers, underscores (_), hyphens (-), and periods (.) are allowed. To avoid conflicts with automatic snapshot names, the name cannot start with 'auto'.
        :param pulumi.Input[_builtins.str] snapshot_type: Snapshot type. The available values are: user: query manual snapshots. auto: query automatic snapshots. share: query shared snapshots. By default, all snapshots are queried.
        :param pulumi.Input[_builtins.str] status: Snapshot status. Value options: available: available. creating: creating. rollbacking: rolling back. deleted: deleted. failed: error.
        :param pulumi.Input[Sequence[pulumi.Input['SnapshotTagArgs']]] tags: Snapshot tag information.
               Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        :param pulumi.Input[_builtins.str] volume_id: Cloud disk ID associated with the snapshot.
        :param pulumi.Input[_builtins.str] volume_kind: Cloud disk category. Value options: system: system disk. data: data disk.
        :param pulumi.Input[_builtins.str] volume_name: Cloud disk name.
        :param pulumi.Input[_builtins.int] volume_size: Cloud disk size, in GiB.
        :param pulumi.Input[_builtins.str] volume_status: Cloud disk status. Value options: available: available, attaching: attaching, attached: attached, detaching: detaching, creating: creating, deleting: deleting, error: error, extending: expanding, "": cloud disk deleted.
        :param pulumi.Input[_builtins.str] volume_type: Cloud disk type. Value options: ESSD*PL0: Ultra-fast SSD cloud disk, PL0 specification. ESSD*FlexPL: Ultra-fast SSD cloud disk, FlexPL specification. TSSD_TL0: Throughput SSD cloud disk
        :param pulumi.Input[_builtins.str] zone_id: Availability zone ID where the snapshot is located.
        """
        if creation_time is not None:
            pulumi.set(__self__, "creation_time", creation_time)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if image_id is not None:
            pulumi.set(__self__, "image_id", image_id)
        if instant_access is not None:
            pulumi.set(__self__, "instant_access", instant_access)
        if progress is not None:
            pulumi.set(__self__, "progress", progress)
        if project_name is not None:
            pulumi.set(__self__, "project_name", project_name)
        if retention_days is not None:
            pulumi.set(__self__, "retention_days", retention_days)
        if shared is not None:
            pulumi.set(__self__, "shared", shared)
        if snapshot_group_id is not None:
            pulumi.set(__self__, "snapshot_group_id", snapshot_group_id)
        if snapshot_id is not None:
            pulumi.set(__self__, "snapshot_id", snapshot_id)
        if snapshot_name is not None:
            pulumi.set(__self__, "snapshot_name", snapshot_name)
        if snapshot_type is not None:
            pulumi.set(__self__, "snapshot_type", snapshot_type)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if volume_id is not None:
            pulumi.set(__self__, "volume_id", volume_id)
        if volume_kind is not None:
            pulumi.set(__self__, "volume_kind", volume_kind)
        if volume_name is not None:
            pulumi.set(__self__, "volume_name", volume_name)
        if volume_size is not None:
            pulumi.set(__self__, "volume_size", volume_size)
        if volume_status is not None:
            pulumi.set(__self__, "volume_status", volume_status)
        if volume_type is not None:
            pulumi.set(__self__, "volume_type", volume_type)
        if zone_id is not None:
            pulumi.set(__self__, "zone_id", zone_id)

    @_builtins.property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Snapshot creation time.
        """
        return pulumi.get(self, "creation_time")

    @creation_time.setter
    def creation_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "creation_time", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Snapshot description. Default is empty. Length must be between 0 and 255 characters.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="imageId")
    def image_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Image ID
        """
        return pulumi.get(self, "image_id")

    @image_id.setter
    def image_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "image_id", value)

    @_builtins.property
    @pulumi.getter(name="instantAccess")
    def instant_access(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the snapshot has enabled ultra-fast availability. Value options: true: ultra-fast availability enabled. false: ultra-fast availability not enabled.
        """
        return pulumi.get(self, "instant_access")

    @instant_access.setter
    def instant_access(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "instant_access", value)

    @_builtins.property
    @pulumi.getter
    def progress(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Snapshot dump progress.
        """
        return pulumi.get(self, "progress")

    @progress.setter
    def progress(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "progress", value)

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the Project to which the snapshot will be added. Note: snapshots do not inherit the project of the cloud disk, so snapshots and cloud disks can belong to different projects. If you do not set ProjectName when creating the snapshot, it will be added to the default project.
        """
        return pulumi.get(self, "project_name")

    @project_name.setter
    def project_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_name", value)

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Snapshot retention period, in days. Value options: empty: retain snapshot permanently. 1~65536: specify retention days. Default is empty, which means retain snapshot permanently. Snapshot retention period is calculated from the snapshot creation time.
        """
        return pulumi.get(self, "retention_days")

    @retention_days.setter
    def retention_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "retention_days", value)

    @_builtins.property
    @pulumi.getter
    def shared(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the snapshot is shared.
        """
        return pulumi.get(self, "shared")

    @shared.setter
    def shared(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "shared", value)

    @_builtins.property
    @pulumi.getter(name="snapshotGroupId")
    def snapshot_group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Snapshot consistency group ID.
        """
        return pulumi.get(self, "snapshot_group_id")

    @snapshot_group_id.setter
    def snapshot_group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "snapshot_group_id", value)

    @_builtins.property
    @pulumi.getter(name="snapshotId")
    def snapshot_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Snapshot ID.
        """
        return pulumi.get(self, "snapshot_id")

    @snapshot_id.setter
    def snapshot_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "snapshot_id", value)

    @_builtins.property
    @pulumi.getter(name="snapshotName")
    def snapshot_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the created snapshot. Naming rules: length must be between 1 and 128 characters. Only Chinese characters, letters, numbers, underscores (_), hyphens (-), and periods (.) are allowed. To avoid conflicts with automatic snapshot names, the name cannot start with 'auto'.
        """
        return pulumi.get(self, "snapshot_name")

    @snapshot_name.setter
    def snapshot_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "snapshot_name", value)

    @_builtins.property
    @pulumi.getter(name="snapshotType")
    def snapshot_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Snapshot type. The available values are: user: query manual snapshots. auto: query automatic snapshots. share: query shared snapshots. By default, all snapshots are queried.
        """
        return pulumi.get(self, "snapshot_type")

    @snapshot_type.setter
    def snapshot_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "snapshot_type", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Snapshot status. Value options: available: available. creating: creating. rollbacking: rolling back. deleted: deleted. failed: error.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SnapshotTagArgs']]]]:
        """
        Snapshot tag information.
        Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SnapshotTagArgs']]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="volumeId")
    def volume_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud disk ID associated with the snapshot.
        """
        return pulumi.get(self, "volume_id")

    @volume_id.setter
    def volume_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "volume_id", value)

    @_builtins.property
    @pulumi.getter(name="volumeKind")
    def volume_kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud disk category. Value options: system: system disk. data: data disk.
        """
        return pulumi.get(self, "volume_kind")

    @volume_kind.setter
    def volume_kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "volume_kind", value)

    @_builtins.property
    @pulumi.getter(name="volumeName")
    def volume_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud disk name.
        """
        return pulumi.get(self, "volume_name")

    @volume_name.setter
    def volume_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "volume_name", value)

    @_builtins.property
    @pulumi.getter(name="volumeSize")
    def volume_size(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Cloud disk size, in GiB.
        """
        return pulumi.get(self, "volume_size")

    @volume_size.setter
    def volume_size(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "volume_size", value)

    @_builtins.property
    @pulumi.getter(name="volumeStatus")
    def volume_status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud disk status. Value options: available: available, attaching: attaching, attached: attached, detaching: detaching, creating: creating, deleting: deleting, error: error, extending: expanding, "": cloud disk deleted.
        """
        return pulumi.get(self, "volume_status")

    @volume_status.setter
    def volume_status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "volume_status", value)

    @_builtins.property
    @pulumi.getter(name="volumeType")
    def volume_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud disk type. Value options: ESSD*PL0: Ultra-fast SSD cloud disk, PL0 specification. ESSD*FlexPL: Ultra-fast SSD cloud disk, FlexPL specification. TSSD_TL0: Throughput SSD cloud disk
        """
        return pulumi.get(self, "volume_type")

    @volume_type.setter
    def volume_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "volume_type", value)

    @_builtins.property
    @pulumi.getter(name="zoneId")
    def zone_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Availability zone ID where the snapshot is located.
        """
        return pulumi.get(self, "zone_id")

    @zone_id.setter
    def zone_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "zone_id", value)


@pulumi.type_token("volcenginecc:storageebs/snapshot:Snapshot")
class Snapshot(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 snapshot_name: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SnapshotTagArgs', 'SnapshotTagArgsDict']]]]] = None,
                 volume_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A snapshot is a backup method. Each snapshot is a backup file of cloud disk data at a specific point in time. When data is lost or a failure occurs, you can roll back cloud disk data using the snapshot to recover lost data.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_volcenginecc as volcenginecc

        storage_ebs_snapshot_demo = volcenginecc.storageebs.Snapshot("StorageEBSSnapshotDemo",
            volume_id="vol-3wt6pip1dy3qu*****",
            snapshot_name="StorageEBSSnapshotDemo",
            description="StorageEBSSnapshotDemo description",
            project_name="default",
            tags=[{
                "key": "env",
                "value": "test",
            }])
        ```

        ## Import

        ```sh
        $ pulumi import volcenginecc:storageebs/snapshot:Snapshot example "snapshot_id"
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Snapshot description. Default is empty. Length must be between 0 and 255 characters.
        :param pulumi.Input[_builtins.str] project_name: Name of the Project to which the snapshot will be added. Note: snapshots do not inherit the project of the cloud disk, so snapshots and cloud disks can belong to different projects. If you do not set ProjectName when creating the snapshot, it will be added to the default project.
        :param pulumi.Input[_builtins.int] retention_days: Snapshot retention period, in days. Value options: empty: retain snapshot permanently. 1~65536: specify retention days. Default is empty, which means retain snapshot permanently. Snapshot retention period is calculated from the snapshot creation time.
        :param pulumi.Input[_builtins.str] snapshot_name: Name of the created snapshot. Naming rules: length must be between 1 and 128 characters. Only Chinese characters, letters, numbers, underscores (_), hyphens (-), and periods (.) are allowed. To avoid conflicts with automatic snapshot names, the name cannot start with 'auto'.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SnapshotTagArgs', 'SnapshotTagArgsDict']]]] tags: Snapshot tag information.
               Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        :param pulumi.Input[_builtins.str] volume_id: Cloud disk ID associated with the snapshot.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SnapshotArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A snapshot is a backup method. Each snapshot is a backup file of cloud disk data at a specific point in time. When data is lost or a failure occurs, you can roll back cloud disk data using the snapshot to recover lost data.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_volcenginecc as volcenginecc

        storage_ebs_snapshot_demo = volcenginecc.storageebs.Snapshot("StorageEBSSnapshotDemo",
            volume_id="vol-3wt6pip1dy3qu*****",
            snapshot_name="StorageEBSSnapshotDemo",
            description="StorageEBSSnapshotDemo description",
            project_name="default",
            tags=[{
                "key": "env",
                "value": "test",
            }])
        ```

        ## Import

        ```sh
        $ pulumi import volcenginecc:storageebs/snapshot:Snapshot example "snapshot_id"
        ```


        :param str resource_name: The name of the resource.
        :param SnapshotArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SnapshotArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 snapshot_name: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SnapshotTagArgs', 'SnapshotTagArgsDict']]]]] = None,
                 volume_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SnapshotArgs.__new__(SnapshotArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["project_name"] = project_name
            __props__.__dict__["retention_days"] = retention_days
            if snapshot_name is None and not opts.urn:
                raise TypeError("Missing required property 'snapshot_name'")
            __props__.__dict__["snapshot_name"] = snapshot_name
            __props__.__dict__["tags"] = tags
            if volume_id is None and not opts.urn:
                raise TypeError("Missing required property 'volume_id'")
            __props__.__dict__["volume_id"] = volume_id
            __props__.__dict__["creation_time"] = None
            __props__.__dict__["image_id"] = None
            __props__.__dict__["instant_access"] = None
            __props__.__dict__["progress"] = None
            __props__.__dict__["shared"] = None
            __props__.__dict__["snapshot_group_id"] = None
            __props__.__dict__["snapshot_id"] = None
            __props__.__dict__["snapshot_type"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["volume_kind"] = None
            __props__.__dict__["volume_name"] = None
            __props__.__dict__["volume_size"] = None
            __props__.__dict__["volume_status"] = None
            __props__.__dict__["volume_type"] = None
            __props__.__dict__["zone_id"] = None
        super(Snapshot, __self__).__init__(
            'volcenginecc:storageebs/snapshot:Snapshot',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            creation_time: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            image_id: pulumi.Input[Optional[_builtins.str]] = None,
            instant_access: pulumi.Input[Optional[_builtins.bool]] = None,
            progress: pulumi.Input[Optional[_builtins.int]] = None,
            project_name: pulumi.Input[Optional[_builtins.str]] = None,
            retention_days: pulumi.Input[Optional[_builtins.int]] = None,
            shared: pulumi.Input[Optional[_builtins.bool]] = None,
            snapshot_group_id: pulumi.Input[Optional[_builtins.str]] = None,
            snapshot_id: pulumi.Input[Optional[_builtins.str]] = None,
            snapshot_name: pulumi.Input[Optional[_builtins.str]] = None,
            snapshot_type: pulumi.Input[Optional[_builtins.str]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            tags: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SnapshotTagArgs', 'SnapshotTagArgsDict']]]]] = None,
            volume_id: pulumi.Input[Optional[_builtins.str]] = None,
            volume_kind: pulumi.Input[Optional[_builtins.str]] = None,
            volume_name: pulumi.Input[Optional[_builtins.str]] = None,
            volume_size: pulumi.Input[Optional[_builtins.int]] = None,
            volume_status: pulumi.Input[Optional[_builtins.str]] = None,
            volume_type: pulumi.Input[Optional[_builtins.str]] = None,
            zone_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'Snapshot':
        """
        Get an existing Snapshot resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] creation_time: Snapshot creation time.
        :param pulumi.Input[_builtins.str] description: Snapshot description. Default is empty. Length must be between 0 and 255 characters.
        :param pulumi.Input[_builtins.str] image_id: Image ID
        :param pulumi.Input[_builtins.bool] instant_access: Whether the snapshot has enabled ultra-fast availability. Value options: true: ultra-fast availability enabled. false: ultra-fast availability not enabled.
        :param pulumi.Input[_builtins.int] progress: Snapshot dump progress.
        :param pulumi.Input[_builtins.str] project_name: Name of the Project to which the snapshot will be added. Note: snapshots do not inherit the project of the cloud disk, so snapshots and cloud disks can belong to different projects. If you do not set ProjectName when creating the snapshot, it will be added to the default project.
        :param pulumi.Input[_builtins.int] retention_days: Snapshot retention period, in days. Value options: empty: retain snapshot permanently. 1~65536: specify retention days. Default is empty, which means retain snapshot permanently. Snapshot retention period is calculated from the snapshot creation time.
        :param pulumi.Input[_builtins.bool] shared: Whether the snapshot is shared.
        :param pulumi.Input[_builtins.str] snapshot_group_id: Snapshot consistency group ID.
        :param pulumi.Input[_builtins.str] snapshot_id: Snapshot ID.
        :param pulumi.Input[_builtins.str] snapshot_name: Name of the created snapshot. Naming rules: length must be between 1 and 128 characters. Only Chinese characters, letters, numbers, underscores (_), hyphens (-), and periods (.) are allowed. To avoid conflicts with automatic snapshot names, the name cannot start with 'auto'.
        :param pulumi.Input[_builtins.str] snapshot_type: Snapshot type. The available values are: user: query manual snapshots. auto: query automatic snapshots. share: query shared snapshots. By default, all snapshots are queried.
        :param pulumi.Input[_builtins.str] status: Snapshot status. Value options: available: available. creating: creating. rollbacking: rolling back. deleted: deleted. failed: error.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SnapshotTagArgs', 'SnapshotTagArgsDict']]]] tags: Snapshot tag information.
               Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        :param pulumi.Input[_builtins.str] volume_id: Cloud disk ID associated with the snapshot.
        :param pulumi.Input[_builtins.str] volume_kind: Cloud disk category. Value options: system: system disk. data: data disk.
        :param pulumi.Input[_builtins.str] volume_name: Cloud disk name.
        :param pulumi.Input[_builtins.int] volume_size: Cloud disk size, in GiB.
        :param pulumi.Input[_builtins.str] volume_status: Cloud disk status. Value options: available: available, attaching: attaching, attached: attached, detaching: detaching, creating: creating, deleting: deleting, error: error, extending: expanding, "": cloud disk deleted.
        :param pulumi.Input[_builtins.str] volume_type: Cloud disk type. Value options: ESSD*PL0: Ultra-fast SSD cloud disk, PL0 specification. ESSD*FlexPL: Ultra-fast SSD cloud disk, FlexPL specification. TSSD_TL0: Throughput SSD cloud disk
        :param pulumi.Input[_builtins.str] zone_id: Availability zone ID where the snapshot is located.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SnapshotState.__new__(_SnapshotState)

        __props__.__dict__["creation_time"] = creation_time
        __props__.__dict__["description"] = description
        __props__.__dict__["image_id"] = image_id
        __props__.__dict__["instant_access"] = instant_access
        __props__.__dict__["progress"] = progress
        __props__.__dict__["project_name"] = project_name
        __props__.__dict__["retention_days"] = retention_days
        __props__.__dict__["shared"] = shared
        __props__.__dict__["snapshot_group_id"] = snapshot_group_id
        __props__.__dict__["snapshot_id"] = snapshot_id
        __props__.__dict__["snapshot_name"] = snapshot_name
        __props__.__dict__["snapshot_type"] = snapshot_type
        __props__.__dict__["status"] = status
        __props__.__dict__["tags"] = tags
        __props__.__dict__["volume_id"] = volume_id
        __props__.__dict__["volume_kind"] = volume_kind
        __props__.__dict__["volume_name"] = volume_name
        __props__.__dict__["volume_size"] = volume_size
        __props__.__dict__["volume_status"] = volume_status
        __props__.__dict__["volume_type"] = volume_type
        __props__.__dict__["zone_id"] = zone_id
        return Snapshot(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> pulumi.Output[_builtins.str]:
        """
        Snapshot creation time.
        """
        return pulumi.get(self, "creation_time")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        Snapshot description. Default is empty. Length must be between 0 and 255 characters.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="imageId")
    def image_id(self) -> pulumi.Output[_builtins.str]:
        """
        Image ID
        """
        return pulumi.get(self, "image_id")

    @_builtins.property
    @pulumi.getter(name="instantAccess")
    def instant_access(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the snapshot has enabled ultra-fast availability. Value options: true: ultra-fast availability enabled. false: ultra-fast availability not enabled.
        """
        return pulumi.get(self, "instant_access")

    @_builtins.property
    @pulumi.getter
    def progress(self) -> pulumi.Output[_builtins.int]:
        """
        Snapshot dump progress.
        """
        return pulumi.get(self, "progress")

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the Project to which the snapshot will be added. Note: snapshots do not inherit the project of the cloud disk, so snapshots and cloud disks can belong to different projects. If you do not set ProjectName when creating the snapshot, it will be added to the default project.
        """
        return pulumi.get(self, "project_name")

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Output[_builtins.int]:
        """
        Snapshot retention period, in days. Value options: empty: retain snapshot permanently. 1~65536: specify retention days. Default is empty, which means retain snapshot permanently. Snapshot retention period is calculated from the snapshot creation time.
        """
        return pulumi.get(self, "retention_days")

    @_builtins.property
    @pulumi.getter
    def shared(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the snapshot is shared.
        """
        return pulumi.get(self, "shared")

    @_builtins.property
    @pulumi.getter(name="snapshotGroupId")
    def snapshot_group_id(self) -> pulumi.Output[_builtins.str]:
        """
        Snapshot consistency group ID.
        """
        return pulumi.get(self, "snapshot_group_id")

    @_builtins.property
    @pulumi.getter(name="snapshotId")
    def snapshot_id(self) -> pulumi.Output[_builtins.str]:
        """
        Snapshot ID.
        """
        return pulumi.get(self, "snapshot_id")

    @_builtins.property
    @pulumi.getter(name="snapshotName")
    def snapshot_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the created snapshot. Naming rules: length must be between 1 and 128 characters. Only Chinese characters, letters, numbers, underscores (_), hyphens (-), and periods (.) are allowed. To avoid conflicts with automatic snapshot names, the name cannot start with 'auto'.
        """
        return pulumi.get(self, "snapshot_name")

    @_builtins.property
    @pulumi.getter(name="snapshotType")
    def snapshot_type(self) -> pulumi.Output[_builtins.str]:
        """
        Snapshot type. The available values are: user: query manual snapshots. auto: query automatic snapshots. share: query shared snapshots. By default, all snapshots are queried.
        """
        return pulumi.get(self, "snapshot_type")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Snapshot status. Value options: available: available. creating: creating. rollbacking: rolling back. deleted: deleted. failed: error.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Sequence['outputs.SnapshotTag']]:
        """
        Snapshot tag information.
        Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="volumeId")
    def volume_id(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud disk ID associated with the snapshot.
        """
        return pulumi.get(self, "volume_id")

    @_builtins.property
    @pulumi.getter(name="volumeKind")
    def volume_kind(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud disk category. Value options: system: system disk. data: data disk.
        """
        return pulumi.get(self, "volume_kind")

    @_builtins.property
    @pulumi.getter(name="volumeName")
    def volume_name(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud disk name.
        """
        return pulumi.get(self, "volume_name")

    @_builtins.property
    @pulumi.getter(name="volumeSize")
    def volume_size(self) -> pulumi.Output[_builtins.int]:
        """
        Cloud disk size, in GiB.
        """
        return pulumi.get(self, "volume_size")

    @_builtins.property
    @pulumi.getter(name="volumeStatus")
    def volume_status(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud disk status. Value options: available: available, attaching: attaching, attached: attached, detaching: detaching, creating: creating, deleting: deleting, error: error, extending: expanding, "": cloud disk deleted.
        """
        return pulumi.get(self, "volume_status")

    @_builtins.property
    @pulumi.getter(name="volumeType")
    def volume_type(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud disk type. Value options: ESSD*PL0: Ultra-fast SSD cloud disk, PL0 specification. ESSD*FlexPL: Ultra-fast SSD cloud disk, FlexPL specification. TSSD_TL0: Throughput SSD cloud disk
        """
        return pulumi.get(self, "volume_type")

    @_builtins.property
    @pulumi.getter(name="zoneId")
    def zone_id(self) -> pulumi.Output[_builtins.str]:
        """
        Availability zone ID where the snapshot is located.
        """
        return pulumi.get(self, "zone_id")

