// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.volcengine.volcenginecc.tls.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.volcengine.volcenginecc.tls.outputs.GetIndexFullText;
import com.volcengine.volcenginecc.tls.outputs.GetIndexKeyValue;
import com.volcengine.volcenginecc.tls.outputs.GetIndexUserInnerKeyValue;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetIndexResult {
    /**
     * @return Index creation time.
     * 
     */
    private String createTime;
    /**
     * @return Enable automatic index updates? When enabled, the system will automatically add newly detected fields to the key-value index. true: Enable automatic updates. false: Do not enable automatic updates.
     * 
     */
    private Boolean enableAutoIndex;
    /**
     * @return Full-text index configuration. If this field is null or not configured, full-text indexing is disabled. At least one of full-text index or key-value index must be configured; that is, at least one parameter between FullText and KeyValue must be specified.
     * 
     */
    private GetIndexFullText fullText;
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    private String id;
    /**
     * @return Key-value index configuration. If the length of this field array is 0 or not configured, key-value indexing is disabled. At least one of full-text index configuration or key-value index configuration must be set; that is, you must specify at least one parameter between FullText and KeyValue.
     * 
     */
    private List<GetIndexKeyValue> keyValues;
    /**
     * @return Set the maximum length for field values. The default is 2048. The valid range is 64–16384 bytes. If a single field value exceeds the specified maximum length, the excess part will be truncated and excluded from analysis. After updating the maximum field length, only incremental data is affected.
     * 
     */
    private Integer maxTextLen;
    /**
     * @return Last modified time of the index.
     * 
     */
    private String modifyTime;
    /**
     * @return Log topic ID.
     * 
     */
    private String topicId;
    /**
     * @return Reserved field index configuration. If the array length of this field is 0 or not configured, reserved field indexing is disabled. You cannot enable both full-text indexing and key-value indexing for the reserved field **content** at the same time. If you set the **content** index via the UserInnerKeyValue parameter, you cannot also set the FullText parameter. Among reserved fields, only manual indexing for **content** is currently supported. For other reserved field index settings, refer to reserved fields.
     * 
     */
    private List<GetIndexUserInnerKeyValue> userInnerKeyValues;

    private GetIndexResult() {}
    /**
     * @return Index creation time.
     * 
     */
    public String createTime() {
        return this.createTime;
    }
    /**
     * @return Enable automatic index updates? When enabled, the system will automatically add newly detected fields to the key-value index. true: Enable automatic updates. false: Do not enable automatic updates.
     * 
     */
    public Boolean enableAutoIndex() {
        return this.enableAutoIndex;
    }
    /**
     * @return Full-text index configuration. If this field is null or not configured, full-text indexing is disabled. At least one of full-text index or key-value index must be configured; that is, at least one parameter between FullText and KeyValue must be specified.
     * 
     */
    public GetIndexFullText fullText() {
        return this.fullText;
    }
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Key-value index configuration. If the length of this field array is 0 or not configured, key-value indexing is disabled. At least one of full-text index configuration or key-value index configuration must be set; that is, you must specify at least one parameter between FullText and KeyValue.
     * 
     */
    public List<GetIndexKeyValue> keyValues() {
        return this.keyValues;
    }
    /**
     * @return Set the maximum length for field values. The default is 2048. The valid range is 64–16384 bytes. If a single field value exceeds the specified maximum length, the excess part will be truncated and excluded from analysis. After updating the maximum field length, only incremental data is affected.
     * 
     */
    public Integer maxTextLen() {
        return this.maxTextLen;
    }
    /**
     * @return Last modified time of the index.
     * 
     */
    public String modifyTime() {
        return this.modifyTime;
    }
    /**
     * @return Log topic ID.
     * 
     */
    public String topicId() {
        return this.topicId;
    }
    /**
     * @return Reserved field index configuration. If the array length of this field is 0 or not configured, reserved field indexing is disabled. You cannot enable both full-text indexing and key-value indexing for the reserved field **content** at the same time. If you set the **content** index via the UserInnerKeyValue parameter, you cannot also set the FullText parameter. Among reserved fields, only manual indexing for **content** is currently supported. For other reserved field index settings, refer to reserved fields.
     * 
     */
    public List<GetIndexUserInnerKeyValue> userInnerKeyValues() {
        return this.userInnerKeyValues;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetIndexResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createTime;
        private Boolean enableAutoIndex;
        private GetIndexFullText fullText;
        private String id;
        private List<GetIndexKeyValue> keyValues;
        private Integer maxTextLen;
        private String modifyTime;
        private String topicId;
        private List<GetIndexUserInnerKeyValue> userInnerKeyValues;
        public Builder() {}
        public Builder(GetIndexResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createTime = defaults.createTime;
    	      this.enableAutoIndex = defaults.enableAutoIndex;
    	      this.fullText = defaults.fullText;
    	      this.id = defaults.id;
    	      this.keyValues = defaults.keyValues;
    	      this.maxTextLen = defaults.maxTextLen;
    	      this.modifyTime = defaults.modifyTime;
    	      this.topicId = defaults.topicId;
    	      this.userInnerKeyValues = defaults.userInnerKeyValues;
        }

        @CustomType.Setter
        public Builder createTime(String createTime) {
            if (createTime == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "createTime");
            }
            this.createTime = createTime;
            return this;
        }
        @CustomType.Setter
        public Builder enableAutoIndex(Boolean enableAutoIndex) {
            if (enableAutoIndex == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "enableAutoIndex");
            }
            this.enableAutoIndex = enableAutoIndex;
            return this;
        }
        @CustomType.Setter
        public Builder fullText(GetIndexFullText fullText) {
            if (fullText == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "fullText");
            }
            this.fullText = fullText;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder keyValues(List<GetIndexKeyValue> keyValues) {
            if (keyValues == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "keyValues");
            }
            this.keyValues = keyValues;
            return this;
        }
        public Builder keyValues(GetIndexKeyValue... keyValues) {
            return keyValues(List.of(keyValues));
        }
        @CustomType.Setter
        public Builder maxTextLen(Integer maxTextLen) {
            if (maxTextLen == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "maxTextLen");
            }
            this.maxTextLen = maxTextLen;
            return this;
        }
        @CustomType.Setter
        public Builder modifyTime(String modifyTime) {
            if (modifyTime == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "modifyTime");
            }
            this.modifyTime = modifyTime;
            return this;
        }
        @CustomType.Setter
        public Builder topicId(String topicId) {
            if (topicId == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "topicId");
            }
            this.topicId = topicId;
            return this;
        }
        @CustomType.Setter
        public Builder userInnerKeyValues(List<GetIndexUserInnerKeyValue> userInnerKeyValues) {
            if (userInnerKeyValues == null) {
              throw new MissingRequiredPropertyException("GetIndexResult", "userInnerKeyValues");
            }
            this.userInnerKeyValues = userInnerKeyValues;
            return this;
        }
        public Builder userInnerKeyValues(GetIndexUserInnerKeyValue... userInnerKeyValues) {
            return userInnerKeyValues(List.of(userInnerKeyValues));
        }
        public GetIndexResult build() {
            final var _resultValue = new GetIndexResult();
            _resultValue.createTime = createTime;
            _resultValue.enableAutoIndex = enableAutoIndex;
            _resultValue.fullText = fullText;
            _resultValue.id = id;
            _resultValue.keyValues = keyValues;
            _resultValue.maxTextLen = maxTextLen;
            _resultValue.modifyTime = modifyTime;
            _resultValue.topicId = topicId;
            _resultValue.userInnerKeyValues = userInnerKeyValues;
            return _resultValue;
        }
    }
}
