// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Escloud.Inputs
{

    public sealed class InstanceTransferInfoGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ForbidStop
        /// </summary>
        [Input("forbidStop")]
        public Input<bool>? ForbidStop { get; set; }

        /// <summary>
        /// Resource information
        /// </summary>
        [Input("reduceSpecConfig")]
        public Input<Inputs.InstanceTransferInfoReduceSpecConfigGetArgs>? ReduceSpecConfig { get; set; }

        /// <summary>
        /// Data migration task progress, percentage
        /// </summary>
        [Input("transferProgress")]
        public Input<double>? TransferProgress { get; set; }

        /// <summary>
        /// Data migration task status
        /// </summary>
        [Input("transferStatus")]
        public Input<string>? TransferStatus { get; set; }

        /// <summary>
        /// Data migration task ID
        /// </summary>
        [Input("transferTaskId")]
        public Input<string>? TransferTaskId { get; set; }

        public InstanceTransferInfoGetArgs()
        {
        }
        public static new InstanceTransferInfoGetArgs Empty => new InstanceTransferInfoGetArgs();
    }
}
