// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package apig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcenginecc/sdk/go/volcenginecc/internal"
)

// Plural Data Source schema for Volcengine::APIG::Upstream
func GetUpstreams(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetUpstreamsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetUpstreamsResult
	err := ctx.Invoke("volcenginecc:apig/getUpstreams:getUpstreams", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getUpstreams.
type GetUpstreamsResult struct {
	// Uniquely identifies the data source.
	Id string `pulumi:"id"`
	// Set of Resource Identifiers.
	Ids []string `pulumi:"ids"`
}

func GetUpstreamsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetUpstreamsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetUpstreamsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("volcenginecc:apig/getUpstreams:getUpstreams", nil, GetUpstreamsResultOutput{}, options).(GetUpstreamsResultOutput), nil
	}).(GetUpstreamsResultOutput)
}

// A collection of values returned by getUpstreams.
type GetUpstreamsResultOutput struct{ *pulumi.OutputState }

func (GetUpstreamsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUpstreamsResult)(nil)).Elem()
}

func (o GetUpstreamsResultOutput) ToGetUpstreamsResultOutput() GetUpstreamsResultOutput {
	return o
}

func (o GetUpstreamsResultOutput) ToGetUpstreamsResultOutputWithContext(ctx context.Context) GetUpstreamsResultOutput {
	return o
}

// Uniquely identifies the data source.
func (o GetUpstreamsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetUpstreamsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Set of Resource Identifiers.
func (o GetUpstreamsResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetUpstreamsResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetUpstreamsResultOutput{})
}
