// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcenginecc.Ecs.Outputs
{

    [OutputType]
    public sealed class ImageImportImage
    {
        /// <summary>
        /// Data disk files included in the custom image, at the TOS bucket URL.
        /// </summary>
        public readonly ImmutableArray<string> ImportDataVolumes;
        /// <summary>
        /// System disk files included in the custom image, at the TOS bucket URL.
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private ImageImportImage(
            ImmutableArray<string> importDataVolumes,

            string? url)
        {
            ImportDataVolumes = importDataVolumes;
            Url = url;
        }
    }
}
