// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Data Source schema for Volcengine::VPC::Ipv6Gateway
 */
export function getIpv6Gateway(args: GetIpv6GatewayArgs, opts?: pulumi.InvokeOptions): Promise<GetIpv6GatewayResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("volcenginecc:vpc/getIpv6Gateway:getIpv6Gateway", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpv6Gateway.
 */
export interface GetIpv6GatewayArgs {
    /**
     * Uniquely identifies the resource.
     */
    id: string;
}

/**
 * A collection of values returned by getIpv6Gateway.
 */
export interface GetIpv6GatewayResult {
    /**
     * Creation time of the IPv6 gateway instance
     */
    readonly createdTime: string;
    /**
     * Description of the IPv6 gateway instance. Length limit: 0–255 characters. If not specified, defaults to an empty string. Must start with a letter, Chinese character, or number. Can include English comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。)
     */
    readonly description: string;
    /**
     * Uniquely identifies the resource.
     */
    readonly id: string;
    /**
     * IPv6 gateway instance ID
     */
    readonly ipv6GatewayId: string;
    /**
     * Name of the IPv6 gateway instance. Length limit: 1–128 characters. Must start with a letter, Chinese character, or number. Can include period (.), underscore (_), and hyphen (-). If not specified, defaults to the IPv6 gateway ID
     */
    readonly name: string;
    /**
     * Name of the project to which the IPv6 gateway belongs
     */
    readonly projectName: string;
    /**
     * Route table ID associated with the IPv6 gateway instance
     */
    readonly routeTableId: string;
    /**
     * Operating status of the IPv6 gateway instance. Possible values: Creating: Creating. Deleting: Deleting. Available: Available
     */
    readonly status: string;
    /**
     * Tag information
     */
    readonly tags: outputs.vpc.GetIpv6GatewayTag[];
    /**
     * Modification time of the IPv6 gateway instance
     */
    readonly updatedTime: string;
    /**
     * VPC ID to be associated with the IPv6 gateway instance. Each VPC can only be associated with one IPv6 gateway instance. Ensure the VPC to be associated is not linked to another IPv6 gateway instance
     */
    readonly vpcId: string;
}
/**
 * Data Source schema for Volcengine::VPC::Ipv6Gateway
 */
export function getIpv6GatewayOutput(args: GetIpv6GatewayOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIpv6GatewayResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("volcenginecc:vpc/getIpv6Gateway:getIpv6Gateway", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpv6Gateway.
 */
export interface GetIpv6GatewayOutputArgs {
    /**
     * Uniquely identifies the resource.
     */
    id: pulumi.Input<string>;
}
