// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vpc

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcenginecc/sdk/go/volcenginecc/internal"
)

// Data Source schema for Volcengine::VPC::TrafficMirrorTarget
func LookupTrafficMirrorTarget(ctx *pulumi.Context, args *LookupTrafficMirrorTargetArgs, opts ...pulumi.InvokeOption) (*LookupTrafficMirrorTargetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTrafficMirrorTargetResult
	err := ctx.Invoke("volcenginecc:vpc/getTrafficMirrorTarget:getTrafficMirrorTarget", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTrafficMirrorTarget.
type LookupTrafficMirrorTargetArgs struct {
	// Uniquely identifies the resource.
	Id string `pulumi:"id"`
}

// A collection of values returned by getTrafficMirrorTarget.
type LookupTrafficMirrorTargetResult struct {
	// Creation time of the mirror session.
	CreatedAt string `pulumi:"createdAt"`
	// Listener description. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length must be between 0 and 255 characters. If not specified, the default value is an empty string.
	Description string `pulumi:"description"`
	// Uniquely identifies the resource.
	Id string `pulumi:"id"`
	// Resource ID of the mirror target.
	InstanceId string `pulumi:"instanceId"`
	// Resource type of the mirror target. NetworkInterface: Elastic network interface. ClbInstance: Classic load balancer.
	InstanceType string `pulumi:"instanceType"`
	// Name of the project to which the mirror target belongs. If not specified, it will be added to the default project.
	ProjectName string `pulumi:"projectName"`
	// Status of the mirror target. Available: Available. Creating: Creating.
	Status string `pulumi:"status"`
	// Tag information of the mirror target.
	Tags []GetTrafficMirrorTargetTag `pulumi:"tags"`
	// ID of the mirror target.
	TrafficMirrorTargetId string `pulumi:"trafficMirrorTargetId"`
	// Listener name. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length must be between 1 and 128 characters. If not specified, the default is 'protocol-port' as the listener name.
	TrafficMirrorTargetName string `pulumi:"trafficMirrorTargetName"`
	// Update time of the mirror session.
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupTrafficMirrorTargetOutput(ctx *pulumi.Context, args LookupTrafficMirrorTargetOutputArgs, opts ...pulumi.InvokeOption) LookupTrafficMirrorTargetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTrafficMirrorTargetResultOutput, error) {
			args := v.(LookupTrafficMirrorTargetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("volcenginecc:vpc/getTrafficMirrorTarget:getTrafficMirrorTarget", args, LookupTrafficMirrorTargetResultOutput{}, options).(LookupTrafficMirrorTargetResultOutput), nil
		}).(LookupTrafficMirrorTargetResultOutput)
}

// A collection of arguments for invoking getTrafficMirrorTarget.
type LookupTrafficMirrorTargetOutputArgs struct {
	// Uniquely identifies the resource.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupTrafficMirrorTargetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTrafficMirrorTargetArgs)(nil)).Elem()
}

// A collection of values returned by getTrafficMirrorTarget.
type LookupTrafficMirrorTargetResultOutput struct{ *pulumi.OutputState }

func (LookupTrafficMirrorTargetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTrafficMirrorTargetResult)(nil)).Elem()
}

func (o LookupTrafficMirrorTargetResultOutput) ToLookupTrafficMirrorTargetResultOutput() LookupTrafficMirrorTargetResultOutput {
	return o
}

func (o LookupTrafficMirrorTargetResultOutput) ToLookupTrafficMirrorTargetResultOutputWithContext(ctx context.Context) LookupTrafficMirrorTargetResultOutput {
	return o
}

// Creation time of the mirror session.
func (o LookupTrafficMirrorTargetResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Listener description. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length must be between 0 and 255 characters. If not specified, the default value is an empty string.
func (o LookupTrafficMirrorTargetResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.Description }).(pulumi.StringOutput)
}

// Uniquely identifies the resource.
func (o LookupTrafficMirrorTargetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.Id }).(pulumi.StringOutput)
}

// Resource ID of the mirror target.
func (o LookupTrafficMirrorTargetResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

// Resource type of the mirror target. NetworkInterface: Elastic network interface. ClbInstance: Classic load balancer.
func (o LookupTrafficMirrorTargetResultOutput) InstanceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.InstanceType }).(pulumi.StringOutput)
}

// Name of the project to which the mirror target belongs. If not specified, it will be added to the default project.
func (o LookupTrafficMirrorTargetResultOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.ProjectName }).(pulumi.StringOutput)
}

// Status of the mirror target. Available: Available. Creating: Creating.
func (o LookupTrafficMirrorTargetResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.Status }).(pulumi.StringOutput)
}

// Tag information of the mirror target.
func (o LookupTrafficMirrorTargetResultOutput) Tags() GetTrafficMirrorTargetTagArrayOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) []GetTrafficMirrorTargetTag { return v.Tags }).(GetTrafficMirrorTargetTagArrayOutput)
}

// ID of the mirror target.
func (o LookupTrafficMirrorTargetResultOutput) TrafficMirrorTargetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.TrafficMirrorTargetId }).(pulumi.StringOutput)
}

// Listener name. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length must be between 1 and 128 characters. If not specified, the default is 'protocol-port' as the listener name.
func (o LookupTrafficMirrorTargetResultOutput) TrafficMirrorTargetName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.TrafficMirrorTargetName }).(pulumi.StringOutput)
}

// Update time of the mirror session.
func (o LookupTrafficMirrorTargetResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTrafficMirrorTargetResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTrafficMirrorTargetResultOutput{})
}
